/*
 * Aptly API
 *
 * Aptly operations are also available via REST API served with `aptly api serve`.  On Debian based systems, a package `aptly-api` is available, which will run aptly as systemd service as dedicated aptly-api user.  Some configuration changes (S3 publishing endpoints, ...) will require restarting the aptly service in order to take effect.  The REST API shouldn't be exposed to the Internet as there is no authentication/protection, consider using a HTTP proxy (e.g. nginx) to add https and authentication.  #### Aptly REST API Documentation 
 *
 * The version of the OpenAPI document: 1.6.2+20260228114657.9defe70
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DebPublishedRepo {
    /// Provide index files per hash also
    #[serde(rename = "AcquireByHash", skip_serializing_if = "Option::is_none")]
    pub acquire_by_hash: Option<bool>,
    /// Architectures is a list of all architectures published
    #[serde(rename = "Architectures", skip_serializing_if = "Option::is_none")]
    pub architectures: Option<Vec<String>>,
    #[serde(rename = "ButAutomaticUpgrades", skip_serializing_if = "Option::is_none")]
    pub but_automatic_upgrades: Option<String>,
    #[serde(rename = "Codename", skip_serializing_if = "Option::is_none")]
    pub codename: Option<String>,
    /// Legacy fields for compatibility with old published repositories (< 0.6)
    #[serde(rename = "Component", skip_serializing_if = "Option::is_none")]
    pub component: Option<String>,
    #[serde(rename = "Distribution", skip_serializing_if = "Option::is_none")]
    pub distribution: Option<String>,
    #[serde(rename = "Label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    /// Support multiple distributions
    #[serde(rename = "MultiDist", skip_serializing_if = "Option::is_none")]
    pub multi_dist: Option<bool>,
    #[serde(rename = "NotAutomatic", skip_serializing_if = "Option::is_none")]
    pub not_automatic: Option<String>,
    #[serde(rename = "Origin", skip_serializing_if = "Option::is_none")]
    pub origin: Option<String>,
    #[serde(rename = "Prefix", skip_serializing_if = "Option::is_none")]
    pub prefix: Option<String>,
    /// Revision
    #[serde(rename = "Revision", skip_serializing_if = "Option::is_none")]
    pub revision: Option<Box<models::DebPublishedRepoRevision>>,
    /// An optional field containing a comma separated list of OpenPGP key fingerprints to be used for validating the next Release file
    #[serde(rename = "SignedBy", skip_serializing_if = "Option::is_none")]
    pub signed_by: Option<String>,
    /// Skip bz2 compression for index files
    #[serde(rename = "SkipBz2", skip_serializing_if = "Option::is_none")]
    pub skip_bz2: Option<bool>,
    /// Skip contents generation
    #[serde(rename = "SkipContents", skip_serializing_if = "Option::is_none")]
    pub skip_contents: Option<bool>,
    /// SourceKind is \"local\"/\"repo\"
    #[serde(rename = "SourceKind", skip_serializing_if = "Option::is_none")]
    pub source_kind: Option<String>,
    /// SourceUUID is UUID of either snapshot or local repo
    #[serde(rename = "SourceUUID", skip_serializing_if = "Option::is_none")]
    pub source_uuid: Option<String>,
    /// Map of sources by each component: component name -> source UUID
    #[serde(rename = "Sources", skip_serializing_if = "Option::is_none")]
    pub sources: Option<std::collections::HashMap<String, String>>,
    /// Storage & Prefix & distribution should be unique across all published repositories
    #[serde(rename = "Storage", skip_serializing_if = "Option::is_none")]
    pub storage: Option<String>,
    #[serde(rename = "Suite", skip_serializing_if = "Option::is_none")]
    pub suite: Option<String>,
    /// Internal unique ID
    #[serde(rename = "UUID", skip_serializing_if = "Option::is_none")]
    pub uuid: Option<String>,
}

impl DebPublishedRepo {
    pub fn new() -> DebPublishedRepo {
        DebPublishedRepo {
            acquire_by_hash: None,
            architectures: None,
            but_automatic_upgrades: None,
            codename: None,
            component: None,
            distribution: None,
            label: None,
            multi_dist: None,
            not_automatic: None,
            origin: None,
            prefix: None,
            revision: None,
            signed_by: None,
            skip_bz2: None,
            skip_contents: None,
            source_kind: None,
            source_uuid: None,
            sources: None,
            storage: None,
            suite: None,
            uuid: None,
        }
    }
}

