/*
 * Aptly API
 *
 * Aptly operations are also available via REST API served with `aptly api serve`.  On Debian based systems, a package `aptly-api` is available, which will run aptly as systemd service as dedicated aptly-api user.  Some configuration changes (S3 publishing endpoints, ...) will require restarting the aptly service in order to take effect.  The REST API shouldn't be exposed to the Internet as there is no authentication/protection, consider using a HTTP proxy (e.g. nginx) to add https and authentication.  #### Aptly REST API Documentation 
 *
 * The version of the OpenAPI document: 1.6.2+20260228114657.9defe70
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DebSnapshot {
    #[serde(rename = "ButAutomaticUpgrades", skip_serializing_if = "Option::is_none")]
    pub but_automatic_upgrades: Option<String>,
    /// Date of creation
    #[serde(rename = "CreatedAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    /// Description of how snapshot was created
    #[serde(rename = "Description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "LocalRepos", skip_serializing_if = "Option::is_none")]
    pub local_repos: Option<Vec<models::DebLocalRepo>>,
    /// Human-readable name
    #[serde(rename = "Name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "NotAutomatic", skip_serializing_if = "Option::is_none")]
    pub not_automatic: Option<String>,
    #[serde(rename = "Origin", skip_serializing_if = "Option::is_none")]
    pub origin: Option<String>,
    #[serde(rename = "Packages", skip_serializing_if = "Option::is_none")]
    pub packages: Option<Vec<String>>,
    #[serde(rename = "RemoteRepos", skip_serializing_if = "Option::is_none")]
    pub remote_repos: Option<Vec<models::DebRemoteRepo>>,
    /// Sources
    #[serde(rename = "Snapshots", skip_serializing_if = "Option::is_none")]
    pub snapshots: Option<Vec<models::DebSnapshot>>,
    /// Source: kind + ID
    #[serde(rename = "SourceKind", skip_serializing_if = "Option::is_none")]
    pub source_kind: Option<String>,
}

impl DebSnapshot {
    pub fn new() -> DebSnapshot {
        DebSnapshot {
            but_automatic_upgrades: None,
            created_at: None,
            description: None,
            local_repos: None,
            name: None,
            not_automatic: None,
            origin: None,
            packages: None,
            remote_repos: None,
            snapshots: None,
            source_kind: None,
        }
    }
}

