/*
Aptly API

Testing ReposAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package aptly

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_aptly_ReposAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ReposAPIService ApiReposGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ReposAPI.ApiReposGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ReposAPIService ApiReposNameCopySrcFilePost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var name string
		var src string
		var file string

		resp, httpRes, err := apiClient.ReposAPI.ApiReposNameCopySrcFilePost(context.Background(), name, src, file).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ReposAPIService ApiReposNameDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var name string

		resp, httpRes, err := apiClient.ReposAPI.ApiReposNameDelete(context.Background(), name).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ReposAPIService ApiReposNameFileDirFilePost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var name string
		var dir string
		var file string

		resp, httpRes, err := apiClient.ReposAPI.ApiReposNameFileDirFilePost(context.Background(), name, dir, file).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ReposAPIService ApiReposNameFileDirPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var name string
		var dir string

		resp, httpRes, err := apiClient.ReposAPI.ApiReposNameFileDirPost(context.Background(), name, dir).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ReposAPIService ApiReposNameGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var name string

		resp, httpRes, err := apiClient.ReposAPI.ApiReposNameGet(context.Background(), name).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ReposAPIService ApiReposNameIncludeDirFilePost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var name string
		var dir string
		var file string

		resp, httpRes, err := apiClient.ReposAPI.ApiReposNameIncludeDirFilePost(context.Background(), name, dir, file).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ReposAPIService ApiReposNameIncludeDirPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var name string
		var dir string

		resp, httpRes, err := apiClient.ReposAPI.ApiReposNameIncludeDirPost(context.Background(), name, dir).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ReposAPIService ApiReposNamePackagesDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var name string

		resp, httpRes, err := apiClient.ReposAPI.ApiReposNamePackagesDelete(context.Background(), name).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ReposAPIService ApiReposNamePackagesGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var name string

		resp, httpRes, err := apiClient.ReposAPI.ApiReposNamePackagesGet(context.Background(), name).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ReposAPIService ApiReposNamePackagesPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var name string

		resp, httpRes, err := apiClient.ReposAPI.ApiReposNamePackagesPost(context.Background(), name).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ReposAPIService ApiReposNamePut", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var name string

		resp, httpRes, err := apiClient.ReposAPI.ApiReposNamePut(context.Background(), name).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ReposAPIService ApiReposPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ReposAPI.ApiReposPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ReposAPIService ApiStoragePkgPathGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var storage string
		var pkgPath string

		httpRes, err := apiClient.ReposAPI.ApiStoragePkgPathGet(context.Background(), storage, pkgPath).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
