/* tslint:disable */
/* eslint-disable */
/**
 * Aptly API
 * Aptly operations are also available via REST API served with `aptly api serve`.  On Debian based systems, a package `aptly-api` is available, which will run aptly as systemd service as dedicated aptly-api user.  Some configuration changes (S3 publishing endpoints, ...) will require restarting the aptly service in order to take effect.  The REST API shouldn\'t be exposed to the Internet as there is no authentication/protection, consider using a HTTP proxy (e.g. nginx) to add https and authentication.  #### Aptly REST API Documentation 
 *
 * The version of the OpenAPI document: 1.6.2+20260308145521.8e943a3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiError,
} from '../models/index';
import {
    ApiErrorFromJSON,
    ApiErrorToJSON,
} from '../models/index';

export interface ApiFilesDirDeleteRequest {
    dir: string;
}

export interface ApiFilesDirGetRequest {
    dir: string;
}

export interface ApiFilesDirNameDeleteRequest {
    dir: string;
    name: string;
}

export interface ApiFilesDirPostRequest {
    dir: string;
    files: Blob;
}

/**
 * 
 */
export class FilesApi extends runtime.BaseAPI {

    /**
     * Creates request options for apiFilesDirDelete without sending the request
     */
    async apiFilesDirDeleteRequestOpts(requestParameters: ApiFilesDirDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['dir'] == null) {
            throw new runtime.RequiredError(
                'dir',
                'Required parameter "dir" was null or undefined when calling apiFilesDirDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/files/{dir}`;
        urlPath = urlPath.replace(`{${"dir"}}`, encodeURIComponent(String(requestParameters['dir'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * **Delete upload directory and uploaded files within**  **Example:** ``` $ curl -X DELETE http://localhost:8080/api/files/aptly-0.9 {} ```
     * Delete Directory
     */
    async apiFilesDirDeleteRaw(requestParameters: ApiFilesDirDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.apiFilesDirDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * **Delete upload directory and uploaded files within**  **Example:** ``` $ curl -X DELETE http://localhost:8080/api/files/aptly-0.9 {} ```
     * Delete Directory
     */
    async apiFilesDirDelete(requestParameters: ApiFilesDirDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.apiFilesDirDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiFilesDirGet without sending the request
     */
    async apiFilesDirGetRequestOpts(requestParameters: ApiFilesDirGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['dir'] == null) {
            throw new runtime.RequiredError(
                'dir',
                'Required parameter "dir" was null or undefined when calling apiFilesDirGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/files/{dir}`;
        urlPath = urlPath.replace(`{${"dir"}}`, encodeURIComponent(String(requestParameters['dir'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * **Show uploaded files in upload directory**  **Example:** ``` $ curl http://localhost:8080/api/files/aptly-0.9 [\"aptly_0.9~dev+217+ge5d646c_i386.deb\"] ```
     * List Files
     */
    async apiFilesDirGetRaw(requestParameters: ApiFilesDirGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>> {
        const requestOptions = await this.apiFilesDirGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * **Show uploaded files in upload directory**  **Example:** ``` $ curl http://localhost:8080/api/files/aptly-0.9 [\"aptly_0.9~dev+217+ge5d646c_i386.deb\"] ```
     * List Files
     */
    async apiFilesDirGet(requestParameters: ApiFilesDirGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>> {
        const response = await this.apiFilesDirGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiFilesDirNameDelete without sending the request
     */
    async apiFilesDirNameDeleteRequestOpts(requestParameters: ApiFilesDirNameDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['dir'] == null) {
            throw new runtime.RequiredError(
                'dir',
                'Required parameter "dir" was null or undefined when calling apiFilesDirNameDelete().'
            );
        }

        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling apiFilesDirNameDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/files/{dir}/{name}`;
        urlPath = urlPath.replace(`{${"dir"}}`, encodeURIComponent(String(requestParameters['dir'])));
        urlPath = urlPath.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * **Delete a uploaded file in upload directory**  **Example:** ``` $ curl -X DELETE http://localhost:8080/api/files/aptly-0.9/aptly_0.9~dev+217+ge5d646c_i386.deb {} ```
     * Delete File
     */
    async apiFilesDirNameDeleteRaw(requestParameters: ApiFilesDirNameDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.apiFilesDirNameDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * **Delete a uploaded file in upload directory**  **Example:** ``` $ curl -X DELETE http://localhost:8080/api/files/aptly-0.9/aptly_0.9~dev+217+ge5d646c_i386.deb {} ```
     * Delete File
     */
    async apiFilesDirNameDelete(requestParameters: ApiFilesDirNameDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.apiFilesDirNameDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiFilesDirPost without sending the request
     */
    async apiFilesDirPostRequestOpts(requestParameters: ApiFilesDirPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['dir'] == null) {
            throw new runtime.RequiredError(
                'dir',
                'Required parameter "dir" was null or undefined when calling apiFilesDirPost().'
            );
        }

        if (requestParameters['files'] == null) {
            throw new runtime.RequiredError(
                'files',
                'Required parameter "files" was null or undefined when calling apiFilesDirPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['files'] != null) {
            formParams.append('files', requestParameters['files'] as any);
        }


        let urlPath = `/api/files/{dir}`;
        urlPath = urlPath.replace(`{${"dir"}}`, encodeURIComponent(String(requestParameters['dir'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        };
    }

    /**
     * **Upload files to a directory**  - one or more files can be uploaded - existing uploaded are overwritten  **Example:** ``` $ curl -X POST -F file=@aptly_0.9~dev+217+ge5d646c_i386.deb http://localhost:8080/api/files/aptly-0.9 [\"aptly-0.9/aptly_0.9~dev+217+ge5d646c_i386.deb\"] ```
     * Upload Files
     */
    async apiFilesDirPostRaw(requestParameters: ApiFilesDirPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>> {
        const requestOptions = await this.apiFilesDirPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * **Upload files to a directory**  - one or more files can be uploaded - existing uploaded are overwritten  **Example:** ``` $ curl -X POST -F file=@aptly_0.9~dev+217+ge5d646c_i386.deb http://localhost:8080/api/files/aptly-0.9 [\"aptly-0.9/aptly_0.9~dev+217+ge5d646c_i386.deb\"] ```
     * Upload Files
     */
    async apiFilesDirPost(requestParameters: ApiFilesDirPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>> {
        const response = await this.apiFilesDirPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiFilesGet without sending the request
     */
    async apiFilesGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/files`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * **Get list of upload directories**  **Example:** ``` $ curl http://localhost:8080/api/files [\"aptly-0.9\"] ```
     * List Directories
     */
    async apiFilesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>> {
        const requestOptions = await this.apiFilesGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * **Get list of upload directories**  **Example:** ``` $ curl http://localhost:8080/api/files [\"aptly-0.9\"] ```
     * List Directories
     */
    async apiFilesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>> {
        const response = await this.apiFilesGetRaw(initOverrides);
        return await response.value();
    }

}
