/* tslint:disable */
/* eslint-disable */
/**
 * Aptly API
 * Aptly operations are also available via REST API served with `aptly api serve`.  On Debian based systems, a package `aptly-api` is available, which will run aptly as systemd service as dedicated aptly-api user.  Some configuration changes (S3 publishing endpoints, ...) will require restarting the aptly service in order to take effect.  The REST API shouldn\'t be exposed to the Internet as there is no authentication/protection, consider using a HTTP proxy (e.g. nginx) to add https and authentication.  #### Aptly REST API Documentation 
 *
 * The version of the OpenAPI document: 1.6.2+20260308145521.8e943a3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiError,
  DebPackage,
} from '../models/index';
import {
    ApiErrorFromJSON,
    ApiErrorToJSON,
    DebPackageFromJSON,
    DebPackageToJSON,
} from '../models/index';

export interface ApiPackagesGetRequest {
    q?: string;
    format?: string;
}

export interface ApiPackagesKeyFileGetRequest {
    key: string;
}

export interface ApiPackagesKeyGetRequest {
    key: string;
}

/**
 * 
 */
export class PackagesApi extends runtime.BaseAPI {

    /**
     * Creates request options for apiPackagesGet without sending the request
     */
    async apiPackagesGetRequestOpts(requestParameters: ApiPackagesGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        if (requestParameters['format'] != null) {
            queryParameters['format'] = requestParameters['format'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/packages`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * **Get list of packages**
     * List Packages
     */
    async apiPackagesGetRaw(requestParameters: ApiPackagesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>> {
        const requestOptions = await this.apiPackagesGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * **Get list of packages**
     * List Packages
     */
    async apiPackagesGet(requestParameters: ApiPackagesGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>> {
        const response = await this.apiPackagesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiPackagesKeyFileGet without sending the request
     */
    async apiPackagesKeyFileGetRequestOpts(requestParameters: ApiPackagesKeyFileGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['key'] == null) {
            throw new runtime.RequiredError(
                'key',
                'Required parameter "key" was null or undefined when calling apiPackagesKeyFileGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/packages/{key}/file`;
        urlPath = urlPath.replace(`{${"key"}}`, encodeURIComponent(String(requestParameters['key'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * **Download a package file directly from the pool by package key** Serves the first (primary) file associated with the package.
     * Download Package File
     */
    async apiPackagesKeyFileGetRaw(requestParameters: ApiPackagesKeyFileGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        const requestOptions = await this.apiPackagesKeyFileGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * **Download a package file directly from the pool by package key** Serves the first (primary) file associated with the package.
     * Download Package File
     */
    async apiPackagesKeyFileGet(requestParameters: ApiPackagesKeyFileGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.apiPackagesKeyFileGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiPackagesKeyGet without sending the request
     */
    async apiPackagesKeyGetRequestOpts(requestParameters: ApiPackagesKeyGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['key'] == null) {
            throw new runtime.RequiredError(
                'key',
                'Required parameter "key" was null or undefined when calling apiPackagesKeyGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/packages/{key}`;
        urlPath = urlPath.replace(`{${"key"}}`, encodeURIComponent(String(requestParameters['key'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * **Show information about package by package key** Package keys could be obtained from various GET .../packages APIs.
     * Get Package Info
     */
    async apiPackagesKeyGetRaw(requestParameters: ApiPackagesKeyGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DebPackage>> {
        const requestOptions = await this.apiPackagesKeyGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DebPackageFromJSON(jsonValue));
    }

    /**
     * **Show information about package by package key** Package keys could be obtained from various GET .../packages APIs.
     * Get Package Info
     */
    async apiPackagesKeyGet(requestParameters: ApiPackagesKeyGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DebPackage> {
        const response = await this.apiPackagesKeyGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
