/* tslint:disable */
/* eslint-disable */
/**
 * Aptly API
 * Aptly operations are also available via REST API served with `aptly api serve`.  On Debian based systems, a package `aptly-api` is available, which will run aptly as systemd service as dedicated aptly-api user.  Some configuration changes (S3 publishing endpoints, ...) will require restarting the aptly service in order to take effect.  The REST API shouldn\'t be exposed to the Internet as there is no authentication/protection, consider using a HTTP proxy (e.g. nginx) to add https and authentication.  #### Aptly REST API Documentation 
 *
 * The version of the OpenAPI document: 1.6.2+20260308145521.8e943a3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiError,
  ApiPublishedRepoCreateParams,
  ApiPublishedRepoUpdateParams,
  ApiPublishedRepoUpdateSwitchParams,
  ApiSourceParams,
  DebPublishedRepo,
  DebSourceEntry,
} from '../models/index';
import {
    ApiErrorFromJSON,
    ApiErrorToJSON,
    ApiPublishedRepoCreateParamsFromJSON,
    ApiPublishedRepoCreateParamsToJSON,
    ApiPublishedRepoUpdateParamsFromJSON,
    ApiPublishedRepoUpdateParamsToJSON,
    ApiPublishedRepoUpdateSwitchParamsFromJSON,
    ApiPublishedRepoUpdateSwitchParamsToJSON,
    ApiSourceParamsFromJSON,
    ApiSourceParamsToJSON,
    DebPublishedRepoFromJSON,
    DebPublishedRepoToJSON,
    DebSourceEntryFromJSON,
    DebSourceEntryToJSON,
} from '../models/index';

export interface ApiPublishPrefixDistributionDeleteRequest {
    prefix: string;
    distribution: string;
    force: number;
    skipCleanup: number;
    async?: boolean;
}

export interface ApiPublishPrefixDistributionGetRequest {
    prefix: string;
    distribution: string;
}

export interface ApiPublishPrefixDistributionPutRequest {
    prefix: string;
    distribution: string;
    request: ApiPublishedRepoUpdateSwitchParams;
    async?: boolean;
}

export interface ApiPublishPrefixDistributionSourcesComponentDeleteRequest {
    prefix: string;
    distribution: string;
    component: string;
    async?: boolean;
}

export interface ApiPublishPrefixDistributionSourcesComponentPutRequest {
    prefix: string;
    distribution: string;
    component: string;
    request: ApiSourceParams;
    async?: boolean;
}

export interface ApiPublishPrefixDistributionSourcesDeleteRequest {
    prefix: string;
    distribution: string;
    async?: boolean;
}

export interface ApiPublishPrefixDistributionSourcesGetRequest {
    prefix: string;
    distribution: string;
}

export interface ApiPublishPrefixDistributionSourcesPostRequest {
    prefix: string;
    distribution: string;
    request: ApiSourceParams;
    async?: boolean;
}

export interface ApiPublishPrefixDistributionSourcesPutRequest {
    prefix: string;
    distribution: string;
    request: Array<ApiSourceParams>;
    async?: boolean;
}

export interface ApiPublishPrefixDistributionUpdatePostRequest {
    prefix: string;
    distribution: string;
    request: ApiPublishedRepoUpdateParams;
    async?: boolean;
}

export interface ApiPublishPrefixPostRequest {
    prefix: string;
    request: ApiPublishedRepoCreateParams;
    async?: boolean;
}

/**
 * 
 */
export class PublishApi extends runtime.BaseAPI {

    /**
     * Creates request options for apiPublishGet without sending the request
     */
    async apiPublishGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/publish`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * **Get list of published repositories**  Return list of published repositories including detailed information.  See also: `aptly publish list`
     * List Published Repositories
     */
    async apiPublishGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<DebPublishedRepo>>> {
        const requestOptions = await this.apiPublishGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DebPublishedRepoFromJSON));
    }

    /**
     * **Get list of published repositories**  Return list of published repositories including detailed information.  See also: `aptly publish list`
     * List Published Repositories
     */
    async apiPublishGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<DebPublishedRepo>> {
        const response = await this.apiPublishGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiPublishPrefixDistributionDelete without sending the request
     */
    async apiPublishPrefixDistributionDeleteRequestOpts(requestParameters: ApiPublishPrefixDistributionDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['prefix'] == null) {
            throw new runtime.RequiredError(
                'prefix',
                'Required parameter "prefix" was null or undefined when calling apiPublishPrefixDistributionDelete().'
            );
        }

        if (requestParameters['distribution'] == null) {
            throw new runtime.RequiredError(
                'distribution',
                'Required parameter "distribution" was null or undefined when calling apiPublishPrefixDistributionDelete().'
            );
        }

        if (requestParameters['force'] == null) {
            throw new runtime.RequiredError(
                'force',
                'Required parameter "force" was null or undefined when calling apiPublishPrefixDistributionDelete().'
            );
        }

        if (requestParameters['skipCleanup'] == null) {
            throw new runtime.RequiredError(
                'skipCleanup',
                'Required parameter "skipCleanup" was null or undefined when calling apiPublishPrefixDistributionDelete().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['force'] != null) {
            queryParameters['force'] = requestParameters['force'];
        }

        if (requestParameters['skipCleanup'] != null) {
            queryParameters['skipCleanup'] = requestParameters['skipCleanup'];
        }

        if (requestParameters['async'] != null) {
            queryParameters['_async'] = requestParameters['async'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/publish/{prefix}/{distribution}`;
        urlPath = urlPath.replace(`{${"prefix"}}`, encodeURIComponent(String(requestParameters['prefix'])));
        urlPath = urlPath.replace(`{${"distribution"}}`, encodeURIComponent(String(requestParameters['distribution'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * **Delete a published repository**  Delete a distribution of a published repository and remove associated files.  If no other published repositories share the same prefix, all files inside the prefix will be removed.  See also: `aptly publish drop`
     * Delete Published Repository
     */
    async apiPublishPrefixDistributionDeleteRaw(requestParameters: ApiPublishPrefixDistributionDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.apiPublishPrefixDistributionDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * **Delete a published repository**  Delete a distribution of a published repository and remove associated files.  If no other published repositories share the same prefix, all files inside the prefix will be removed.  See also: `aptly publish drop`
     * Delete Published Repository
     */
    async apiPublishPrefixDistributionDelete(requestParameters: ApiPublishPrefixDistributionDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiPublishPrefixDistributionDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for apiPublishPrefixDistributionGet without sending the request
     */
    async apiPublishPrefixDistributionGetRequestOpts(requestParameters: ApiPublishPrefixDistributionGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['prefix'] == null) {
            throw new runtime.RequiredError(
                'prefix',
                'Required parameter "prefix" was null or undefined when calling apiPublishPrefixDistributionGet().'
            );
        }

        if (requestParameters['distribution'] == null) {
            throw new runtime.RequiredError(
                'distribution',
                'Required parameter "distribution" was null or undefined when calling apiPublishPrefixDistributionGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/publish/{prefix}/{distribution}`;
        urlPath = urlPath.replace(`{${"prefix"}}`, encodeURIComponent(String(requestParameters['prefix'])));
        urlPath = urlPath.replace(`{${"distribution"}}`, encodeURIComponent(String(requestParameters['distribution'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * **Get published repository information**  Show detailed information of a published repository.  See also: `aptly publish show`
     * Show Published Repository
     */
    async apiPublishPrefixDistributionGetRaw(requestParameters: ApiPublishPrefixDistributionGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DebPublishedRepo>> {
        const requestOptions = await this.apiPublishPrefixDistributionGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DebPublishedRepoFromJSON(jsonValue));
    }

    /**
     * **Get published repository information**  Show detailed information of a published repository.  See also: `aptly publish show`
     * Show Published Repository
     */
    async apiPublishPrefixDistributionGet(requestParameters: ApiPublishPrefixDistributionGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DebPublishedRepo> {
        const response = await this.apiPublishPrefixDistributionGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiPublishPrefixDistributionPut without sending the request
     */
    async apiPublishPrefixDistributionPutRequestOpts(requestParameters: ApiPublishPrefixDistributionPutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['prefix'] == null) {
            throw new runtime.RequiredError(
                'prefix',
                'Required parameter "prefix" was null or undefined when calling apiPublishPrefixDistributionPut().'
            );
        }

        if (requestParameters['distribution'] == null) {
            throw new runtime.RequiredError(
                'distribution',
                'Required parameter "distribution" was null or undefined when calling apiPublishPrefixDistributionPut().'
            );
        }

        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling apiPublishPrefixDistributionPut().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['async'] != null) {
            queryParameters['_async'] = requestParameters['async'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/publish/{prefix}/{distribution}`;
        urlPath = urlPath.replace(`{${"prefix"}}`, encodeURIComponent(String(requestParameters['prefix'])));
        urlPath = urlPath.replace(`{${"distribution"}}`, encodeURIComponent(String(requestParameters['distribution'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ApiPublishedRepoUpdateSwitchParamsToJSON(requestParameters['request']),
        };
    }

    /**
     * **Update a published repository**  Update a published local repository or switch snapshot.  For published local repositories: * update to match local repository contents  For published snapshots: * switch components to new snapshot  See also: `aptly publish update` / `aptly publish switch`
     * Update Published Repository
     */
    async apiPublishPrefixDistributionPutRaw(requestParameters: ApiPublishPrefixDistributionPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DebPublishedRepo>> {
        const requestOptions = await this.apiPublishPrefixDistributionPutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DebPublishedRepoFromJSON(jsonValue));
    }

    /**
     * **Update a published repository**  Update a published local repository or switch snapshot.  For published local repositories: * update to match local repository contents  For published snapshots: * switch components to new snapshot  See also: `aptly publish update` / `aptly publish switch`
     * Update Published Repository
     */
    async apiPublishPrefixDistributionPut(requestParameters: ApiPublishPrefixDistributionPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DebPublishedRepo> {
        const response = await this.apiPublishPrefixDistributionPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiPublishPrefixDistributionSourcesComponentDelete without sending the request
     */
    async apiPublishPrefixDistributionSourcesComponentDeleteRequestOpts(requestParameters: ApiPublishPrefixDistributionSourcesComponentDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['prefix'] == null) {
            throw new runtime.RequiredError(
                'prefix',
                'Required parameter "prefix" was null or undefined when calling apiPublishPrefixDistributionSourcesComponentDelete().'
            );
        }

        if (requestParameters['distribution'] == null) {
            throw new runtime.RequiredError(
                'distribution',
                'Required parameter "distribution" was null or undefined when calling apiPublishPrefixDistributionSourcesComponentDelete().'
            );
        }

        if (requestParameters['component'] == null) {
            throw new runtime.RequiredError(
                'component',
                'Required parameter "component" was null or undefined when calling apiPublishPrefixDistributionSourcesComponentDelete().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['async'] != null) {
            queryParameters['_async'] = requestParameters['async'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/publish/{prefix}/{distribution}/sources/{component}`;
        urlPath = urlPath.replace(`{${"prefix"}}`, encodeURIComponent(String(requestParameters['prefix'])));
        urlPath = urlPath.replace(`{${"distribution"}}`, encodeURIComponent(String(requestParameters['distribution'])));
        urlPath = urlPath.replace(`{${"component"}}`, encodeURIComponent(String(requestParameters['component'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * **Remove a source component from a published repo**  Remove a source component (snapshot / local repo) from a published repository.  This call does not publish the changes, but rather schedules them for a subsequent publish update call (i.e `PUT /api/publish/{prefix}/{distribution}` / `POST /api/publish/{prefix}/{distribution}/update`).  See also: `aptly publish source remove`
     * Remove Source Component
     */
    async apiPublishPrefixDistributionSourcesComponentDeleteRaw(requestParameters: ApiPublishPrefixDistributionSourcesComponentDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.apiPublishPrefixDistributionSourcesComponentDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * **Remove a source component from a published repo**  Remove a source component (snapshot / local repo) from a published repository.  This call does not publish the changes, but rather schedules them for a subsequent publish update call (i.e `PUT /api/publish/{prefix}/{distribution}` / `POST /api/publish/{prefix}/{distribution}/update`).  See also: `aptly publish source remove`
     * Remove Source Component
     */
    async apiPublishPrefixDistributionSourcesComponentDelete(requestParameters: ApiPublishPrefixDistributionSourcesComponentDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiPublishPrefixDistributionSourcesComponentDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for apiPublishPrefixDistributionSourcesComponentPut without sending the request
     */
    async apiPublishPrefixDistributionSourcesComponentPutRequestOpts(requestParameters: ApiPublishPrefixDistributionSourcesComponentPutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['prefix'] == null) {
            throw new runtime.RequiredError(
                'prefix',
                'Required parameter "prefix" was null or undefined when calling apiPublishPrefixDistributionSourcesComponentPut().'
            );
        }

        if (requestParameters['distribution'] == null) {
            throw new runtime.RequiredError(
                'distribution',
                'Required parameter "distribution" was null or undefined when calling apiPublishPrefixDistributionSourcesComponentPut().'
            );
        }

        if (requestParameters['component'] == null) {
            throw new runtime.RequiredError(
                'component',
                'Required parameter "component" was null or undefined when calling apiPublishPrefixDistributionSourcesComponentPut().'
            );
        }

        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling apiPublishPrefixDistributionSourcesComponentPut().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['async'] != null) {
            queryParameters['_async'] = requestParameters['async'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/publish/{prefix}/{distribution}/sources/{component}`;
        urlPath = urlPath.replace(`{${"prefix"}}`, encodeURIComponent(String(requestParameters['prefix'])));
        urlPath = urlPath.replace(`{${"distribution"}}`, encodeURIComponent(String(requestParameters['distribution'])));
        urlPath = urlPath.replace(`{${"component"}}`, encodeURIComponent(String(requestParameters['component'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ApiSourceParamsToJSON(requestParameters['request']),
        };
    }

    /**
     * **Update the source component of a published repository**  Update a component of a snapshot or local repository to be published.  This call does not publish the changes, but rather schedules them for a subsequent publish update call (i.e `PUT /api/publish/{prefix}/{distribution}` / `POST /api/publish/{prefix}/{distribution}/update`).  See also: `aptly publish source update`
     * Update Source Component
     */
    async apiPublishPrefixDistributionSourcesComponentPutRaw(requestParameters: ApiPublishPrefixDistributionSourcesComponentPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.apiPublishPrefixDistributionSourcesComponentPutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * **Update the source component of a published repository**  Update a component of a snapshot or local repository to be published.  This call does not publish the changes, but rather schedules them for a subsequent publish update call (i.e `PUT /api/publish/{prefix}/{distribution}` / `POST /api/publish/{prefix}/{distribution}/update`).  See also: `aptly publish source update`
     * Update Source Component
     */
    async apiPublishPrefixDistributionSourcesComponentPut(requestParameters: ApiPublishPrefixDistributionSourcesComponentPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiPublishPrefixDistributionSourcesComponentPutRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for apiPublishPrefixDistributionSourcesDelete without sending the request
     */
    async apiPublishPrefixDistributionSourcesDeleteRequestOpts(requestParameters: ApiPublishPrefixDistributionSourcesDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['prefix'] == null) {
            throw new runtime.RequiredError(
                'prefix',
                'Required parameter "prefix" was null or undefined when calling apiPublishPrefixDistributionSourcesDelete().'
            );
        }

        if (requestParameters['distribution'] == null) {
            throw new runtime.RequiredError(
                'distribution',
                'Required parameter "distribution" was null or undefined when calling apiPublishPrefixDistributionSourcesDelete().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['async'] != null) {
            queryParameters['_async'] = requestParameters['async'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/publish/{prefix}/{distribution}/sources`;
        urlPath = urlPath.replace(`{${"prefix"}}`, encodeURIComponent(String(requestParameters['prefix'])));
        urlPath = urlPath.replace(`{${"distribution"}}`, encodeURIComponent(String(requestParameters['distribution'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * **Discard pending source component changes of a published repository**  Remove all pending changes what would be applied with a subsequent publish update call (i.e. `PUT /api/publish/{prefix}/{distribution}` / `POST /api/publish/{prefix}/{distribution}/update`).  See also: `aptly publish source drop`
     * Discard Pending Changes
     */
    async apiPublishPrefixDistributionSourcesDeleteRaw(requestParameters: ApiPublishPrefixDistributionSourcesDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.apiPublishPrefixDistributionSourcesDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * **Discard pending source component changes of a published repository**  Remove all pending changes what would be applied with a subsequent publish update call (i.e. `PUT /api/publish/{prefix}/{distribution}` / `POST /api/publish/{prefix}/{distribution}/update`).  See also: `aptly publish source drop`
     * Discard Pending Changes
     */
    async apiPublishPrefixDistributionSourcesDelete(requestParameters: ApiPublishPrefixDistributionSourcesDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiPublishPrefixDistributionSourcesDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for apiPublishPrefixDistributionSourcesGet without sending the request
     */
    async apiPublishPrefixDistributionSourcesGetRequestOpts(requestParameters: ApiPublishPrefixDistributionSourcesGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['prefix'] == null) {
            throw new runtime.RequiredError(
                'prefix',
                'Required parameter "prefix" was null or undefined when calling apiPublishPrefixDistributionSourcesGet().'
            );
        }

        if (requestParameters['distribution'] == null) {
            throw new runtime.RequiredError(
                'distribution',
                'Required parameter "distribution" was null or undefined when calling apiPublishPrefixDistributionSourcesGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/publish/{prefix}/{distribution}/sources`;
        urlPath = urlPath.replace(`{${"prefix"}}`, encodeURIComponent(String(requestParameters['prefix'])));
        urlPath = urlPath.replace(`{${"distribution"}}`, encodeURIComponent(String(requestParameters['distribution'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * **List source component changes to be applied**  Return added, removed or changed components of snapshots or local repository to be published.  The changes will be applied by a subsequent publish update call (i.e. `PUT /api/publish/{prefix}/{distribution}` / `POST /api/publish/{prefix}/{distribution}/update`).  See also: `aptly publish source list`
     * List Pending Changes
     */
    async apiPublishPrefixDistributionSourcesGetRaw(requestParameters: ApiPublishPrefixDistributionSourcesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Array<DebSourceEntry>>>> {
        const requestOptions = await this.apiPublishPrefixDistributionSourcesGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * **List source component changes to be applied**  Return added, removed or changed components of snapshots or local repository to be published.  The changes will be applied by a subsequent publish update call (i.e. `PUT /api/publish/{prefix}/{distribution}` / `POST /api/publish/{prefix}/{distribution}/update`).  See also: `aptly publish source list`
     * List Pending Changes
     */
    async apiPublishPrefixDistributionSourcesGet(requestParameters: ApiPublishPrefixDistributionSourcesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Array<DebSourceEntry>>> {
        const response = await this.apiPublishPrefixDistributionSourcesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiPublishPrefixDistributionSourcesPost without sending the request
     */
    async apiPublishPrefixDistributionSourcesPostRequestOpts(requestParameters: ApiPublishPrefixDistributionSourcesPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['prefix'] == null) {
            throw new runtime.RequiredError(
                'prefix',
                'Required parameter "prefix" was null or undefined when calling apiPublishPrefixDistributionSourcesPost().'
            );
        }

        if (requestParameters['distribution'] == null) {
            throw new runtime.RequiredError(
                'distribution',
                'Required parameter "distribution" was null or undefined when calling apiPublishPrefixDistributionSourcesPost().'
            );
        }

        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling apiPublishPrefixDistributionSourcesPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['async'] != null) {
            queryParameters['_async'] = requestParameters['async'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/publish/{prefix}/{distribution}/sources`;
        urlPath = urlPath.replace(`{${"prefix"}}`, encodeURIComponent(String(requestParameters['prefix'])));
        urlPath = urlPath.replace(`{${"distribution"}}`, encodeURIComponent(String(requestParameters['distribution'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ApiSourceParamsToJSON(requestParameters['request']),
        };
    }

    /**
     * **Add a source component to a published repo**  Add a component of a snapshot or local repository to be published.  This call does not publish the changes, but rather schedules them for a subsequent publish update call (i.e `PUT /api/publish/{prefix}/{distribution}` / `POST /api/publish/{prefix}/{distribution}/update`).  See also: `aptly publish source add`
     * Add Source Component
     */
    async apiPublishPrefixDistributionSourcesPostRaw(requestParameters: ApiPublishPrefixDistributionSourcesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.apiPublishPrefixDistributionSourcesPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * **Add a source component to a published repo**  Add a component of a snapshot or local repository to be published.  This call does not publish the changes, but rather schedules them for a subsequent publish update call (i.e `PUT /api/publish/{prefix}/{distribution}` / `POST /api/publish/{prefix}/{distribution}/update`).  See also: `aptly publish source add`
     * Add Source Component
     */
    async apiPublishPrefixDistributionSourcesPost(requestParameters: ApiPublishPrefixDistributionSourcesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiPublishPrefixDistributionSourcesPostRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for apiPublishPrefixDistributionSourcesPut without sending the request
     */
    async apiPublishPrefixDistributionSourcesPutRequestOpts(requestParameters: ApiPublishPrefixDistributionSourcesPutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['prefix'] == null) {
            throw new runtime.RequiredError(
                'prefix',
                'Required parameter "prefix" was null or undefined when calling apiPublishPrefixDistributionSourcesPut().'
            );
        }

        if (requestParameters['distribution'] == null) {
            throw new runtime.RequiredError(
                'distribution',
                'Required parameter "distribution" was null or undefined when calling apiPublishPrefixDistributionSourcesPut().'
            );
        }

        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling apiPublishPrefixDistributionSourcesPut().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['async'] != null) {
            queryParameters['_async'] = requestParameters['async'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/publish/{prefix}/{distribution}/sources`;
        urlPath = urlPath.replace(`{${"prefix"}}`, encodeURIComponent(String(requestParameters['prefix'])));
        urlPath = urlPath.replace(`{${"distribution"}}`, encodeURIComponent(String(requestParameters['distribution'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['request']!.map(ApiSourceParamsToJSON),
        };
    }

    /**
     * **Replace the source components of a published repository**  Sets the components of snapshots or local repositories to be published. Existing Sourced will be replaced.  This call does not publish the changes, but rather schedules them for a subsequent publish update call (i.e `PUT /api/publish/{prefix}/{distribution}` / `POST /api/publish/{prefix}/{distribution}/update`).  See also: `aptly publish source replace`
     * Replace Source Components
     */
    async apiPublishPrefixDistributionSourcesPutRaw(requestParameters: ApiPublishPrefixDistributionSourcesPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.apiPublishPrefixDistributionSourcesPutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * **Replace the source components of a published repository**  Sets the components of snapshots or local repositories to be published. Existing Sourced will be replaced.  This call does not publish the changes, but rather schedules them for a subsequent publish update call (i.e `PUT /api/publish/{prefix}/{distribution}` / `POST /api/publish/{prefix}/{distribution}/update`).  See also: `aptly publish source replace`
     * Replace Source Components
     */
    async apiPublishPrefixDistributionSourcesPut(requestParameters: ApiPublishPrefixDistributionSourcesPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiPublishPrefixDistributionSourcesPutRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for apiPublishPrefixDistributionUpdatePost without sending the request
     */
    async apiPublishPrefixDistributionUpdatePostRequestOpts(requestParameters: ApiPublishPrefixDistributionUpdatePostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['prefix'] == null) {
            throw new runtime.RequiredError(
                'prefix',
                'Required parameter "prefix" was null or undefined when calling apiPublishPrefixDistributionUpdatePost().'
            );
        }

        if (requestParameters['distribution'] == null) {
            throw new runtime.RequiredError(
                'distribution',
                'Required parameter "distribution" was null or undefined when calling apiPublishPrefixDistributionUpdatePost().'
            );
        }

        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling apiPublishPrefixDistributionUpdatePost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['async'] != null) {
            queryParameters['_async'] = requestParameters['async'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/publish/{prefix}/{distribution}/update`;
        urlPath = urlPath.replace(`{${"prefix"}}`, encodeURIComponent(String(requestParameters['prefix'])));
        urlPath = urlPath.replace(`{${"distribution"}}`, encodeURIComponent(String(requestParameters['distribution'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ApiPublishedRepoUpdateParamsToJSON(requestParameters['request']),
        };
    }

    /**
     * **Update a published repository**  Publish pending source component changes which were added with `Add/Remove/Replace Source Components`  See also: `aptly publish update`
     * Update Published Repository
     */
    async apiPublishPrefixDistributionUpdatePostRaw(requestParameters: ApiPublishPrefixDistributionUpdatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DebPublishedRepo>> {
        const requestOptions = await this.apiPublishPrefixDistributionUpdatePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DebPublishedRepoFromJSON(jsonValue));
    }

    /**
     * **Update a published repository**  Publish pending source component changes which were added with `Add/Remove/Replace Source Components`  See also: `aptly publish update`
     * Update Published Repository
     */
    async apiPublishPrefixDistributionUpdatePost(requestParameters: ApiPublishPrefixDistributionUpdatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DebPublishedRepo> {
        const response = await this.apiPublishPrefixDistributionUpdatePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiPublishPrefixPost without sending the request
     */
    async apiPublishPrefixPostRequestOpts(requestParameters: ApiPublishPrefixPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['prefix'] == null) {
            throw new runtime.RequiredError(
                'prefix',
                'Required parameter "prefix" was null or undefined when calling apiPublishPrefixPost().'
            );
        }

        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling apiPublishPrefixPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['async'] != null) {
            queryParameters['_async'] = requestParameters['async'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/publish/{prefix}`;
        urlPath = urlPath.replace(`{${"prefix"}}`, encodeURIComponent(String(requestParameters['prefix'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ApiPublishedRepoCreateParamsToJSON(requestParameters['request']),
        };
    }

    /**
     * **Publish a local repository or snapshot**  Create a published repository.  The prefix may contain a storage specifier, e.g. `s3:packages/`, or it may also be empty to publish to the root directory.  **Example:** ``` $ curl -X POST -H \'Content-Type: application/json\' --data \'{\"Distribution\": \"wheezy\", \"Sources\": [{\"Name\": \"aptly-repo\"}]}\' http://localhost:8080/api/publish//repos {\"Architectures\":[\"i386\"],\"Distribution\":\"wheezy\",\"Label\":\"\",\"Origin\":\"\",\"Prefix\":\".\",\"SourceKind\":\"local\",\"Sources\":[{\"Component\":\"main\",\"Name\":\"aptly-repo\"}],\"Storage\":\"\"} ```  See also: `aptly publish create`
     * Create Published Repository
     */
    async apiPublishPrefixPostRaw(requestParameters: ApiPublishPrefixPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DebPublishedRepo>> {
        const requestOptions = await this.apiPublishPrefixPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DebPublishedRepoFromJSON(jsonValue));
    }

    /**
     * **Publish a local repository or snapshot**  Create a published repository.  The prefix may contain a storage specifier, e.g. `s3:packages/`, or it may also be empty to publish to the root directory.  **Example:** ``` $ curl -X POST -H \'Content-Type: application/json\' --data \'{\"Distribution\": \"wheezy\", \"Sources\": [{\"Name\": \"aptly-repo\"}]}\' http://localhost:8080/api/publish//repos {\"Architectures\":[\"i386\"],\"Distribution\":\"wheezy\",\"Label\":\"\",\"Origin\":\"\",\"Prefix\":\".\",\"SourceKind\":\"local\",\"Sources\":[{\"Component\":\"main\",\"Name\":\"aptly-repo\"}],\"Storage\":\"\"} ```  See also: `aptly publish create`
     * Create Published Repository
     */
    async apiPublishPrefixPost(requestParameters: ApiPublishPrefixPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DebPublishedRepo> {
        const response = await this.apiPublishPrefixPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
