/* tslint:disable */
/* eslint-disable */
/**
 * Aptly API
 * Aptly operations are also available via REST API served with `aptly api serve`.  On Debian based systems, a package `aptly-api` is available, which will run aptly as systemd service as dedicated aptly-api user.  Some configuration changes (S3 publishing endpoints, ...) will require restarting the aptly service in order to take effect.  The REST API shouldn\'t be exposed to the Internet as there is no authentication/protection, consider using a HTTP proxy (e.g. nginx) to add https and authentication.  #### Aptly REST API Documentation 
 *
 * The version of the OpenAPI document: 1.6.2+20260228114657.9defe70
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiError,
  ApiRepoCreateParams,
  ApiReposEditParams,
  ApiReposIncludePackageFromDirResponse,
  ApiReposPackagesAddDeleteParams,
  DebLocalRepo,
  TaskProcessReturnValue,
} from '../models/index';
import {
    ApiErrorFromJSON,
    ApiErrorToJSON,
    ApiRepoCreateParamsFromJSON,
    ApiRepoCreateParamsToJSON,
    ApiReposEditParamsFromJSON,
    ApiReposEditParamsToJSON,
    ApiReposIncludePackageFromDirResponseFromJSON,
    ApiReposIncludePackageFromDirResponseToJSON,
    ApiReposPackagesAddDeleteParamsFromJSON,
    ApiReposPackagesAddDeleteParamsToJSON,
    DebLocalRepoFromJSON,
    DebLocalRepoToJSON,
    TaskProcessReturnValueFromJSON,
    TaskProcessReturnValueToJSON,
} from '../models/index';

export interface ApiReposNameCopySrcFilePostRequest {
    name: string;
    src: string;
    file: string;
    async?: boolean;
}

export interface ApiReposNameDeleteRequest {
    name: string;
    async?: boolean;
    force?: number;
}

export interface ApiReposNameFileDirFilePostRequest {
    name: string;
    dir: string;
    file: string;
    async?: boolean;
}

export interface ApiReposNameFileDirPostRequest {
    name: string;
    dir: string;
    noRemove?: string;
    forceReplace?: string;
    async?: boolean;
}

export interface ApiReposNameGetRequest {
    name: string;
}

export interface ApiReposNameIncludeDirFilePostRequest {
    name: string;
    dir: string;
    file: string;
    forceReplace?: number;
    noRemoveFiles?: number;
    acceptUnsigned?: number;
    ignoreSignature?: number;
    async?: boolean;
}

export interface ApiReposNameIncludeDirPostRequest {
    name: string;
    dir: string;
    forceReplace?: number;
    noRemoveFiles?: number;
    acceptUnsigned?: number;
    ignoreSignature?: number;
    async?: boolean;
}

export interface ApiReposNamePackagesDeleteRequest {
    name: string;
    request: ApiReposPackagesAddDeleteParams;
    async?: boolean;
}

export interface ApiReposNamePackagesGetRequest {
    name: string;
    q: string;
    withDeps: string;
    format: string;
    maximumVersion: string;
}

export interface ApiReposNamePackagesPostRequest {
    name: string;
    request: ApiReposPackagesAddDeleteParams;
    async?: boolean;
}

export interface ApiReposNamePutRequest {
    name: string;
    request: ApiReposEditParams;
}

export interface ApiReposPostRequest {
    request: ApiRepoCreateParams;
}

export interface ApiStoragePkgPathGetRequest {
    storage: string;
    pkgPath: string;
}

/**
 * 
 */
export class ReposApi extends runtime.BaseAPI {

    /**
     * Creates request options for apiReposGet without sending the request
     */
    async apiReposGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/repos`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * **Get list of available repos** Each repo is returned as in “show” API.
     * List Repositories
     */
    async apiReposGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<DebLocalRepo>>> {
        const requestOptions = await this.apiReposGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DebLocalRepoFromJSON));
    }

    /**
     * **Get list of available repos** Each repo is returned as in “show” API.
     * List Repositories
     */
    async apiReposGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<DebLocalRepo>> {
        const response = await this.apiReposGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiReposNameCopySrcFilePost without sending the request
     */
    async apiReposNameCopySrcFilePostRequestOpts(requestParameters: ApiReposNameCopySrcFilePostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling apiReposNameCopySrcFilePost().'
            );
        }

        if (requestParameters['src'] == null) {
            throw new runtime.RequiredError(
                'src',
                'Required parameter "src" was null or undefined when calling apiReposNameCopySrcFilePost().'
            );
        }

        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling apiReposNameCopySrcFilePost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['async'] != null) {
            queryParameters['_async'] = requestParameters['async'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/repos/{name}/copy/{src}/{file}`;
        urlPath = urlPath.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name'])));
        urlPath = urlPath.replace(`{${"src"}}`, encodeURIComponent(String(requestParameters['src'])));
        urlPath = urlPath.replace(`{${"file"}}`, encodeURIComponent(String(requestParameters['file'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Copies a package from a source to destination repository
     * Copy Package
     */
    async apiReposNameCopySrcFilePostRaw(requestParameters: ApiReposNameCopySrcFilePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskProcessReturnValue>> {
        const requestOptions = await this.apiReposNameCopySrcFilePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskProcessReturnValueFromJSON(jsonValue));
    }

    /**
     * Copies a package from a source to destination repository
     * Copy Package
     */
    async apiReposNameCopySrcFilePost(requestParameters: ApiReposNameCopySrcFilePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskProcessReturnValue> {
        const response = await this.apiReposNameCopySrcFilePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiReposNameDelete without sending the request
     */
    async apiReposNameDeleteRequestOpts(requestParameters: ApiReposNameDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling apiReposNameDelete().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['async'] != null) {
            queryParameters['_async'] = requestParameters['async'];
        }

        if (requestParameters['force'] != null) {
            queryParameters['force'] = requestParameters['force'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/repos/{name}`;
        urlPath = urlPath.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Drop/delete a repo Cannot drop repos that are published. Needs force=1 to drop repos used as source by other repos.
     * Delete Repository
     */
    async apiReposNameDeleteRaw(requestParameters: ApiReposNameDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskProcessReturnValue>> {
        const requestOptions = await this.apiReposNameDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskProcessReturnValueFromJSON(jsonValue));
    }

    /**
     * Drop/delete a repo Cannot drop repos that are published. Needs force=1 to drop repos used as source by other repos.
     * Delete Repository
     */
    async apiReposNameDelete(requestParameters: ApiReposNameDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskProcessReturnValue> {
        const response = await this.apiReposNameDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiReposNameFileDirFilePost without sending the request
     */
    async apiReposNameFileDirFilePostRequestOpts(requestParameters: ApiReposNameFileDirFilePostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling apiReposNameFileDirFilePost().'
            );
        }

        if (requestParameters['dir'] == null) {
            throw new runtime.RequiredError(
                'dir',
                'Required parameter "dir" was null or undefined when calling apiReposNameFileDirFilePost().'
            );
        }

        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling apiReposNameFileDirFilePost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['async'] != null) {
            queryParameters['_async'] = requestParameters['async'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/repos/{name}/file/{dir}/{file}`;
        urlPath = urlPath.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name'])));
        urlPath = urlPath.replace(`{${"dir"}}`, encodeURIComponent(String(requestParameters['dir'])));
        urlPath = urlPath.replace(`{${"file"}}`, encodeURIComponent(String(requestParameters['file'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Import packages from files (uploaded using File Upload API) to the local repository. If directory specified, aptly would discover package files automatically. Adding same package to local repository is not an error. By default aptly would try to remove every successfully processed file and directory `dir` (if it becomes empty after import).
     * Add Uploaded File
     */
    async apiReposNameFileDirFilePostRaw(requestParameters: ApiReposNameFileDirFilePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.apiReposNameFileDirFilePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Import packages from files (uploaded using File Upload API) to the local repository. If directory specified, aptly would discover package files automatically. Adding same package to local repository is not an error. By default aptly would try to remove every successfully processed file and directory `dir` (if it becomes empty after import).
     * Add Uploaded File
     */
    async apiReposNameFileDirFilePost(requestParameters: ApiReposNameFileDirFilePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.apiReposNameFileDirFilePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiReposNameFileDirPost without sending the request
     */
    async apiReposNameFileDirPostRequestOpts(requestParameters: ApiReposNameFileDirPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling apiReposNameFileDirPost().'
            );
        }

        if (requestParameters['dir'] == null) {
            throw new runtime.RequiredError(
                'dir',
                'Required parameter "dir" was null or undefined when calling apiReposNameFileDirPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['noRemove'] != null) {
            queryParameters['noRemove'] = requestParameters['noRemove'];
        }

        if (requestParameters['forceReplace'] != null) {
            queryParameters['forceReplace'] = requestParameters['forceReplace'];
        }

        if (requestParameters['async'] != null) {
            queryParameters['_async'] = requestParameters['async'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/repos/{name}/file/{dir}`;
        urlPath = urlPath.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name'])));
        urlPath = urlPath.replace(`{${"dir"}}`, encodeURIComponent(String(requestParameters['dir'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Import packages from files (uploaded using File Upload API) to the local repository. If directory specified, aptly would discover package files automatically. Adding same package to local repository is not an error. By default aptly would try to remove every successfully processed file and directory `dir` (if it becomes empty after import).
     * Add Uploaded Directory
     */
    async apiReposNameFileDirPostRaw(requestParameters: ApiReposNameFileDirPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.apiReposNameFileDirPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Import packages from files (uploaded using File Upload API) to the local repository. If directory specified, aptly would discover package files automatically. Adding same package to local repository is not an error. By default aptly would try to remove every successfully processed file and directory `dir` (if it becomes empty after import).
     * Add Uploaded Directory
     */
    async apiReposNameFileDirPost(requestParameters: ApiReposNameFileDirPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.apiReposNameFileDirPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiReposNameGet without sending the request
     */
    async apiReposNameGetRequestOpts(requestParameters: ApiReposNameGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling apiReposNameGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/repos/{name}`;
        urlPath = urlPath.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns basic information about local repository.
     * Get Repository Info
     */
    async apiReposNameGetRaw(requestParameters: ApiReposNameGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DebLocalRepo>> {
        const requestOptions = await this.apiReposNameGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DebLocalRepoFromJSON(jsonValue));
    }

    /**
     * Returns basic information about local repository.
     * Get Repository Info
     */
    async apiReposNameGet(requestParameters: ApiReposNameGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DebLocalRepo> {
        const response = await this.apiReposNameGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiReposNameIncludeDirFilePost without sending the request
     */
    async apiReposNameIncludeDirFilePostRequestOpts(requestParameters: ApiReposNameIncludeDirFilePostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling apiReposNameIncludeDirFilePost().'
            );
        }

        if (requestParameters['dir'] == null) {
            throw new runtime.RequiredError(
                'dir',
                'Required parameter "dir" was null or undefined when calling apiReposNameIncludeDirFilePost().'
            );
        }

        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling apiReposNameIncludeDirFilePost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['forceReplace'] != null) {
            queryParameters['forceReplace'] = requestParameters['forceReplace'];
        }

        if (requestParameters['noRemoveFiles'] != null) {
            queryParameters['noRemoveFiles'] = requestParameters['noRemoveFiles'];
        }

        if (requestParameters['acceptUnsigned'] != null) {
            queryParameters['acceptUnsigned'] = requestParameters['acceptUnsigned'];
        }

        if (requestParameters['ignoreSignature'] != null) {
            queryParameters['ignoreSignature'] = requestParameters['ignoreSignature'];
        }

        if (requestParameters['async'] != null) {
            queryParameters['_async'] = requestParameters['async'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/repos/{name}/include/{dir}/{file}`;
        urlPath = urlPath.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name'])));
        urlPath = urlPath.replace(`{${"dir"}}`, encodeURIComponent(String(requestParameters['dir'])));
        urlPath = urlPath.replace(`{${"file"}}`, encodeURIComponent(String(requestParameters['file'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Allows automatic processing of .changes file controlling package upload (uploaded using File Upload API) to the local repository. i.e. Exposes repo include command in api.
     * Include File from Directory
     */
    async apiReposNameIncludeDirFilePostRaw(requestParameters: ApiReposNameIncludeDirFilePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.apiReposNameIncludeDirFilePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Allows automatic processing of .changes file controlling package upload (uploaded using File Upload API) to the local repository. i.e. Exposes repo include command in api.
     * Include File from Directory
     */
    async apiReposNameIncludeDirFilePost(requestParameters: ApiReposNameIncludeDirFilePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.apiReposNameIncludeDirFilePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiReposNameIncludeDirPost without sending the request
     */
    async apiReposNameIncludeDirPostRequestOpts(requestParameters: ApiReposNameIncludeDirPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling apiReposNameIncludeDirPost().'
            );
        }

        if (requestParameters['dir'] == null) {
            throw new runtime.RequiredError(
                'dir',
                'Required parameter "dir" was null or undefined when calling apiReposNameIncludeDirPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['forceReplace'] != null) {
            queryParameters['forceReplace'] = requestParameters['forceReplace'];
        }

        if (requestParameters['noRemoveFiles'] != null) {
            queryParameters['noRemoveFiles'] = requestParameters['noRemoveFiles'];
        }

        if (requestParameters['acceptUnsigned'] != null) {
            queryParameters['acceptUnsigned'] = requestParameters['acceptUnsigned'];
        }

        if (requestParameters['ignoreSignature'] != null) {
            queryParameters['ignoreSignature'] = requestParameters['ignoreSignature'];
        }

        if (requestParameters['async'] != null) {
            queryParameters['_async'] = requestParameters['async'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/repos/{name}/include/{dir}`;
        urlPath = urlPath.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name'])));
        urlPath = urlPath.replace(`{${"dir"}}`, encodeURIComponent(String(requestParameters['dir'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Allows automatic processing of .changes file controlling package upload (uploaded using File Upload API) to the local repository. i.e. Exposes repo include command in api.
     * Include Directory
     */
    async apiReposNameIncludeDirPostRaw(requestParameters: ApiReposNameIncludeDirPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiReposIncludePackageFromDirResponse>> {
        const requestOptions = await this.apiReposNameIncludeDirPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiReposIncludePackageFromDirResponseFromJSON(jsonValue));
    }

    /**
     * Allows automatic processing of .changes file controlling package upload (uploaded using File Upload API) to the local repository. i.e. Exposes repo include command in api.
     * Include Directory
     */
    async apiReposNameIncludeDirPost(requestParameters: ApiReposNameIncludeDirPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiReposIncludePackageFromDirResponse> {
        const response = await this.apiReposNameIncludeDirPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiReposNamePackagesDelete without sending the request
     */
    async apiReposNamePackagesDeleteRequestOpts(requestParameters: ApiReposNamePackagesDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling apiReposNamePackagesDelete().'
            );
        }

        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling apiReposNamePackagesDelete().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['async'] != null) {
            queryParameters['_async'] = requestParameters['async'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/repos/{name}/packages`;
        urlPath = urlPath.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: ApiReposPackagesAddDeleteParamsToJSON(requestParameters['request']),
        };
    }

    /**
     * **Remove packages from local repository by package keys.**  Any package(s) can be removed from a local repository. Package references from a local repository can be retrieved with GET /api/repos/:name/packages.
     * Delete Packages by Key
     */
    async apiReposNamePackagesDeleteRaw(requestParameters: ApiReposNamePackagesDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.apiReposNamePackagesDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * **Remove packages from local repository by package keys.**  Any package(s) can be removed from a local repository. Package references from a local repository can be retrieved with GET /api/repos/:name/packages.
     * Delete Packages by Key
     */
    async apiReposNamePackagesDelete(requestParameters: ApiReposNamePackagesDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.apiReposNamePackagesDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiReposNamePackagesGet without sending the request
     */
    async apiReposNamePackagesGetRequestOpts(requestParameters: ApiReposNamePackagesGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling apiReposNamePackagesGet().'
            );
        }

        if (requestParameters['q'] == null) {
            throw new runtime.RequiredError(
                'q',
                'Required parameter "q" was null or undefined when calling apiReposNamePackagesGet().'
            );
        }

        if (requestParameters['withDeps'] == null) {
            throw new runtime.RequiredError(
                'withDeps',
                'Required parameter "withDeps" was null or undefined when calling apiReposNamePackagesGet().'
            );
        }

        if (requestParameters['format'] == null) {
            throw new runtime.RequiredError(
                'format',
                'Required parameter "format" was null or undefined when calling apiReposNamePackagesGet().'
            );
        }

        if (requestParameters['maximumVersion'] == null) {
            throw new runtime.RequiredError(
                'maximumVersion',
                'Required parameter "maximumVersion" was null or undefined when calling apiReposNamePackagesGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        if (requestParameters['withDeps'] != null) {
            queryParameters['withDeps'] = requestParameters['withDeps'];
        }

        if (requestParameters['format'] != null) {
            queryParameters['format'] = requestParameters['format'];
        }

        if (requestParameters['maximumVersion'] != null) {
            queryParameters['maximumVersion'] = requestParameters['maximumVersion'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/repos/{name}/packages`;
        urlPath = urlPath.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * **Return a list of packages present in the repo**  If `q` query parameter is missing, return all packages, otherwise return packages that match q  **Example:** ``` $ curl http://localhost:8080/api/repos/aptly-repo/packages [\"Pi386 aptly 0.8 966561016b44ed80\"] ```
     * List Repo Packages
     */
    async apiReposNamePackagesGetRaw(requestParameters: ApiReposNamePackagesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.apiReposNamePackagesGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * **Return a list of packages present in the repo**  If `q` query parameter is missing, return all packages, otherwise return packages that match q  **Example:** ``` $ curl http://localhost:8080/api/repos/aptly-repo/packages [\"Pi386 aptly 0.8 966561016b44ed80\"] ```
     * List Repo Packages
     */
    async apiReposNamePackagesGet(requestParameters: ApiReposNamePackagesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.apiReposNamePackagesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiReposNamePackagesPost without sending the request
     */
    async apiReposNamePackagesPostRequestOpts(requestParameters: ApiReposNamePackagesPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling apiReposNamePackagesPost().'
            );
        }

        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling apiReposNamePackagesPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['async'] != null) {
            queryParameters['_async'] = requestParameters['async'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/repos/{name}/packages`;
        urlPath = urlPath.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ApiReposPackagesAddDeleteParamsToJSON(requestParameters['request']),
        };
    }

    /**
     * **Add packages to local repository by package keys.**  Any package can be added that is present in the aptly database (from any mirror, snapshot, local repository). This API combined with package list (search) APIs allows one to implement importing, copying, moving packages around.  API verifies that packages actually exist in aptly database and checks constraint that conflicting packages can’t be part of the same local repository.
     * Add Packages by Key
     */
    async apiReposNamePackagesPostRaw(requestParameters: ApiReposNamePackagesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.apiReposNamePackagesPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * **Add packages to local repository by package keys.**  Any package can be added that is present in the aptly database (from any mirror, snapshot, local repository). This API combined with package list (search) APIs allows one to implement importing, copying, moving packages around.  API verifies that packages actually exist in aptly database and checks constraint that conflicting packages can’t be part of the same local repository.
     * Add Packages by Key
     */
    async apiReposNamePackagesPost(requestParameters: ApiReposNamePackagesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.apiReposNamePackagesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiReposNamePut without sending the request
     */
    async apiReposNamePutRequestOpts(requestParameters: ApiReposNamePutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling apiReposNamePut().'
            );
        }

        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling apiReposNamePut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/repos/{name}`;
        urlPath = urlPath.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ApiReposEditParamsToJSON(requestParameters['request']),
        };
    }

    /**
     * **Update local repository meta information**
     * Update Repository
     */
    async apiReposNamePutRaw(requestParameters: ApiReposNamePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DebLocalRepo>> {
        const requestOptions = await this.apiReposNamePutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DebLocalRepoFromJSON(jsonValue));
    }

    /**
     * **Update local repository meta information**
     * Update Repository
     */
    async apiReposNamePut(requestParameters: ApiReposNamePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DebLocalRepo> {
        const response = await this.apiReposNamePutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiReposPost without sending the request
     */
    async apiReposPostRequestOpts(requestParameters: ApiReposPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling apiReposPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/repos`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ApiRepoCreateParamsToJSON(requestParameters['request']),
        };
    }

    /**
     * **Create a local repository**  Distribution and component are used as defaults when publishing repo either directly or via snapshot.  ``` $ curl -X POST -H \'Content-Type: application/json\' --data \'{\"Name\": \"aptly-repo\"}\' http://localhost:8080/api/repos {\"Name\":\"aptly-repo\",\"Comment\":\"\",\"DefaultDistribution\":\"\",\"DefaultComponent\":\"\"} ```
     * Create Repository
     */
    async apiReposPostRaw(requestParameters: ApiReposPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DebLocalRepo>> {
        const requestOptions = await this.apiReposPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DebLocalRepoFromJSON(jsonValue));
    }

    /**
     * **Create a local repository**  Distribution and component are used as defaults when publishing repo either directly or via snapshot.  ``` $ curl -X POST -H \'Content-Type: application/json\' --data \'{\"Name\": \"aptly-repo\"}\' http://localhost:8080/api/repos {\"Name\":\"aptly-repo\",\"Comment\":\"\",\"DefaultDistribution\":\"\",\"DefaultComponent\":\"\"} ```
     * Create Repository
     */
    async apiReposPost(requestParameters: ApiReposPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DebLocalRepo> {
        const response = await this.apiReposPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiStoragePkgPathGet without sending the request
     */
    async apiStoragePkgPathGetRequestOpts(requestParameters: ApiStoragePkgPathGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['storage'] == null) {
            throw new runtime.RequiredError(
                'storage',
                'Required parameter "storage" was null or undefined when calling apiStoragePkgPathGet().'
            );
        }

        if (requestParameters['pkgPath'] == null) {
            throw new runtime.RequiredError(
                'pkgPath',
                'Required parameter "pkgPath" was null or undefined when calling apiStoragePkgPathGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/{storage}/{pkgPath}`;
        urlPath = urlPath.replace(`{${"storage"}}`, encodeURIComponent(String(requestParameters['storage'])));
        urlPath = urlPath.replace(`{${"pkgPath"}}`, encodeURIComponent(String(requestParameters['pkgPath'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * If ServeInAPIMode is enabled in aptly config, this api serves a specified package from storage
     * Serve Packages
     */
    async apiStoragePkgPathGetRaw(requestParameters: ApiStoragePkgPathGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.apiStoragePkgPathGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * If ServeInAPIMode is enabled in aptly config, this api serves a specified package from storage
     * Serve Packages
     */
    async apiStoragePkgPathGet(requestParameters: ApiStoragePkgPathGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiStoragePkgPathGetRaw(requestParameters, initOverrides);
    }

}
