/* tslint:disable */
/* eslint-disable */
/**
 * Aptly API
 * Aptly operations are also available via REST API served with `aptly api serve`.  On Debian based systems, a package `aptly-api` is available, which will run aptly as systemd service as dedicated aptly-api user.  Some configuration changes (S3 publishing endpoints, ...) will require restarting the aptly service in order to take effect.  The REST API shouldn\'t be exposed to the Internet as there is no authentication/protection, consider using a HTTP proxy (e.g. nginx) to add https and authentication.  #### Aptly REST API Documentation 
 *
 * The version of the OpenAPI document: 1.6.2+20260308145521.8e943a3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiAptlyStatus,
  ApiAptlyVersion,
  ApiDiskFree,
  ApiError,
} from '../models/index';
import {
    ApiAptlyStatusFromJSON,
    ApiAptlyStatusToJSON,
    ApiAptlyVersionFromJSON,
    ApiAptlyVersionToJSON,
    ApiDiskFreeFromJSON,
    ApiDiskFreeToJSON,
    ApiErrorFromJSON,
    ApiErrorToJSON,
} from '../models/index';

export interface ApiGraphExtGetRequest {
    ext: string;
    layout?: string;
}

/**
 * 
 */
export class StatusApi extends runtime.BaseAPI {

    /**
     * Creates request options for apiGraphExtGet without sending the request
     */
    async apiGraphExtGetRequestOpts(requestParameters: ApiGraphExtGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['ext'] == null) {
            throw new runtime.RequiredError(
                'ext',
                'Required parameter "ext" was null or undefined when calling apiGraphExtGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['layout'] != null) {
            queryParameters['layout'] = requestParameters['layout'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/graph.{ext}`;
        urlPath = urlPath.replace(`{${"ext"}}`, encodeURIComponent(String(requestParameters['ext'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * **Generate dependency graph**  Command graph generates graph of dependencies:  * between snapshots and mirrors (what mirror was used to create each snapshot) * between snapshots and local repos (what local repo was used to create snapshot) * between snapshots (pulling, merging, etc.) * between snapshots, local repos and published repositories (how snapshots were published).  Graph is rendered to PNG file using graphviz package.  Example URL: `http://localhost:8080/api/graph.svg?layout=vertical`
     * Graph Output
     */
    async apiGraphExtGetRaw(requestParameters: ApiGraphExtGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<number>>> {
        const requestOptions = await this.apiGraphExtGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * **Generate dependency graph**  Command graph generates graph of dependencies:  * between snapshots and mirrors (what mirror was used to create each snapshot) * between snapshots and local repos (what local repo was used to create snapshot) * between snapshots (pulling, merging, etc.) * between snapshots, local repos and published repositories (how snapshots were published).  Graph is rendered to PNG file using graphviz package.  Example URL: `http://localhost:8080/api/graph.svg?layout=vertical`
     * Graph Output
     */
    async apiGraphExtGet(requestParameters: ApiGraphExtGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<number>> {
        const response = await this.apiGraphExtGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiHealthyGet without sending the request
     */
    async apiHealthyGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/healthy`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * **Get aptly health state**  Return aptly health state: - `Aptly is healthy` (HTTP 200)
     * Get Health State
     */
    async apiHealthyGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiAptlyStatus>> {
        const requestOptions = await this.apiHealthyGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiAptlyStatusFromJSON(jsonValue));
    }

    /**
     * **Get aptly health state**  Return aptly health state: - `Aptly is healthy` (HTTP 200)
     * Get Health State
     */
    async apiHealthyGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiAptlyStatus> {
        const response = await this.apiHealthyGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiReadyGet without sending the request
     */
    async apiReadyGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/ready`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * **Get aptly ready state**  Return aptly ready state: - `Aptly is ready` (HTTP 200) - `Aptly is unavailable` (HTTP 503)
     * Get Ready State
     */
    async apiReadyGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiAptlyStatus>> {
        const requestOptions = await this.apiReadyGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiAptlyStatusFromJSON(jsonValue));
    }

    /**
     * **Get aptly ready state**  Return aptly ready state: - `Aptly is ready` (HTTP 200) - `Aptly is unavailable` (HTTP 503)
     * Get Ready State
     */
    async apiReadyGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiAptlyStatus> {
        const response = await this.apiReadyGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiS3Get without sending the request
     */
    async apiS3GetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/s3`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * **Get list of S3 buckets**  List configured S3 buckets.
     * S3 buckets
     */
    async apiS3GetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>> {
        const requestOptions = await this.apiS3GetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * **Get list of S3 buckets**  List configured S3 buckets.
     * S3 buckets
     */
    async apiS3Get(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>> {
        const response = await this.apiS3GetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiStorageGet without sending the request
     */
    async apiStorageGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/storage`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * **Get disk free information of aptly storage**  Units in MiB.
     * Get Storage Utilization
     */
    async apiStorageGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiDiskFree>> {
        const requestOptions = await this.apiStorageGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiDiskFreeFromJSON(jsonValue));
    }

    /**
     * **Get disk free information of aptly storage**  Units in MiB.
     * Get Storage Utilization
     */
    async apiStorageGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiDiskFree> {
        const response = await this.apiStorageGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiVersionGet without sending the request
     */
    async apiVersionGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/version`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * **Get aptly version**  **Example:** ``` $ curl http://localhost:8080/api/version {\"Version\":\"0.9~dev\"} ```
     * Aptly Version
     */
    async apiVersionGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiAptlyVersion>> {
        const requestOptions = await this.apiVersionGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiAptlyVersionFromJSON(jsonValue));
    }

    /**
     * **Get aptly version**  **Example:** ``` $ curl http://localhost:8080/api/version {\"Version\":\"0.9~dev\"} ```
     * Aptly Version
     */
    async apiVersionGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiAptlyVersion> {
        const response = await this.apiVersionGetRaw(initOverrides);
        return await response.value();
    }

}
