/* tslint:disable */
/* eslint-disable */
/**
 * Aptly API
 * Aptly operations are also available via REST API served with `aptly api serve`.  On Debian based systems, a package `aptly-api` is available, which will run aptly as systemd service as dedicated aptly-api user.  Some configuration changes (S3 publishing endpoints, ...) will require restarting the aptly service in order to take effect.  The REST API shouldn\'t be exposed to the Internet as there is no authentication/protection, consider using a HTTP proxy (e.g. nginx) to add https and authentication.  #### Aptly REST API Documentation 
 *
 * The version of the OpenAPI document: 1.6.2+20260308145521.8e943a3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiError,
  TaskTask,
} from '../models/index';
import {
    ApiErrorFromJSON,
    ApiErrorToJSON,
    TaskTaskFromJSON,
    TaskTaskToJSON,
} from '../models/index';

export interface ApiTasksIdDeleteRequest {
    id: number;
}

export interface ApiTasksIdDetailGetRequest {
    id: number;
}

export interface ApiTasksIdGetRequest {
    id: number;
}

export interface ApiTasksIdOutputGetRequest {
    id: number;
}

export interface ApiTasksIdReturnValueGetRequest {
    id: number;
}

export interface ApiTasksIdWaitGetRequest {
    id: number;
}

/**
 * 
 */
export class TasksApi extends runtime.BaseAPI {

    /**
     * Creates request options for apiTasksClearPost without sending the request
     */
    async apiTasksClearPostRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/tasks-clear`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * **Removes finished and failed tasks from internal task list**
     * Clear Tasks
     */
    async apiTasksClearPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.apiTasksClearPostRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * **Removes finished and failed tasks from internal task list**
     * Clear Tasks
     */
    async apiTasksClearPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiTasksClearPostRaw(initOverrides);
    }

    /**
     * Creates request options for apiTasksGet without sending the request
     */
    async apiTasksGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/tasks`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * **Get list of available tasks. Each task is returned as in “show” API**
     * List Tasks
     */
    async apiTasksGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TaskTask>>> {
        const requestOptions = await this.apiTasksGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TaskTaskFromJSON));
    }

    /**
     * **Get list of available tasks. Each task is returned as in “show” API**
     * List Tasks
     */
    async apiTasksGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TaskTask>> {
        const response = await this.apiTasksGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiTasksIdDelete without sending the request
     */
    async apiTasksIdDeleteRequestOpts(requestParameters: ApiTasksIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiTasksIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/tasks/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * **Delete completed task by given ID. Does not stop task execution**
     * Delete Task
     */
    async apiTasksIdDeleteRaw(requestParameters: ApiTasksIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskTask>> {
        const requestOptions = await this.apiTasksIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskTaskFromJSON(jsonValue));
    }

    /**
     * **Delete completed task by given ID. Does not stop task execution**
     * Delete Task
     */
    async apiTasksIdDelete(requestParameters: ApiTasksIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskTask> {
        const response = await this.apiTasksIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiTasksIdDetailGet without sending the request
     */
    async apiTasksIdDetailGetRequestOpts(requestParameters: ApiTasksIdDetailGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiTasksIdDetailGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/tasks/{id}/detail`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * **Return task detail for a given ID**
     * Get Task Details
     */
    async apiTasksIdDetailGetRaw(requestParameters: ApiTasksIdDetailGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.apiTasksIdDetailGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * **Return task detail for a given ID**
     * Get Task Details
     */
    async apiTasksIdDetailGet(requestParameters: ApiTasksIdDetailGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.apiTasksIdDetailGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiTasksIdGet without sending the request
     */
    async apiTasksIdGetRequestOpts(requestParameters: ApiTasksIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiTasksIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/tasks/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * **Return task information for a given ID**
     * Get Task Info
     */
    async apiTasksIdGetRaw(requestParameters: ApiTasksIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskTask>> {
        const requestOptions = await this.apiTasksIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskTaskFromJSON(jsonValue));
    }

    /**
     * **Return task information for a given ID**
     * Get Task Info
     */
    async apiTasksIdGet(requestParameters: ApiTasksIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskTask> {
        const response = await this.apiTasksIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiTasksIdOutputGet without sending the request
     */
    async apiTasksIdOutputGetRequestOpts(requestParameters: ApiTasksIdOutputGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiTasksIdOutputGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/tasks/{id}/output`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * **Return task output for a given ID**
     * Get Task Output
     */
    async apiTasksIdOutputGetRaw(requestParameters: ApiTasksIdOutputGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.apiTasksIdOutputGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * **Return task output for a given ID**
     * Get Task Output
     */
    async apiTasksIdOutputGet(requestParameters: ApiTasksIdOutputGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.apiTasksIdOutputGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiTasksIdReturnValueGet without sending the request
     */
    async apiTasksIdReturnValueGetRequestOpts(requestParameters: ApiTasksIdReturnValueGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiTasksIdReturnValueGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/tasks/{id}/return_value`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * **Return task return value (status code) by given ID**
     * Get Task Return Value
     */
    async apiTasksIdReturnValueGetRaw(requestParameters: ApiTasksIdReturnValueGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.apiTasksIdReturnValueGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * **Return task return value (status code) by given ID**
     * Get Task Return Value
     */
    async apiTasksIdReturnValueGet(requestParameters: ApiTasksIdReturnValueGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.apiTasksIdReturnValueGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiTasksIdWaitGet without sending the request
     */
    async apiTasksIdWaitGetRequestOpts(requestParameters: ApiTasksIdWaitGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiTasksIdWaitGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/tasks/{id}/wait`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * **Waits for and returns when given Task ID is complete**
     * Wait for Task
     */
    async apiTasksIdWaitGetRaw(requestParameters: ApiTasksIdWaitGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskTask>> {
        const requestOptions = await this.apiTasksIdWaitGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskTaskFromJSON(jsonValue));
    }

    /**
     * **Waits for and returns when given Task ID is complete**
     * Wait for Task
     */
    async apiTasksIdWaitGet(requestParameters: ApiTasksIdWaitGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskTask> {
        const response = await this.apiTasksIdWaitGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiTasksWaitGet without sending the request
     */
    async apiTasksWaitGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/tasks-wait`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * **Waits for and returns when all running tasks are complete**
     * Wait for all Tasks
     */
    async apiTasksWaitGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.apiTasksWaitGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * **Waits for and returns when all running tasks are complete**
     * Wait for all Tasks
     */
    async apiTasksWaitGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiTasksWaitGetRaw(initOverrides);
    }

}
