/* tslint:disable */
/* eslint-disable */
/**
 * Aptly API
 * Aptly operations are also available via REST API served with `aptly api serve`.  On Debian based systems, a package `aptly-api` is available, which will run aptly as systemd service as dedicated aptly-api user.  Some configuration changes (S3 publishing endpoints, ...) will require restarting the aptly service in order to take effect.  The REST API shouldn\'t be exposed to the Internet as there is no authentication/protection, consider using a HTTP proxy (e.g. nginx) to add https and authentication.  #### Aptly REST API Documentation 
 *
 * The version of the OpenAPI document: 1.6.2+20260308145521.8e943a3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiAptlyStatus
 */
export interface ApiAptlyStatus {
    /**
     * Aptly Status
     * @type {string}
     * @memberof ApiAptlyStatus
     */
    status?: string;
}

/**
 * Check if a given object implements the ApiAptlyStatus interface.
 */
export function instanceOfApiAptlyStatus(value: object): value is ApiAptlyStatus {
    return true;
}

export function ApiAptlyStatusFromJSON(json: any): ApiAptlyStatus {
    return ApiAptlyStatusFromJSONTyped(json, false);
}

export function ApiAptlyStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiAptlyStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['Status'] == null ? undefined : json['Status'],
    };
}

export function ApiAptlyStatusToJSON(json: any): ApiAptlyStatus {
    return ApiAptlyStatusToJSONTyped(json, false);
}

export function ApiAptlyStatusToJSONTyped(value?: ApiAptlyStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Status': value['status'],
    };
}

