/* tslint:disable */
/* eslint-disable */
/**
 * Aptly API
 * Aptly operations are also available via REST API served with `aptly api serve`.  On Debian based systems, a package `aptly-api` is available, which will run aptly as systemd service as dedicated aptly-api user.  Some configuration changes (S3 publishing endpoints, ...) will require restarting the aptly service in order to take effect.  The REST API shouldn\'t be exposed to the Internet as there is no authentication/protection, consider using a HTTP proxy (e.g. nginx) to add https and authentication.  #### Aptly REST API Documentation 
 *
 * The version of the OpenAPI document: 1.6.2+20260315225119.eb0ae3a
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiGpgDeleteKeyParams
 */
export interface ApiGpgDeleteKeyParams {
    /**
     * Key fingerprints or IDs to delete, separated by space
     * @type {string}
     * @memberof ApiGpgDeleteKeyParams
     */
    gpgKeyID?: string;
    /**
     * Keyring to delete keys from (default: trustedkeys.gpg)
     * @type {string}
     * @memberof ApiGpgDeleteKeyParams
     */
    keyring?: string;
}

/**
 * Check if a given object implements the ApiGpgDeleteKeyParams interface.
 */
export function instanceOfApiGpgDeleteKeyParams(value: object): value is ApiGpgDeleteKeyParams {
    return true;
}

export function ApiGpgDeleteKeyParamsFromJSON(json: any): ApiGpgDeleteKeyParams {
    return ApiGpgDeleteKeyParamsFromJSONTyped(json, false);
}

export function ApiGpgDeleteKeyParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiGpgDeleteKeyParams {
    if (json == null) {
        return json;
    }
    return {
        
        'gpgKeyID': json['GpgKeyID'] == null ? undefined : json['GpgKeyID'],
        'keyring': json['Keyring'] == null ? undefined : json['Keyring'],
    };
}

export function ApiGpgDeleteKeyParamsToJSON(json: any): ApiGpgDeleteKeyParams {
    return ApiGpgDeleteKeyParamsToJSONTyped(json, false);
}

export function ApiGpgDeleteKeyParamsToJSONTyped(value?: ApiGpgDeleteKeyParams | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'GpgKeyID': value['gpgKeyID'],
        'Keyring': value['keyring'],
    };
}

