/* tslint:disable */
/* eslint-disable */
/**
 * Aptly API
 * Aptly operations are also available via REST API served with `aptly api serve`.  On Debian based systems, a package `aptly-api` is available, which will run aptly as systemd service as dedicated aptly-api user.  Some configuration changes (S3 publishing endpoints, ...) will require restarting the aptly service in order to take effect.  The REST API shouldn\'t be exposed to the Internet as there is no authentication/protection, consider using a HTTP proxy (e.g. nginx) to add https and authentication.  #### Aptly REST API Documentation 
 *
 * The version of the OpenAPI document: 1.6.2+20260315225119.eb0ae3a
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiSourceParams } from './ApiSourceParams';
import {
    ApiSourceParamsFromJSON,
    ApiSourceParamsFromJSONTyped,
    ApiSourceParamsToJSON,
    ApiSourceParamsToJSONTyped,
} from './ApiSourceParams';
import type { ApiSigningParams } from './ApiSigningParams';
import {
    ApiSigningParamsFromJSON,
    ApiSigningParamsFromJSONTyped,
    ApiSigningParamsToJSON,
    ApiSigningParamsToJSONTyped,
} from './ApiSigningParams';

/**
 * 
 * @export
 * @interface ApiPublishedRepoCreateParams
 */
export interface ApiPublishedRepoCreateParams {
    /**
     * Provide index files by hash
     * @type {boolean}
     * @memberof ApiPublishedRepoCreateParams
     */
    acquireByHash?: boolean;
    /**
     * Override list of published architectures
     * @type {Array<string>}
     * @memberof ApiPublishedRepoCreateParams
     */
    architectures?: Array<string>;
    /**
     * setting to yes excludes upgrades from the NotAutomic setting
     * @type {string}
     * @memberof ApiPublishedRepoCreateParams
     */
    butAutomaticUpgrades?: string;
    /**
     * Value of Description: field in published repository stanza
     * @type {string}
     * @memberof ApiPublishedRepoCreateParams
     */
    description?: string;
    /**
     * Distribution name, if missing Aptly would try to guess from sources
     * @type {string}
     * @memberof ApiPublishedRepoCreateParams
     */
    distribution?: string;
    /**
     * when publishing, overwrite files in pool/ directory without notice
     * @type {boolean}
     * @memberof ApiPublishedRepoCreateParams
     */
    forceOverwrite?: boolean;
    /**
     * Value of Label: field in published repository stanza
     * @type {string}
     * @memberof ApiPublishedRepoCreateParams
     */
    label?: string;
    /**
     * Enable multiple packages with the same filename in different distributions
     * @type {boolean}
     * @memberof ApiPublishedRepoCreateParams
     */
    multiDist?: boolean;
    /**
     * Setting to yes indicates to the package manager to not install or upgrade packages from the repository without user consent
     * @type {string}
     * @memberof ApiPublishedRepoCreateParams
     */
    notAutomatic?: string;
    /**
     * Value of Origin: field in published repository stanza
     * @type {string}
     * @memberof ApiPublishedRepoCreateParams
     */
    origin?: string;
    /**
     * An optional field containing a comma separated list of OpenPGP key fingerprints to be used for validating the next Release file.
     * @type {string}
     * @memberof ApiPublishedRepoCreateParams
     */
    signedBy?: string;
    /**
     * GPG options
     * @type {ApiSigningParams}
     * @memberof ApiPublishedRepoCreateParams
     */
    signing?: ApiSigningParams;
    /**
     * Skip bz2 compression for index files
     * @type {boolean}
     * @memberof ApiPublishedRepoCreateParams
     */
    skipBz2?: boolean;
    /**
     * Don't remove unreferenced files in prefix/component
     * @type {boolean}
     * @memberof ApiPublishedRepoCreateParams
     */
    skipCleanup?: boolean;
    /**
     * Don't generate contents indexes
     * @type {boolean}
     * @memberof ApiPublishedRepoCreateParams
     */
    skipContents?: boolean;
    /**
     * 'local' for local repositories and 'snapshot' for snapshots
     * @type {string}
     * @memberof ApiPublishedRepoCreateParams
     */
    sourceKind: string;
    /**
     * List of 'Component/Name' objects, 'Name' is either local repository or snapshot name
     * @type {Array<ApiSourceParams>}
     * @memberof ApiPublishedRepoCreateParams
     */
    sources: Array<ApiSourceParams>;
}

/**
 * Check if a given object implements the ApiPublishedRepoCreateParams interface.
 */
export function instanceOfApiPublishedRepoCreateParams(value: object): value is ApiPublishedRepoCreateParams {
    if (!('sourceKind' in value) || value['sourceKind'] === undefined) return false;
    if (!('sources' in value) || value['sources'] === undefined) return false;
    return true;
}

export function ApiPublishedRepoCreateParamsFromJSON(json: any): ApiPublishedRepoCreateParams {
    return ApiPublishedRepoCreateParamsFromJSONTyped(json, false);
}

export function ApiPublishedRepoCreateParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiPublishedRepoCreateParams {
    if (json == null) {
        return json;
    }
    return {
        
        'acquireByHash': json['AcquireByHash'] == null ? undefined : json['AcquireByHash'],
        'architectures': json['Architectures'] == null ? undefined : json['Architectures'],
        'butAutomaticUpgrades': json['ButAutomaticUpgrades'] == null ? undefined : json['ButAutomaticUpgrades'],
        'description': json['Description'] == null ? undefined : json['Description'],
        'distribution': json['Distribution'] == null ? undefined : json['Distribution'],
        'forceOverwrite': json['ForceOverwrite'] == null ? undefined : json['ForceOverwrite'],
        'label': json['Label'] == null ? undefined : json['Label'],
        'multiDist': json['MultiDist'] == null ? undefined : json['MultiDist'],
        'notAutomatic': json['NotAutomatic'] == null ? undefined : json['NotAutomatic'],
        'origin': json['Origin'] == null ? undefined : json['Origin'],
        'signedBy': json['SignedBy'] == null ? undefined : json['SignedBy'],
        'signing': json['Signing'] == null ? undefined : ApiSigningParamsFromJSON(json['Signing']),
        'skipBz2': json['SkipBz2'] == null ? undefined : json['SkipBz2'],
        'skipCleanup': json['SkipCleanup'] == null ? undefined : json['SkipCleanup'],
        'skipContents': json['SkipContents'] == null ? undefined : json['SkipContents'],
        'sourceKind': json['SourceKind'],
        'sources': ((json['Sources'] as Array<any>).map(ApiSourceParamsFromJSON)),
    };
}

export function ApiPublishedRepoCreateParamsToJSON(json: any): ApiPublishedRepoCreateParams {
    return ApiPublishedRepoCreateParamsToJSONTyped(json, false);
}

export function ApiPublishedRepoCreateParamsToJSONTyped(value?: ApiPublishedRepoCreateParams | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'AcquireByHash': value['acquireByHash'],
        'Architectures': value['architectures'],
        'ButAutomaticUpgrades': value['butAutomaticUpgrades'],
        'Description': value['description'],
        'Distribution': value['distribution'],
        'ForceOverwrite': value['forceOverwrite'],
        'Label': value['label'],
        'MultiDist': value['multiDist'],
        'NotAutomatic': value['notAutomatic'],
        'Origin': value['origin'],
        'SignedBy': value['signedBy'],
        'Signing': ApiSigningParamsToJSON(value['signing']),
        'SkipBz2': value['skipBz2'],
        'SkipCleanup': value['skipCleanup'],
        'SkipContents': value['skipContents'],
        'SourceKind': value['sourceKind'],
        'Sources': ((value['sources'] as Array<any>).map(ApiSourceParamsToJSON)),
    };
}

