/* tslint:disable */
/* eslint-disable */
/**
 * Aptly API
 * Aptly operations are also available via REST API served with `aptly api serve`.  On Debian based systems, a package `aptly-api` is available, which will run aptly as systemd service as dedicated aptly-api user.  Some configuration changes (S3 publishing endpoints, ...) will require restarting the aptly service in order to take effect.  The REST API shouldn\'t be exposed to the Internet as there is no authentication/protection, consider using a HTTP proxy (e.g. nginx) to add https and authentication.  #### Aptly REST API Documentation 
 *
 * The version of the OpenAPI document: 1.6.2+20260228114657.9defe70
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiSigningParams } from './ApiSigningParams';
import {
    ApiSigningParamsFromJSON,
    ApiSigningParamsFromJSONTyped,
    ApiSigningParamsToJSON,
    ApiSigningParamsToJSONTyped,
} from './ApiSigningParams';

/**
 * 
 * @export
 * @interface ApiPublishedRepoUpdateParams
 */
export interface ApiPublishedRepoUpdateParams {
    /**
     * Provide index files by hash
     * @type {boolean}
     * @memberof ApiPublishedRepoUpdateParams
     */
    acquireByHash?: boolean;
    /**
     * when publishing, overwrite files in pool/ directory without notice
     * @type {boolean}
     * @memberof ApiPublishedRepoUpdateParams
     */
    forceOverwrite?: boolean;
    /**
     * Value of Label: field in published repository stanza
     * @type {string}
     * @memberof ApiPublishedRepoUpdateParams
     */
    label?: string;
    /**
     * Enable multiple packages with the same filename in different distributions
     * @type {boolean}
     * @memberof ApiPublishedRepoUpdateParams
     */
    multiDist?: boolean;
    /**
     * Value of Origin: field in published repository stanza
     * @type {string}
     * @memberof ApiPublishedRepoUpdateParams
     */
    origin?: string;
    /**
     * An optional field containing a comma separated list of OpenPGP key fingerprints to be used for validating the next Release file
     * @type {string}
     * @memberof ApiPublishedRepoUpdateParams
     */
    signedBy?: string;
    /**
     * GPG options
     * @type {ApiSigningParams}
     * @memberof ApiPublishedRepoUpdateParams
     */
    signing?: ApiSigningParams;
    /**
     * Skip bz2 compression for index files
     * @type {boolean}
     * @memberof ApiPublishedRepoUpdateParams
     */
    skipBz2?: boolean;
    /**
     * Don't remove unreferenced files in prefix/component
     * @type {boolean}
     * @memberof ApiPublishedRepoUpdateParams
     */
    skipCleanup?: boolean;
    /**
     * Don't generate contents indexes
     * @type {boolean}
     * @memberof ApiPublishedRepoUpdateParams
     */
    skipContents?: boolean;
}

/**
 * Check if a given object implements the ApiPublishedRepoUpdateParams interface.
 */
export function instanceOfApiPublishedRepoUpdateParams(value: object): value is ApiPublishedRepoUpdateParams {
    return true;
}

export function ApiPublishedRepoUpdateParamsFromJSON(json: any): ApiPublishedRepoUpdateParams {
    return ApiPublishedRepoUpdateParamsFromJSONTyped(json, false);
}

export function ApiPublishedRepoUpdateParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiPublishedRepoUpdateParams {
    if (json == null) {
        return json;
    }
    return {
        
        'acquireByHash': json['AcquireByHash'] == null ? undefined : json['AcquireByHash'],
        'forceOverwrite': json['ForceOverwrite'] == null ? undefined : json['ForceOverwrite'],
        'label': json['Label'] == null ? undefined : json['Label'],
        'multiDist': json['MultiDist'] == null ? undefined : json['MultiDist'],
        'origin': json['Origin'] == null ? undefined : json['Origin'],
        'signedBy': json['SignedBy'] == null ? undefined : json['SignedBy'],
        'signing': json['Signing'] == null ? undefined : ApiSigningParamsFromJSON(json['Signing']),
        'skipBz2': json['SkipBz2'] == null ? undefined : json['SkipBz2'],
        'skipCleanup': json['SkipCleanup'] == null ? undefined : json['SkipCleanup'],
        'skipContents': json['SkipContents'] == null ? undefined : json['SkipContents'],
    };
}

export function ApiPublishedRepoUpdateParamsToJSON(json: any): ApiPublishedRepoUpdateParams {
    return ApiPublishedRepoUpdateParamsToJSONTyped(json, false);
}

export function ApiPublishedRepoUpdateParamsToJSONTyped(value?: ApiPublishedRepoUpdateParams | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'AcquireByHash': value['acquireByHash'],
        'ForceOverwrite': value['forceOverwrite'],
        'Label': value['label'],
        'MultiDist': value['multiDist'],
        'Origin': value['origin'],
        'SignedBy': value['signedBy'],
        'Signing': ApiSigningParamsToJSON(value['signing']),
        'SkipBz2': value['skipBz2'],
        'SkipCleanup': value['skipCleanup'],
        'SkipContents': value['skipContents'],
    };
}

