/* tslint:disable */
/* eslint-disable */
/**
 * Aptly API
 * Aptly operations are also available via REST API served with `aptly api serve`.  On Debian based systems, a package `aptly-api` is available, which will run aptly as systemd service as dedicated aptly-api user.  Some configuration changes (S3 publishing endpoints, ...) will require restarting the aptly service in order to take effect.  The REST API shouldn\'t be exposed to the Internet as there is no authentication/protection, consider using a HTTP proxy (e.g. nginx) to add https and authentication.  #### Aptly REST API Documentation 
 *
 * The version of the OpenAPI document: 1.6.2+20260308145521.8e943a3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiRepoCreateParams
 */
export interface ApiRepoCreateParams {
    /**
     * Text describing the repository (optional)
     * @type {string}
     * @memberof ApiRepoCreateParams
     */
    comment?: string;
    /**
     * Default component when publishing from this local repo
     * @type {string}
     * @memberof ApiRepoCreateParams
     */
    defaultComponent?: string;
    /**
     * Default distribution when publishing from this local repo
     * @type {string}
     * @memberof ApiRepoCreateParams
     */
    defaultDistribution?: string;
    /**
     * Snapshot name to create repoitory from (optional)
     * @type {string}
     * @memberof ApiRepoCreateParams
     */
    fromSnapshot?: string;
    /**
     * Name of repository to create
     * @type {string}
     * @memberof ApiRepoCreateParams
     */
    name: string;
}

/**
 * Check if a given object implements the ApiRepoCreateParams interface.
 */
export function instanceOfApiRepoCreateParams(value: object): value is ApiRepoCreateParams {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function ApiRepoCreateParamsFromJSON(json: any): ApiRepoCreateParams {
    return ApiRepoCreateParamsFromJSONTyped(json, false);
}

export function ApiRepoCreateParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiRepoCreateParams {
    if (json == null) {
        return json;
    }
    return {
        
        'comment': json['Comment'] == null ? undefined : json['Comment'],
        'defaultComponent': json['DefaultComponent'] == null ? undefined : json['DefaultComponent'],
        'defaultDistribution': json['DefaultDistribution'] == null ? undefined : json['DefaultDistribution'],
        'fromSnapshot': json['FromSnapshot'] == null ? undefined : json['FromSnapshot'],
        'name': json['Name'],
    };
}

export function ApiRepoCreateParamsToJSON(json: any): ApiRepoCreateParams {
    return ApiRepoCreateParamsToJSONTyped(json, false);
}

export function ApiRepoCreateParamsToJSONTyped(value?: ApiRepoCreateParams | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Comment': value['comment'],
        'DefaultComponent': value['defaultComponent'],
        'DefaultDistribution': value['defaultDistribution'],
        'FromSnapshot': value['fromSnapshot'],
        'Name': value['name'],
    };
}

