/* tslint:disable */
/* eslint-disable */
/**
 * Aptly API
 * Aptly operations are also available via REST API served with `aptly api serve`.  On Debian based systems, a package `aptly-api` is available, which will run aptly as systemd service as dedicated aptly-api user.  Some configuration changes (S3 publishing endpoints, ...) will require restarting the aptly service in order to take effect.  The REST API shouldn\'t be exposed to the Internet as there is no authentication/protection, consider using a HTTP proxy (e.g. nginx) to add https and authentication.  #### Aptly REST API Documentation 
 *
 * The version of the OpenAPI document: 1.6.2+20260308145521.8e943a3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiReposPackagesAddDeleteParams
 */
export interface ApiReposPackagesAddDeleteParams {
    /**
     * Package Refs
     * @type {Array<string>}
     * @memberof ApiReposPackagesAddDeleteParams
     */
    packageRefs: Array<string>;
}

/**
 * Check if a given object implements the ApiReposPackagesAddDeleteParams interface.
 */
export function instanceOfApiReposPackagesAddDeleteParams(value: object): value is ApiReposPackagesAddDeleteParams {
    if (!('packageRefs' in value) || value['packageRefs'] === undefined) return false;
    return true;
}

export function ApiReposPackagesAddDeleteParamsFromJSON(json: any): ApiReposPackagesAddDeleteParams {
    return ApiReposPackagesAddDeleteParamsFromJSONTyped(json, false);
}

export function ApiReposPackagesAddDeleteParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiReposPackagesAddDeleteParams {
    if (json == null) {
        return json;
    }
    return {
        
        'packageRefs': json['PackageRefs'],
    };
}

export function ApiReposPackagesAddDeleteParamsToJSON(json: any): ApiReposPackagesAddDeleteParams {
    return ApiReposPackagesAddDeleteParamsToJSONTyped(json, false);
}

export function ApiReposPackagesAddDeleteParamsToJSONTyped(value?: ApiReposPackagesAddDeleteParams | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'PackageRefs': value['packageRefs'],
    };
}

