/* tslint:disable */
/* eslint-disable */
/**
 * Aptly API
 * Aptly operations are also available via REST API served with `aptly api serve`.  On Debian based systems, a package `aptly-api` is available, which will run aptly as systemd service as dedicated aptly-api user.  Some configuration changes (S3 publishing endpoints, ...) will require restarting the aptly service in order to take effect.  The REST API shouldn\'t be exposed to the Internet as there is no authentication/protection, consider using a HTTP proxy (e.g. nginx) to add https and authentication.  #### Aptly REST API Documentation 
 *
 * The version of the OpenAPI document: 1.6.2+20260315225119.eb0ae3a
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiSnapshotsCreateParams
 */
export interface ApiSnapshotsCreateParams {
    /**
     * Description of snapshot
     * @type {string}
     * @memberof ApiSnapshotsCreateParams
     */
    description?: string;
    /**
     * Name of snapshot to create
     * @type {string}
     * @memberof ApiSnapshotsCreateParams
     */
    name: string;
    /**
     * List of package refs
     * @type {Array<string>}
     * @memberof ApiSnapshotsCreateParams
     */
    packageRefs?: Array<string>;
    /**
     * List of source snapshots
     * @type {Array<string>}
     * @memberof ApiSnapshotsCreateParams
     */
    sourceSnapshots?: Array<string>;
}

/**
 * Check if a given object implements the ApiSnapshotsCreateParams interface.
 */
export function instanceOfApiSnapshotsCreateParams(value: object): value is ApiSnapshotsCreateParams {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function ApiSnapshotsCreateParamsFromJSON(json: any): ApiSnapshotsCreateParams {
    return ApiSnapshotsCreateParamsFromJSONTyped(json, false);
}

export function ApiSnapshotsCreateParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiSnapshotsCreateParams {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['Description'] == null ? undefined : json['Description'],
        'name': json['Name'],
        'packageRefs': json['PackageRefs'] == null ? undefined : json['PackageRefs'],
        'sourceSnapshots': json['SourceSnapshots'] == null ? undefined : json['SourceSnapshots'],
    };
}

export function ApiSnapshotsCreateParamsToJSON(json: any): ApiSnapshotsCreateParams {
    return ApiSnapshotsCreateParamsToJSONTyped(json, false);
}

export function ApiSnapshotsCreateParamsToJSONTyped(value?: ApiSnapshotsCreateParams | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Description': value['description'],
        'Name': value['name'],
        'PackageRefs': value['packageRefs'],
        'SourceSnapshots': value['sourceSnapshots'],
    };
}

