/* tslint:disable */
/* eslint-disable */
/**
 * Aptly API
 * Aptly operations are also available via REST API served with `aptly api serve`.  On Debian based systems, a package `aptly-api` is available, which will run aptly as systemd service as dedicated aptly-api user.  Some configuration changes (S3 publishing endpoints, ...) will require restarting the aptly service in order to take effect.  The REST API shouldn\'t be exposed to the Internet as there is no authentication/protection, consider using a HTTP proxy (e.g. nginx) to add https and authentication.  #### Aptly REST API Documentation 
 *
 * The version of the OpenAPI document: 1.6.2+20260315225119.eb0ae3a
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiSnapshotsCreateFromMirrorParams
 */
export interface ApiSnapshotsCreateFromMirrorParams {
    /**
     * Description of snapshot
     * @type {string}
     * @memberof ApiSnapshotsCreateFromMirrorParams
     */
    description?: string;
    /**
     * Name of snapshot to create
     * @type {string}
     * @memberof ApiSnapshotsCreateFromMirrorParams
     */
    name: string;
}

/**
 * Check if a given object implements the ApiSnapshotsCreateFromMirrorParams interface.
 */
export function instanceOfApiSnapshotsCreateFromMirrorParams(value: object): value is ApiSnapshotsCreateFromMirrorParams {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function ApiSnapshotsCreateFromMirrorParamsFromJSON(json: any): ApiSnapshotsCreateFromMirrorParams {
    return ApiSnapshotsCreateFromMirrorParamsFromJSONTyped(json, false);
}

export function ApiSnapshotsCreateFromMirrorParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiSnapshotsCreateFromMirrorParams {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['Description'] == null ? undefined : json['Description'],
        'name': json['Name'],
    };
}

export function ApiSnapshotsCreateFromMirrorParamsToJSON(json: any): ApiSnapshotsCreateFromMirrorParams {
    return ApiSnapshotsCreateFromMirrorParamsToJSONTyped(json, false);
}

export function ApiSnapshotsCreateFromMirrorParamsToJSONTyped(value?: ApiSnapshotsCreateFromMirrorParams | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Description': value['description'],
        'Name': value['name'],
    };
}

