/* tslint:disable */
/* eslint-disable */
/**
 * Aptly API
 * Aptly operations are also available via REST API served with `aptly api serve`.  On Debian based systems, a package `aptly-api` is available, which will run aptly as systemd service as dedicated aptly-api user.  Some configuration changes (S3 publishing endpoints, ...) will require restarting the aptly service in order to take effect.  The REST API shouldn\'t be exposed to the Internet as there is no authentication/protection, consider using a HTTP proxy (e.g. nginx) to add https and authentication.  #### Aptly REST API Documentation 
 *
 * The version of the OpenAPI document: 1.6.2+20260315225119.eb0ae3a
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiSigningParams
 */
export interface ApiSigningParams {
    /**
     * GPG key ID(s) to use when signing the release, separated by comma, and if not specified, default configured key(s) are used
     * @type {string}
     * @memberof ApiSigningParams
     */
    gpgKey?: string;
    /**
     * GPG keyring to use (instead of default)
     * @type {string}
     * @memberof ApiSigningParams
     */
    keyring?: string;
    /**
     * GPG passphrase to unlock private key (possibly insecure)
     * @type {string}
     * @memberof ApiSigningParams
     */
    passphrase?: string;
    /**
     * GPG passphrase file to unlock private key (possibly insecure)
     * @type {string}
     * @memberof ApiSigningParams
     */
    passphraseFile?: string;
    /**
     * GPG secret keyring to use (instead of default) Note: depreciated with gpg2
     * @type {string}
     * @memberof ApiSigningParams
     */
    secretKeyring?: string;
    /**
     * Don't sign published repository
     * @type {boolean}
     * @memberof ApiSigningParams
     */
    skip?: boolean;
}

/**
 * Check if a given object implements the ApiSigningParams interface.
 */
export function instanceOfApiSigningParams(value: object): value is ApiSigningParams {
    return true;
}

export function ApiSigningParamsFromJSON(json: any): ApiSigningParams {
    return ApiSigningParamsFromJSONTyped(json, false);
}

export function ApiSigningParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiSigningParams {
    if (json == null) {
        return json;
    }
    return {
        
        'gpgKey': json['GpgKey'] == null ? undefined : json['GpgKey'],
        'keyring': json['Keyring'] == null ? undefined : json['Keyring'],
        'passphrase': json['Passphrase'] == null ? undefined : json['Passphrase'],
        'passphraseFile': json['PassphraseFile'] == null ? undefined : json['PassphraseFile'],
        'secretKeyring': json['SecretKeyring'] == null ? undefined : json['SecretKeyring'],
        'skip': json['Skip'] == null ? undefined : json['Skip'],
    };
}

export function ApiSigningParamsToJSON(json: any): ApiSigningParams {
    return ApiSigningParamsToJSONTyped(json, false);
}

export function ApiSigningParamsToJSONTyped(value?: ApiSigningParams | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'GpgKey': value['gpgKey'],
        'Keyring': value['keyring'],
        'Passphrase': value['passphrase'],
        'PassphraseFile': value['passphraseFile'],
        'SecretKeyring': value['secretKeyring'],
        'Skip': value['skip'],
    };
}

