/* tslint:disable */
/* eslint-disable */
/**
 * Aptly API
 * Aptly operations are also available via REST API served with `aptly api serve`.  On Debian based systems, a package `aptly-api` is available, which will run aptly as systemd service as dedicated aptly-api user.  Some configuration changes (S3 publishing endpoints, ...) will require restarting the aptly service in order to take effect.  The REST API shouldn\'t be exposed to the Internet as there is no authentication/protection, consider using a HTTP proxy (e.g. nginx) to add https and authentication.  #### Aptly REST API Documentation 
 *
 * The version of the OpenAPI document: 1.6.2+20260316002414.a40994d
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AptlyRecordingResultReporter
 */
export interface AptlyRecordingResultReporter {
    /**
     * 
     * @type {Array<string>}
     * @memberof AptlyRecordingResultReporter
     */
    added?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof AptlyRecordingResultReporter
     */
    removed?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof AptlyRecordingResultReporter
     */
    warnings?: Array<string>;
}

/**
 * Check if a given object implements the AptlyRecordingResultReporter interface.
 */
export function instanceOfAptlyRecordingResultReporter(value: object): value is AptlyRecordingResultReporter {
    return true;
}

export function AptlyRecordingResultReporterFromJSON(json: any): AptlyRecordingResultReporter {
    return AptlyRecordingResultReporterFromJSONTyped(json, false);
}

export function AptlyRecordingResultReporterFromJSONTyped(json: any, ignoreDiscriminator: boolean): AptlyRecordingResultReporter {
    if (json == null) {
        return json;
    }
    return {
        
        'added': json['Added'] == null ? undefined : json['Added'],
        'removed': json['Removed'] == null ? undefined : json['Removed'],
        'warnings': json['Warnings'] == null ? undefined : json['Warnings'],
    };
}

export function AptlyRecordingResultReporterToJSON(json: any): AptlyRecordingResultReporter {
    return AptlyRecordingResultReporterToJSONTyped(json, false);
}

export function AptlyRecordingResultReporterToJSONTyped(value?: AptlyRecordingResultReporter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Added': value['added'],
        'Removed': value['removed'],
        'Warnings': value['warnings'],
    };
}

