/* tslint:disable */
/* eslint-disable */
/**
 * Aptly API
 * Aptly operations are also available via REST API served with `aptly api serve`.  On Debian based systems, a package `aptly-api` is available, which will run aptly as systemd service as dedicated aptly-api user.  Some configuration changes (S3 publishing endpoints, ...) will require restarting the aptly service in order to take effect.  The REST API shouldn\'t be exposed to the Internet as there is no authentication/protection, consider using a HTTP proxy (e.g. nginx) to add https and authentication.  #### Aptly REST API Documentation 
 *
 * The version of the OpenAPI document: 1.6.2+20260228114657.9defe70
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DebLocalRepo
 */
export interface DebLocalRepo {
    /**
     * Comment
     * @type {string}
     * @memberof DebLocalRepo
     */
    comment?: string;
    /**
     * DefaultComponent
     * @type {string}
     * @memberof DebLocalRepo
     */
    defaultComponent?: string;
    /**
     * DefaultDistribution
     * @type {string}
     * @memberof DebLocalRepo
     */
    defaultDistribution?: string;
    /**
     * User-assigned name
     * @type {string}
     * @memberof DebLocalRepo
     */
    name?: string;
}

/**
 * Check if a given object implements the DebLocalRepo interface.
 */
export function instanceOfDebLocalRepo(value: object): value is DebLocalRepo {
    return true;
}

export function DebLocalRepoFromJSON(json: any): DebLocalRepo {
    return DebLocalRepoFromJSONTyped(json, false);
}

export function DebLocalRepoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DebLocalRepo {
    if (json == null) {
        return json;
    }
    return {
        
        'comment': json['Comment'] == null ? undefined : json['Comment'],
        'defaultComponent': json['DefaultComponent'] == null ? undefined : json['DefaultComponent'],
        'defaultDistribution': json['DefaultDistribution'] == null ? undefined : json['DefaultDistribution'],
        'name': json['Name'] == null ? undefined : json['Name'],
    };
}

export function DebLocalRepoToJSON(json: any): DebLocalRepo {
    return DebLocalRepoToJSONTyped(json, false);
}

export function DebLocalRepoToJSONTyped(value?: DebLocalRepo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Comment': value['comment'],
        'DefaultComponent': value['defaultComponent'],
        'DefaultDistribution': value['defaultDistribution'],
        'Name': value['name'],
    };
}

