/* tslint:disable */
/* eslint-disable */
/**
 * Aptly API
 * Aptly operations are also available via REST API served with `aptly api serve`.  On Debian based systems, a package `aptly-api` is available, which will run aptly as systemd service as dedicated aptly-api user.  Some configuration changes (S3 publishing endpoints, ...) will require restarting the aptly service in order to take effect.  The REST API shouldn\'t be exposed to the Internet as there is no authentication/protection, consider using a HTTP proxy (e.g. nginx) to add https and authentication.  #### Aptly REST API Documentation 
 *
 * The version of the OpenAPI document: 1.6.2+20260315225119.eb0ae3a
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DebPublishedRepoRevision } from './DebPublishedRepoRevision';
import {
    DebPublishedRepoRevisionFromJSON,
    DebPublishedRepoRevisionFromJSONTyped,
    DebPublishedRepoRevisionToJSON,
    DebPublishedRepoRevisionToJSONTyped,
} from './DebPublishedRepoRevision';

/**
 * 
 * @export
 * @interface DebPublishedRepo
 */
export interface DebPublishedRepo {
    /**
     * Provide index files per hash also
     * @type {boolean}
     * @memberof DebPublishedRepo
     */
    acquireByHash?: boolean;
    /**
     * Architectures is a list of all architectures published
     * @type {Array<string>}
     * @memberof DebPublishedRepo
     */
    architectures?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof DebPublishedRepo
     */
    butAutomaticUpgrades?: string;
    /**
     * 
     * @type {string}
     * @memberof DebPublishedRepo
     */
    codename?: string;
    /**
     * Legacy fields for compatibility with old published repositories (< 0.6)
     * @type {string}
     * @memberof DebPublishedRepo
     */
    component?: string;
    /**
     * 
     * @type {string}
     * @memberof DebPublishedRepo
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof DebPublishedRepo
     */
    distribution?: string;
    /**
     * 
     * @type {string}
     * @memberof DebPublishedRepo
     */
    label?: string;
    /**
     * Support multiple distributions
     * @type {boolean}
     * @memberof DebPublishedRepo
     */
    multiDist?: boolean;
    /**
     * 
     * @type {string}
     * @memberof DebPublishedRepo
     */
    notAutomatic?: string;
    /**
     * 
     * @type {string}
     * @memberof DebPublishedRepo
     */
    origin?: string;
    /**
     * 
     * @type {string}
     * @memberof DebPublishedRepo
     */
    prefix?: string;
    /**
     * Revision
     * @type {DebPublishedRepoRevision}
     * @memberof DebPublishedRepo
     */
    revision?: DebPublishedRepoRevision;
    /**
     * An optional field containing a comma separated list
     * of OpenPGP key fingerprints to be used
     * for validating the next Release file
     * @type {string}
     * @memberof DebPublishedRepo
     */
    signedBy?: string;
    /**
     * Skip bz2 compression for index files
     * @type {boolean}
     * @memberof DebPublishedRepo
     */
    skipBz2?: boolean;
    /**
     * Skip contents generation
     * @type {boolean}
     * @memberof DebPublishedRepo
     */
    skipContents?: boolean;
    /**
     * SourceKind is "local"/"repo"
     * @type {string}
     * @memberof DebPublishedRepo
     */
    sourceKind?: string;
    /**
     * SourceUUID is UUID of either snapshot or local repo
     * @type {string}
     * @memberof DebPublishedRepo
     */
    sourceUUID?: string;
    /**
     * Map of sources by each component: component name -> source UUID
     * @type {{ [key: string]: string; }}
     * @memberof DebPublishedRepo
     */
    sources?: { [key: string]: string; };
    /**
     * Storage & Prefix & distribution should be unique across all published repositories
     * @type {string}
     * @memberof DebPublishedRepo
     */
    storage?: string;
    /**
     * 
     * @type {string}
     * @memberof DebPublishedRepo
     */
    suite?: string;
    /**
     * Internal unique ID
     * @type {string}
     * @memberof DebPublishedRepo
     */
    uUID?: string;
}

/**
 * Check if a given object implements the DebPublishedRepo interface.
 */
export function instanceOfDebPublishedRepo(value: object): value is DebPublishedRepo {
    return true;
}

export function DebPublishedRepoFromJSON(json: any): DebPublishedRepo {
    return DebPublishedRepoFromJSONTyped(json, false);
}

export function DebPublishedRepoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DebPublishedRepo {
    if (json == null) {
        return json;
    }
    return {
        
        'acquireByHash': json['AcquireByHash'] == null ? undefined : json['AcquireByHash'],
        'architectures': json['Architectures'] == null ? undefined : json['Architectures'],
        'butAutomaticUpgrades': json['ButAutomaticUpgrades'] == null ? undefined : json['ButAutomaticUpgrades'],
        'codename': json['Codename'] == null ? undefined : json['Codename'],
        'component': json['Component'] == null ? undefined : json['Component'],
        'description': json['Description'] == null ? undefined : json['Description'],
        'distribution': json['Distribution'] == null ? undefined : json['Distribution'],
        'label': json['Label'] == null ? undefined : json['Label'],
        'multiDist': json['MultiDist'] == null ? undefined : json['MultiDist'],
        'notAutomatic': json['NotAutomatic'] == null ? undefined : json['NotAutomatic'],
        'origin': json['Origin'] == null ? undefined : json['Origin'],
        'prefix': json['Prefix'] == null ? undefined : json['Prefix'],
        'revision': json['Revision'] == null ? undefined : DebPublishedRepoRevisionFromJSON(json['Revision']),
        'signedBy': json['SignedBy'] == null ? undefined : json['SignedBy'],
        'skipBz2': json['SkipBz2'] == null ? undefined : json['SkipBz2'],
        'skipContents': json['SkipContents'] == null ? undefined : json['SkipContents'],
        'sourceKind': json['SourceKind'] == null ? undefined : json['SourceKind'],
        'sourceUUID': json['SourceUUID'] == null ? undefined : json['SourceUUID'],
        'sources': json['Sources'] == null ? undefined : json['Sources'],
        'storage': json['Storage'] == null ? undefined : json['Storage'],
        'suite': json['Suite'] == null ? undefined : json['Suite'],
        'uUID': json['UUID'] == null ? undefined : json['UUID'],
    };
}

export function DebPublishedRepoToJSON(json: any): DebPublishedRepo {
    return DebPublishedRepoToJSONTyped(json, false);
}

export function DebPublishedRepoToJSONTyped(value?: DebPublishedRepo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'AcquireByHash': value['acquireByHash'],
        'Architectures': value['architectures'],
        'ButAutomaticUpgrades': value['butAutomaticUpgrades'],
        'Codename': value['codename'],
        'Component': value['component'],
        'Description': value['description'],
        'Distribution': value['distribution'],
        'Label': value['label'],
        'MultiDist': value['multiDist'],
        'NotAutomatic': value['notAutomatic'],
        'Origin': value['origin'],
        'Prefix': value['prefix'],
        'Revision': DebPublishedRepoRevisionToJSON(value['revision']),
        'SignedBy': value['signedBy'],
        'SkipBz2': value['skipBz2'],
        'SkipContents': value['skipContents'],
        'SourceKind': value['sourceKind'],
        'SourceUUID': value['sourceUUID'],
        'Sources': value['sources'],
        'Storage': value['storage'],
        'Suite': value['suite'],
        'UUID': value['uUID'],
    };
}

