/* tslint:disable */
/* eslint-disable */
/**
 * Aptly API
 * Aptly operations are also available via REST API served with `aptly api serve`.  On Debian based systems, a package `aptly-api` is available, which will run aptly as systemd service as dedicated aptly-api user.  Some configuration changes (S3 publishing endpoints, ...) will require restarting the aptly service in order to take effect.  The REST API shouldn\'t be exposed to the Internet as there is no authentication/protection, consider using a HTTP proxy (e.g. nginx) to add https and authentication.  #### Aptly REST API Documentation 
 *
 * The version of the OpenAPI document: 1.6.2+20260228114657.9defe70
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DebPackage } from './DebPackage';
import {
    DebPackageFromJSON,
    DebPackageFromJSONTyped,
    DebPackageToJSON,
    DebPackageToJSONTyped,
} from './DebPackage';

/**
 * 
 * @export
 * @interface DebPackageDiff
 */
export interface DebPackageDiff {
    /**
     * 
     * @type {DebPackage}
     * @memberof DebPackageDiff
     */
    left?: DebPackage;
    /**
     * 
     * @type {DebPackage}
     * @memberof DebPackageDiff
     */
    right?: DebPackage;
}

/**
 * Check if a given object implements the DebPackageDiff interface.
 */
export function instanceOfDebPackageDiff(value: object): value is DebPackageDiff {
    return true;
}

export function DebPackageDiffFromJSON(json: any): DebPackageDiff {
    return DebPackageDiffFromJSONTyped(json, false);
}

export function DebPackageDiffFromJSONTyped(json: any, ignoreDiscriminator: boolean): DebPackageDiff {
    if (json == null) {
        return json;
    }
    return {
        
        'left': json['Left'] == null ? undefined : DebPackageFromJSON(json['Left']),
        'right': json['Right'] == null ? undefined : DebPackageFromJSON(json['Right']),
    };
}

export function DebPackageDiffToJSON(json: any): DebPackageDiff {
    return DebPackageDiffToJSONTyped(json, false);
}

export function DebPackageDiffToJSONTyped(value?: DebPackageDiff | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Left': DebPackageToJSON(value['left']),
        'Right': DebPackageToJSON(value['right']),
    };
}

