/* tslint:disable */
/* eslint-disable */
/**
 * Aptly API
 * Aptly operations are also available via REST API served with `aptly api serve`.  On Debian based systems, a package `aptly-api` is available, which will run aptly as systemd service as dedicated aptly-api user.  Some configuration changes (S3 publishing endpoints, ...) will require restarting the aptly service in order to take effect.  The REST API shouldn\'t be exposed to the Internet as there is no authentication/protection, consider using a HTTP proxy (e.g. nginx) to add https and authentication.  #### Aptly REST API Documentation 
 *
 * The version of the OpenAPI document: 1.6.2+20260228114657.9defe70
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DebPackage
 */
export interface DebPackage {
    /**
     * 
     * @type {string}
     * @memberof DebPackage
     */
    architecture?: string;
    /**
     * Hash of files section
     * @type {number}
     * @memberof DebPackage
     */
    filesHash?: number;
    /**
     * Is this package a dummy installer package
     * @type {boolean}
     * @memberof DebPackage
     */
    isInstaller?: boolean;
    /**
     * Is this source package
     * @type {boolean}
     * @memberof DebPackage
     */
    isSource?: boolean;
    /**
     * Is this udeb package
     * @type {boolean}
     * @memberof DebPackage
     */
    isUdeb?: boolean;
    /**
     * Basic package properties
     * @type {string}
     * @memberof DebPackage
     */
    name?: string;
    /**
     * List of virtual packages this package provides
     * @type {Array<string>}
     * @memberof DebPackage
     */
    provides?: Array<string>;
    /**
     * For binary package, name of source package
     * @type {string}
     * @memberof DebPackage
     */
    source?: string;
    /**
     * If this source package, this field holds "real" architecture value,
     * while Architecture would be equal to "source"
     * @type {string}
     * @memberof DebPackage
     */
    sourceArchitecture?: string;
    /**
     * Is this >= 0.6 package?
     * @type {boolean}
     * @memberof DebPackage
     */
    v06Plus?: boolean;
    /**
     * 
     * @type {string}
     * @memberof DebPackage
     */
    version?: string;
}

/**
 * Check if a given object implements the DebPackage interface.
 */
export function instanceOfDebPackage(value: object): value is DebPackage {
    return true;
}

export function DebPackageFromJSON(json: any): DebPackage {
    return DebPackageFromJSONTyped(json, false);
}

export function DebPackageFromJSONTyped(json: any, ignoreDiscriminator: boolean): DebPackage {
    if (json == null) {
        return json;
    }
    return {
        
        'architecture': json['Architecture'] == null ? undefined : json['Architecture'],
        'filesHash': json['FilesHash'] == null ? undefined : json['FilesHash'],
        'isInstaller': json['IsInstaller'] == null ? undefined : json['IsInstaller'],
        'isSource': json['IsSource'] == null ? undefined : json['IsSource'],
        'isUdeb': json['IsUdeb'] == null ? undefined : json['IsUdeb'],
        'name': json['Name'] == null ? undefined : json['Name'],
        'provides': json['Provides'] == null ? undefined : json['Provides'],
        'source': json['Source'] == null ? undefined : json['Source'],
        'sourceArchitecture': json['SourceArchitecture'] == null ? undefined : json['SourceArchitecture'],
        'v06Plus': json['V06Plus'] == null ? undefined : json['V06Plus'],
        'version': json['Version'] == null ? undefined : json['Version'],
    };
}

export function DebPackageToJSON(json: any): DebPackage {
    return DebPackageToJSONTyped(json, false);
}

export function DebPackageToJSONTyped(value?: DebPackage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Architecture': value['architecture'],
        'FilesHash': value['filesHash'],
        'IsInstaller': value['isInstaller'],
        'IsSource': value['isSource'],
        'IsUdeb': value['isUdeb'],
        'Name': value['name'],
        'Provides': value['provides'],
        'Source': value['source'],
        'SourceArchitecture': value['sourceArchitecture'],
        'V06Plus': value['v06Plus'],
        'Version': value['version'],
    };
}

