/* tslint:disable */
/* eslint-disable */
/**
 * Aptly API
 * Aptly operations are also available via REST API served with `aptly api serve`.  On Debian based systems, a package `aptly-api` is available, which will run aptly as systemd service as dedicated aptly-api user.  Some configuration changes (S3 publishing endpoints, ...) will require restarting the aptly service in order to take effect.  The REST API shouldn\'t be exposed to the Internet as there is no authentication/protection, consider using a HTTP proxy (e.g. nginx) to add https and authentication.  #### Aptly REST API Documentation 
 *
 * The version of the OpenAPI document: 1.6.2+20260315225119.eb0ae3a
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DebPublishedRepoRevision
 */
export interface DebPublishedRepoRevision {
    /**
     * Map of sources: component name -> snapshot name/local repo Name
     * @type {{ [key: string]: string; }}
     * @memberof DebPublishedRepoRevision
     */
    sources?: { [key: string]: string; };
}

/**
 * Check if a given object implements the DebPublishedRepoRevision interface.
 */
export function instanceOfDebPublishedRepoRevision(value: object): value is DebPublishedRepoRevision {
    return true;
}

export function DebPublishedRepoRevisionFromJSON(json: any): DebPublishedRepoRevision {
    return DebPublishedRepoRevisionFromJSONTyped(json, false);
}

export function DebPublishedRepoRevisionFromJSONTyped(json: any, ignoreDiscriminator: boolean): DebPublishedRepoRevision {
    if (json == null) {
        return json;
    }
    return {
        
        'sources': json['Sources'] == null ? undefined : json['Sources'],
    };
}

export function DebPublishedRepoRevisionToJSON(json: any): DebPublishedRepoRevision {
    return DebPublishedRepoRevisionToJSONTyped(json, false);
}

export function DebPublishedRepoRevisionToJSONTyped(value?: DebPublishedRepoRevision | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Sources': value['sources'],
    };
}

