/* tslint:disable */
/* eslint-disable */
/**
 * Aptly API
 * Aptly operations are also available via REST API served with `aptly api serve`.  On Debian based systems, a package `aptly-api` is available, which will run aptly as systemd service as dedicated aptly-api user.  Some configuration changes (S3 publishing endpoints, ...) will require restarting the aptly service in order to take effect.  The REST API shouldn\'t be exposed to the Internet as there is no authentication/protection, consider using a HTTP proxy (e.g. nginx) to add https and authentication.  #### Aptly REST API Documentation 
 *
 * The version of the OpenAPI document: 1.6.2+20260308145521.8e943a3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DebSourceEntry
 */
export interface DebSourceEntry {
    /**
     * 
     * @type {string}
     * @memberof DebSourceEntry
     */
    component?: string;
    /**
     * 
     * @type {string}
     * @memberof DebSourceEntry
     */
    name?: string;
}

/**
 * Check if a given object implements the DebSourceEntry interface.
 */
export function instanceOfDebSourceEntry(value: object): value is DebSourceEntry {
    return true;
}

export function DebSourceEntryFromJSON(json: any): DebSourceEntry {
    return DebSourceEntryFromJSONTyped(json, false);
}

export function DebSourceEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): DebSourceEntry {
    if (json == null) {
        return json;
    }
    return {
        
        'component': json['Component'] == null ? undefined : json['Component'],
        'name': json['Name'] == null ? undefined : json['Name'],
    };
}

export function DebSourceEntryToJSON(json: any): DebSourceEntry {
    return DebSourceEntryToJSONTyped(json, false);
}

export function DebSourceEntryToJSONTyped(value?: DebSourceEntry | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Component': value['component'],
        'Name': value['name'],
    };
}

