/*
Aptly API

Aptly operations are also available via REST API served with `aptly api serve`.  On Debian based systems, a package `aptly-api` is available, which will run aptly as systemd service as dedicated aptly-api user.  Some configuration changes (S3 publishing endpoints, ...) will require restarting the aptly service in order to take effect.  The REST API shouldn't be exposed to the Internet as there is no authentication/protection, consider using a HTTP proxy (e.g. nginx) to add https and authentication.  #### Aptly REST API Documentation 

API version: 1.6.2+20260228114657.9defe70
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aptly

import (
	"encoding/json"
)

// checks if the DebPublishedRepoRevision type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DebPublishedRepoRevision{}

// DebPublishedRepoRevision struct for DebPublishedRepoRevision
type DebPublishedRepoRevision struct {
	// Map of sources: component name -> snapshot name/local repo Name
	Sources *map[string]string `json:"Sources,omitempty"`
}

// NewDebPublishedRepoRevision instantiates a new DebPublishedRepoRevision object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDebPublishedRepoRevision() *DebPublishedRepoRevision {
	this := DebPublishedRepoRevision{}
	return &this
}

// NewDebPublishedRepoRevisionWithDefaults instantiates a new DebPublishedRepoRevision object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDebPublishedRepoRevisionWithDefaults() *DebPublishedRepoRevision {
	this := DebPublishedRepoRevision{}
	return &this
}

// GetSources returns the Sources field value if set, zero value otherwise.
func (o *DebPublishedRepoRevision) GetSources() map[string]string {
	if o == nil || IsNil(o.Sources) {
		var ret map[string]string
		return ret
	}
	return *o.Sources
}

// GetSourcesOk returns a tuple with the Sources field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebPublishedRepoRevision) GetSourcesOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Sources) {
		return nil, false
	}
	return o.Sources, true
}

// HasSources returns a boolean if a field has been set.
func (o *DebPublishedRepoRevision) HasSources() bool {
	if o != nil && !IsNil(o.Sources) {
		return true
	}

	return false
}

// SetSources gets a reference to the given map[string]string and assigns it to the Sources field.
func (o *DebPublishedRepoRevision) SetSources(v map[string]string) {
	o.Sources = &v
}

func (o DebPublishedRepoRevision) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DebPublishedRepoRevision) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Sources) {
		toSerialize["Sources"] = o.Sources
	}
	return toSerialize, nil
}

type NullableDebPublishedRepoRevision struct {
	value *DebPublishedRepoRevision
	isSet bool
}

func (v NullableDebPublishedRepoRevision) Get() *DebPublishedRepoRevision {
	return v.value
}

func (v *NullableDebPublishedRepoRevision) Set(val *DebPublishedRepoRevision) {
	v.value = val
	v.isSet = true
}

func (v NullableDebPublishedRepoRevision) IsSet() bool {
	return v.isSet
}

func (v *NullableDebPublishedRepoRevision) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDebPublishedRepoRevision(val *DebPublishedRepoRevision) *NullableDebPublishedRepoRevision {
	return &NullableDebPublishedRepoRevision{value: val, isSet: true}
}

func (v NullableDebPublishedRepoRevision) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDebPublishedRepoRevision) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


