/*
Aptly API

Aptly operations are also available via REST API served with `aptly api serve`.  On Debian based systems, a package `aptly-api` is available, which will run aptly as systemd service as dedicated aptly-api user.  Some configuration changes (S3 publishing endpoints, ...) will require restarting the aptly service in order to take effect.  The REST API shouldn't be exposed to the Internet as there is no authentication/protection, consider using a HTTP proxy (e.g. nginx) to add https and authentication.  #### Aptly REST API Documentation 

API version: 1.6.2+20260228114657.9defe70
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aptly

import (
	"encoding/json"
)

// checks if the ApiDiskFree type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiDiskFree{}

// ApiDiskFree struct for ApiDiskFree
type ApiDiskFree struct {
	// Available Storage [MiB]
	Free *int64 `json:"Free,omitempty"`
	// Percentage Full
	PercentFull *float32 `json:"PercentFull,omitempty"`
	// Storage size [MiB]
	Total *int64 `json:"Total,omitempty"`
}

// NewApiDiskFree instantiates a new ApiDiskFree object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiDiskFree() *ApiDiskFree {
	this := ApiDiskFree{}
	return &this
}

// NewApiDiskFreeWithDefaults instantiates a new ApiDiskFree object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiDiskFreeWithDefaults() *ApiDiskFree {
	this := ApiDiskFree{}
	return &this
}

// GetFree returns the Free field value if set, zero value otherwise.
func (o *ApiDiskFree) GetFree() int64 {
	if o == nil || IsNil(o.Free) {
		var ret int64
		return ret
	}
	return *o.Free
}

// GetFreeOk returns a tuple with the Free field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiDiskFree) GetFreeOk() (*int64, bool) {
	if o == nil || IsNil(o.Free) {
		return nil, false
	}
	return o.Free, true
}

// HasFree returns a boolean if a field has been set.
func (o *ApiDiskFree) HasFree() bool {
	if o != nil && !IsNil(o.Free) {
		return true
	}

	return false
}

// SetFree gets a reference to the given int64 and assigns it to the Free field.
func (o *ApiDiskFree) SetFree(v int64) {
	o.Free = &v
}

// GetPercentFull returns the PercentFull field value if set, zero value otherwise.
func (o *ApiDiskFree) GetPercentFull() float32 {
	if o == nil || IsNil(o.PercentFull) {
		var ret float32
		return ret
	}
	return *o.PercentFull
}

// GetPercentFullOk returns a tuple with the PercentFull field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiDiskFree) GetPercentFullOk() (*float32, bool) {
	if o == nil || IsNil(o.PercentFull) {
		return nil, false
	}
	return o.PercentFull, true
}

// HasPercentFull returns a boolean if a field has been set.
func (o *ApiDiskFree) HasPercentFull() bool {
	if o != nil && !IsNil(o.PercentFull) {
		return true
	}

	return false
}

// SetPercentFull gets a reference to the given float32 and assigns it to the PercentFull field.
func (o *ApiDiskFree) SetPercentFull(v float32) {
	o.PercentFull = &v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *ApiDiskFree) GetTotal() int64 {
	if o == nil || IsNil(o.Total) {
		var ret int64
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiDiskFree) GetTotalOk() (*int64, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *ApiDiskFree) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int64 and assigns it to the Total field.
func (o *ApiDiskFree) SetTotal(v int64) {
	o.Total = &v
}

func (o ApiDiskFree) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiDiskFree) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Free) {
		toSerialize["Free"] = o.Free
	}
	if !IsNil(o.PercentFull) {
		toSerialize["PercentFull"] = o.PercentFull
	}
	if !IsNil(o.Total) {
		toSerialize["Total"] = o.Total
	}
	return toSerialize, nil
}

type NullableApiDiskFree struct {
	value *ApiDiskFree
	isSet bool
}

func (v NullableApiDiskFree) Get() *ApiDiskFree {
	return v.value
}

func (v *NullableApiDiskFree) Set(val *ApiDiskFree) {
	v.value = val
	v.isSet = true
}

func (v NullableApiDiskFree) IsSet() bool {
	return v.isSet
}

func (v *NullableApiDiskFree) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiDiskFree(val *ApiDiskFree) *NullableApiDiskFree {
	return &NullableApiDiskFree{value: val, isSet: true}
}

func (v NullableApiDiskFree) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiDiskFree) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


