/*
Aptly API

Aptly operations are also available via REST API served with `aptly api serve`.  On Debian based systems, a package `aptly-api` is available, which will run aptly as systemd service as dedicated aptly-api user.  Some configuration changes (S3 publishing endpoints, ...) will require restarting the aptly service in order to take effect.  The REST API shouldn't be exposed to the Internet as there is no authentication/protection, consider using a HTTP proxy (e.g. nginx) to add https and authentication.  #### Aptly REST API Documentation 

API version: 1.6.2+20260308145521.8e943a3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aptly

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


// PublishAPIService PublishAPI service
type PublishAPIService service

type ApiApiPublishGetRequest struct {
	ctx context.Context
	ApiService *PublishAPIService
}

func (r ApiApiPublishGetRequest) Execute() ([]DebPublishedRepo, *http.Response, error) {
	return r.ApiService.ApiPublishGetExecute(r)
}

/*
ApiPublishGet List Published Repositories

**Get list of published repositories**

Return list of published repositories including detailed information.

See also: `aptly publish list`

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiApiPublishGetRequest
*/
func (a *PublishAPIService) ApiPublishGet(ctx context.Context) ApiApiPublishGetRequest {
	return ApiApiPublishGetRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return []DebPublishedRepo
func (a *PublishAPIService) ApiPublishGetExecute(r ApiApiPublishGetRequest) ([]DebPublishedRepo, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  []DebPublishedRepo
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PublishAPIService.ApiPublishGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/publish"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiApiPublishPrefixDistributionDeleteRequest struct {
	ctx context.Context
	ApiService *PublishAPIService
	prefix string
	distribution string
	force *int32
	skipCleanup *int32
	async *bool
}

// force: 1 to enable
func (r ApiApiPublishPrefixDistributionDeleteRequest) Force(force int32) ApiApiPublishPrefixDistributionDeleteRequest {
	r.force = &force
	return r
}

// skipCleanup: 1 to enable
func (r ApiApiPublishPrefixDistributionDeleteRequest) SkipCleanup(skipCleanup int32) ApiApiPublishPrefixDistributionDeleteRequest {
	r.skipCleanup = &skipCleanup
	return r
}

// Run in background and return task object
func (r ApiApiPublishPrefixDistributionDeleteRequest) Async(async bool) ApiApiPublishPrefixDistributionDeleteRequest {
	r.async = &async
	return r
}

func (r ApiApiPublishPrefixDistributionDeleteRequest) Execute() (*http.Response, error) {
	return r.ApiService.ApiPublishPrefixDistributionDeleteExecute(r)
}

/*
ApiPublishPrefixDistributionDelete Delete Published Repository

**Delete a published repository**

Delete a distribution of a published repository and remove associated files.

If no other published repositories share the same prefix, all files inside the prefix will be removed.

See also: `aptly publish drop`

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param prefix publishing prefix
 @param distribution distribution name
 @return ApiApiPublishPrefixDistributionDeleteRequest
*/
func (a *PublishAPIService) ApiPublishPrefixDistributionDelete(ctx context.Context, prefix string, distribution string) ApiApiPublishPrefixDistributionDeleteRequest {
	return ApiApiPublishPrefixDistributionDeleteRequest{
		ApiService: a,
		ctx: ctx,
		prefix: prefix,
		distribution: distribution,
	}
}

// Execute executes the request
func (a *PublishAPIService) ApiPublishPrefixDistributionDeleteExecute(r ApiApiPublishPrefixDistributionDeleteRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodDelete
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PublishAPIService.ApiPublishPrefixDistributionDelete")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/publish/{prefix}/{distribution}"
	localVarPath = strings.Replace(localVarPath, "{"+"prefix"+"}", url.PathEscape(parameterValueToString(r.prefix, "prefix")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"distribution"+"}", url.PathEscape(parameterValueToString(r.distribution, "distribution")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.force == nil {
		return nil, reportError("force is required and must be specified")
	}
	if r.skipCleanup == nil {
		return nil, reportError("skipCleanup is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "force", r.force, "", "")
	parameterAddToHeaderOrQuery(localVarQueryParams, "skipCleanup", r.skipCleanup, "", "")
	if r.async != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "_async", r.async, "", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiApiPublishPrefixDistributionGetRequest struct {
	ctx context.Context
	ApiService *PublishAPIService
	prefix string
	distribution string
}

func (r ApiApiPublishPrefixDistributionGetRequest) Execute() (*DebPublishedRepo, *http.Response, error) {
	return r.ApiService.ApiPublishPrefixDistributionGetExecute(r)
}

/*
ApiPublishPrefixDistributionGet Show Published Repository

**Get published repository information**

Show detailed information of a published repository.

See also: `aptly publish show`

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param prefix publishing prefix, use `:.` instead of `.` because it is ambigious in URLs
 @param distribution distribution name
 @return ApiApiPublishPrefixDistributionGetRequest
*/
func (a *PublishAPIService) ApiPublishPrefixDistributionGet(ctx context.Context, prefix string, distribution string) ApiApiPublishPrefixDistributionGetRequest {
	return ApiApiPublishPrefixDistributionGetRequest{
		ApiService: a,
		ctx: ctx,
		prefix: prefix,
		distribution: distribution,
	}
}

// Execute executes the request
//  @return DebPublishedRepo
func (a *PublishAPIService) ApiPublishPrefixDistributionGetExecute(r ApiApiPublishPrefixDistributionGetRequest) (*DebPublishedRepo, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *DebPublishedRepo
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PublishAPIService.ApiPublishPrefixDistributionGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/publish/{prefix}/{distribution}"
	localVarPath = strings.Replace(localVarPath, "{"+"prefix"+"}", url.PathEscape(parameterValueToString(r.prefix, "prefix")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"distribution"+"}", url.PathEscape(parameterValueToString(r.distribution, "distribution")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiApiPublishPrefixDistributionPutRequest struct {
	ctx context.Context
	ApiService *PublishAPIService
	prefix string
	distribution string
	request *ApiPublishedRepoUpdateSwitchParams
	async *bool
}

// Parameters
func (r ApiApiPublishPrefixDistributionPutRequest) Request(request ApiPublishedRepoUpdateSwitchParams) ApiApiPublishPrefixDistributionPutRequest {
	r.request = &request
	return r
}

// Run in background and return task object
func (r ApiApiPublishPrefixDistributionPutRequest) Async(async bool) ApiApiPublishPrefixDistributionPutRequest {
	r.async = &async
	return r
}

func (r ApiApiPublishPrefixDistributionPutRequest) Execute() (*DebPublishedRepo, *http.Response, error) {
	return r.ApiService.ApiPublishPrefixDistributionPutExecute(r)
}

/*
ApiPublishPrefixDistributionPut Update Published Repository

**Update a published repository**

Update a published local repository or switch snapshot.

For published local repositories:
* update to match local repository contents

For published snapshots:
* switch components to new snapshot

See also: `aptly publish update` / `aptly publish switch`

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param prefix publishing prefix
 @param distribution distribution name
 @return ApiApiPublishPrefixDistributionPutRequest
*/
func (a *PublishAPIService) ApiPublishPrefixDistributionPut(ctx context.Context, prefix string, distribution string) ApiApiPublishPrefixDistributionPutRequest {
	return ApiApiPublishPrefixDistributionPutRequest{
		ApiService: a,
		ctx: ctx,
		prefix: prefix,
		distribution: distribution,
	}
}

// Execute executes the request
//  @return DebPublishedRepo
func (a *PublishAPIService) ApiPublishPrefixDistributionPutExecute(r ApiApiPublishPrefixDistributionPutRequest) (*DebPublishedRepo, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPut
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *DebPublishedRepo
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PublishAPIService.ApiPublishPrefixDistributionPut")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/publish/{prefix}/{distribution}"
	localVarPath = strings.Replace(localVarPath, "{"+"prefix"+"}", url.PathEscape(parameterValueToString(r.prefix, "prefix")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"distribution"+"}", url.PathEscape(parameterValueToString(r.distribution, "distribution")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.request == nil {
		return localVarReturnValue, nil, reportError("request is required and must be specified")
	}

	if r.async != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "_async", r.async, "", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.request
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiApiPublishPrefixDistributionSourcesComponentDeleteRequest struct {
	ctx context.Context
	ApiService *PublishAPIService
	prefix string
	distribution string
	component string
	async *bool
}

// Run in background and return task object
func (r ApiApiPublishPrefixDistributionSourcesComponentDeleteRequest) Async(async bool) ApiApiPublishPrefixDistributionSourcesComponentDeleteRequest {
	r.async = &async
	return r
}

func (r ApiApiPublishPrefixDistributionSourcesComponentDeleteRequest) Execute() (*http.Response, error) {
	return r.ApiService.ApiPublishPrefixDistributionSourcesComponentDeleteExecute(r)
}

/*
ApiPublishPrefixDistributionSourcesComponentDelete Remove Source Component

**Remove a source component from a published repo**

Remove a source component (snapshot / local repo) from a published repository.

This call does not publish the changes, but rather schedules them for a subsequent publish update call (i.e `PUT /api/publish/{prefix}/{distribution}` / `POST /api/publish/{prefix}/{distribution}/update`).

See also: `aptly publish source remove`

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param prefix publishing prefix
 @param distribution distribution name
 @param component component name
 @return ApiApiPublishPrefixDistributionSourcesComponentDeleteRequest
*/
func (a *PublishAPIService) ApiPublishPrefixDistributionSourcesComponentDelete(ctx context.Context, prefix string, distribution string, component string) ApiApiPublishPrefixDistributionSourcesComponentDeleteRequest {
	return ApiApiPublishPrefixDistributionSourcesComponentDeleteRequest{
		ApiService: a,
		ctx: ctx,
		prefix: prefix,
		distribution: distribution,
		component: component,
	}
}

// Execute executes the request
func (a *PublishAPIService) ApiPublishPrefixDistributionSourcesComponentDeleteExecute(r ApiApiPublishPrefixDistributionSourcesComponentDeleteRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodDelete
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PublishAPIService.ApiPublishPrefixDistributionSourcesComponentDelete")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/publish/{prefix}/{distribution}/sources/{component}"
	localVarPath = strings.Replace(localVarPath, "{"+"prefix"+"}", url.PathEscape(parameterValueToString(r.prefix, "prefix")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"distribution"+"}", url.PathEscape(parameterValueToString(r.distribution, "distribution")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"component"+"}", url.PathEscape(parameterValueToString(r.component, "component")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.async != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "_async", r.async, "", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiApiPublishPrefixDistributionSourcesComponentPutRequest struct {
	ctx context.Context
	ApiService *PublishAPIService
	prefix string
	distribution string
	component string
	request *ApiSourceParams
	async *bool
}

// Parameters
func (r ApiApiPublishPrefixDistributionSourcesComponentPutRequest) Request(request ApiSourceParams) ApiApiPublishPrefixDistributionSourcesComponentPutRequest {
	r.request = &request
	return r
}

// Run in background and return task object
func (r ApiApiPublishPrefixDistributionSourcesComponentPutRequest) Async(async bool) ApiApiPublishPrefixDistributionSourcesComponentPutRequest {
	r.async = &async
	return r
}

func (r ApiApiPublishPrefixDistributionSourcesComponentPutRequest) Execute() (*http.Response, error) {
	return r.ApiService.ApiPublishPrefixDistributionSourcesComponentPutExecute(r)
}

/*
ApiPublishPrefixDistributionSourcesComponentPut Update Source Component

**Update the source component of a published repository**

Update a component of a snapshot or local repository to be published.

This call does not publish the changes, but rather schedules them for a subsequent publish update call (i.e `PUT /api/publish/{prefix}/{distribution}` / `POST /api/publish/{prefix}/{distribution}/update`).

See also: `aptly publish source update`

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param prefix publishing prefix
 @param distribution distribution name
 @param component component name
 @return ApiApiPublishPrefixDistributionSourcesComponentPutRequest
*/
func (a *PublishAPIService) ApiPublishPrefixDistributionSourcesComponentPut(ctx context.Context, prefix string, distribution string, component string) ApiApiPublishPrefixDistributionSourcesComponentPutRequest {
	return ApiApiPublishPrefixDistributionSourcesComponentPutRequest{
		ApiService: a,
		ctx: ctx,
		prefix: prefix,
		distribution: distribution,
		component: component,
	}
}

// Execute executes the request
func (a *PublishAPIService) ApiPublishPrefixDistributionSourcesComponentPutExecute(r ApiApiPublishPrefixDistributionSourcesComponentPutRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPut
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PublishAPIService.ApiPublishPrefixDistributionSourcesComponentPut")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/publish/{prefix}/{distribution}/sources/{component}"
	localVarPath = strings.Replace(localVarPath, "{"+"prefix"+"}", url.PathEscape(parameterValueToString(r.prefix, "prefix")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"distribution"+"}", url.PathEscape(parameterValueToString(r.distribution, "distribution")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"component"+"}", url.PathEscape(parameterValueToString(r.component, "component")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.request == nil {
		return nil, reportError("request is required and must be specified")
	}

	if r.async != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "_async", r.async, "", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.request
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiApiPublishPrefixDistributionSourcesDeleteRequest struct {
	ctx context.Context
	ApiService *PublishAPIService
	prefix string
	distribution string
	async *bool
}

// Run in background and return task object
func (r ApiApiPublishPrefixDistributionSourcesDeleteRequest) Async(async bool) ApiApiPublishPrefixDistributionSourcesDeleteRequest {
	r.async = &async
	return r
}

func (r ApiApiPublishPrefixDistributionSourcesDeleteRequest) Execute() (*http.Response, error) {
	return r.ApiService.ApiPublishPrefixDistributionSourcesDeleteExecute(r)
}

/*
ApiPublishPrefixDistributionSourcesDelete Discard Pending Changes

**Discard pending source component changes of a published repository**

Remove all pending changes what would be applied with a subsequent publish update call (i.e. `PUT /api/publish/{prefix}/{distribution}` / `POST /api/publish/{prefix}/{distribution}/update`).

See also: `aptly publish source drop`

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param prefix publishing prefix
 @param distribution distribution name
 @return ApiApiPublishPrefixDistributionSourcesDeleteRequest
*/
func (a *PublishAPIService) ApiPublishPrefixDistributionSourcesDelete(ctx context.Context, prefix string, distribution string) ApiApiPublishPrefixDistributionSourcesDeleteRequest {
	return ApiApiPublishPrefixDistributionSourcesDeleteRequest{
		ApiService: a,
		ctx: ctx,
		prefix: prefix,
		distribution: distribution,
	}
}

// Execute executes the request
func (a *PublishAPIService) ApiPublishPrefixDistributionSourcesDeleteExecute(r ApiApiPublishPrefixDistributionSourcesDeleteRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodDelete
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PublishAPIService.ApiPublishPrefixDistributionSourcesDelete")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/publish/{prefix}/{distribution}/sources"
	localVarPath = strings.Replace(localVarPath, "{"+"prefix"+"}", url.PathEscape(parameterValueToString(r.prefix, "prefix")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"distribution"+"}", url.PathEscape(parameterValueToString(r.distribution, "distribution")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.async != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "_async", r.async, "", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiApiPublishPrefixDistributionSourcesGetRequest struct {
	ctx context.Context
	ApiService *PublishAPIService
	prefix string
	distribution string
}

func (r ApiApiPublishPrefixDistributionSourcesGetRequest) Execute() ([][]DebSourceEntry, *http.Response, error) {
	return r.ApiService.ApiPublishPrefixDistributionSourcesGetExecute(r)
}

/*
ApiPublishPrefixDistributionSourcesGet List Pending Changes

**List source component changes to be applied**

Return added, removed or changed components of snapshots or local repository to be published.

The changes will be applied by a subsequent publish update call (i.e. `PUT /api/publish/{prefix}/{distribution}` / `POST /api/publish/{prefix}/{distribution}/update`).

See also: `aptly publish source list`

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param prefix publishing prefix
 @param distribution distribution name
 @return ApiApiPublishPrefixDistributionSourcesGetRequest
*/
func (a *PublishAPIService) ApiPublishPrefixDistributionSourcesGet(ctx context.Context, prefix string, distribution string) ApiApiPublishPrefixDistributionSourcesGetRequest {
	return ApiApiPublishPrefixDistributionSourcesGetRequest{
		ApiService: a,
		ctx: ctx,
		prefix: prefix,
		distribution: distribution,
	}
}

// Execute executes the request
//  @return [][]DebSourceEntry
func (a *PublishAPIService) ApiPublishPrefixDistributionSourcesGetExecute(r ApiApiPublishPrefixDistributionSourcesGetRequest) ([][]DebSourceEntry, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  [][]DebSourceEntry
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PublishAPIService.ApiPublishPrefixDistributionSourcesGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/publish/{prefix}/{distribution}/sources"
	localVarPath = strings.Replace(localVarPath, "{"+"prefix"+"}", url.PathEscape(parameterValueToString(r.prefix, "prefix")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"distribution"+"}", url.PathEscape(parameterValueToString(r.distribution, "distribution")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiApiPublishPrefixDistributionSourcesPostRequest struct {
	ctx context.Context
	ApiService *PublishAPIService
	prefix string
	distribution string
	request *ApiSourceParams
	async *bool
}

// Parameters
func (r ApiApiPublishPrefixDistributionSourcesPostRequest) Request(request ApiSourceParams) ApiApiPublishPrefixDistributionSourcesPostRequest {
	r.request = &request
	return r
}

// Run in background and return task object
func (r ApiApiPublishPrefixDistributionSourcesPostRequest) Async(async bool) ApiApiPublishPrefixDistributionSourcesPostRequest {
	r.async = &async
	return r
}

func (r ApiApiPublishPrefixDistributionSourcesPostRequest) Execute() (*http.Response, error) {
	return r.ApiService.ApiPublishPrefixDistributionSourcesPostExecute(r)
}

/*
ApiPublishPrefixDistributionSourcesPost Add Source Component

**Add a source component to a published repo**

Add a component of a snapshot or local repository to be published.

This call does not publish the changes, but rather schedules them for a subsequent publish update call (i.e `PUT /api/publish/{prefix}/{distribution}` / `POST /api/publish/{prefix}/{distribution}/update`).

See also: `aptly publish source add`

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param prefix publishing prefix
 @param distribution distribution name
 @return ApiApiPublishPrefixDistributionSourcesPostRequest
*/
func (a *PublishAPIService) ApiPublishPrefixDistributionSourcesPost(ctx context.Context, prefix string, distribution string) ApiApiPublishPrefixDistributionSourcesPostRequest {
	return ApiApiPublishPrefixDistributionSourcesPostRequest{
		ApiService: a,
		ctx: ctx,
		prefix: prefix,
		distribution: distribution,
	}
}

// Execute executes the request
func (a *PublishAPIService) ApiPublishPrefixDistributionSourcesPostExecute(r ApiApiPublishPrefixDistributionSourcesPostRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PublishAPIService.ApiPublishPrefixDistributionSourcesPost")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/publish/{prefix}/{distribution}/sources"
	localVarPath = strings.Replace(localVarPath, "{"+"prefix"+"}", url.PathEscape(parameterValueToString(r.prefix, "prefix")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"distribution"+"}", url.PathEscape(parameterValueToString(r.distribution, "distribution")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.request == nil {
		return nil, reportError("request is required and must be specified")
	}

	if r.async != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "_async", r.async, "", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.request
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiApiPublishPrefixDistributionSourcesPutRequest struct {
	ctx context.Context
	ApiService *PublishAPIService
	prefix string
	distribution string
	request *[]ApiSourceParams
	async *bool
}

// Parameters
func (r ApiApiPublishPrefixDistributionSourcesPutRequest) Request(request []ApiSourceParams) ApiApiPublishPrefixDistributionSourcesPutRequest {
	r.request = &request
	return r
}

// Run in background and return task object
func (r ApiApiPublishPrefixDistributionSourcesPutRequest) Async(async bool) ApiApiPublishPrefixDistributionSourcesPutRequest {
	r.async = &async
	return r
}

func (r ApiApiPublishPrefixDistributionSourcesPutRequest) Execute() (*http.Response, error) {
	return r.ApiService.ApiPublishPrefixDistributionSourcesPutExecute(r)
}

/*
ApiPublishPrefixDistributionSourcesPut Replace Source Components

**Replace the source components of a published repository**

Sets the components of snapshots or local repositories to be published. Existing Sourced will be replaced.

This call does not publish the changes, but rather schedules them for a subsequent publish update call (i.e `PUT /api/publish/{prefix}/{distribution}` / `POST /api/publish/{prefix}/{distribution}/update`).

See also: `aptly publish source replace`

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param prefix publishing prefix
 @param distribution distribution name
 @return ApiApiPublishPrefixDistributionSourcesPutRequest
*/
func (a *PublishAPIService) ApiPublishPrefixDistributionSourcesPut(ctx context.Context, prefix string, distribution string) ApiApiPublishPrefixDistributionSourcesPutRequest {
	return ApiApiPublishPrefixDistributionSourcesPutRequest{
		ApiService: a,
		ctx: ctx,
		prefix: prefix,
		distribution: distribution,
	}
}

// Execute executes the request
func (a *PublishAPIService) ApiPublishPrefixDistributionSourcesPutExecute(r ApiApiPublishPrefixDistributionSourcesPutRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPut
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PublishAPIService.ApiPublishPrefixDistributionSourcesPut")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/publish/{prefix}/{distribution}/sources"
	localVarPath = strings.Replace(localVarPath, "{"+"prefix"+"}", url.PathEscape(parameterValueToString(r.prefix, "prefix")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"distribution"+"}", url.PathEscape(parameterValueToString(r.distribution, "distribution")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.request == nil {
		return nil, reportError("request is required and must be specified")
	}

	if r.async != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "_async", r.async, "", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.request
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiApiPublishPrefixDistributionUpdatePostRequest struct {
	ctx context.Context
	ApiService *PublishAPIService
	prefix string
	distribution string
	request *ApiPublishedRepoUpdateParams
	async *bool
}

// Parameters
func (r ApiApiPublishPrefixDistributionUpdatePostRequest) Request(request ApiPublishedRepoUpdateParams) ApiApiPublishPrefixDistributionUpdatePostRequest {
	r.request = &request
	return r
}

// Run in background and return task object
func (r ApiApiPublishPrefixDistributionUpdatePostRequest) Async(async bool) ApiApiPublishPrefixDistributionUpdatePostRequest {
	r.async = &async
	return r
}

func (r ApiApiPublishPrefixDistributionUpdatePostRequest) Execute() (*DebPublishedRepo, *http.Response, error) {
	return r.ApiService.ApiPublishPrefixDistributionUpdatePostExecute(r)
}

/*
ApiPublishPrefixDistributionUpdatePost Update Published Repository

**Update a published repository**

Publish pending source component changes which were added with `Add/Remove/Replace Source Components`

See also: `aptly publish update`

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param prefix publishing prefix
 @param distribution distribution name
 @return ApiApiPublishPrefixDistributionUpdatePostRequest
*/
func (a *PublishAPIService) ApiPublishPrefixDistributionUpdatePost(ctx context.Context, prefix string, distribution string) ApiApiPublishPrefixDistributionUpdatePostRequest {
	return ApiApiPublishPrefixDistributionUpdatePostRequest{
		ApiService: a,
		ctx: ctx,
		prefix: prefix,
		distribution: distribution,
	}
}

// Execute executes the request
//  @return DebPublishedRepo
func (a *PublishAPIService) ApiPublishPrefixDistributionUpdatePostExecute(r ApiApiPublishPrefixDistributionUpdatePostRequest) (*DebPublishedRepo, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *DebPublishedRepo
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PublishAPIService.ApiPublishPrefixDistributionUpdatePost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/publish/{prefix}/{distribution}/update"
	localVarPath = strings.Replace(localVarPath, "{"+"prefix"+"}", url.PathEscape(parameterValueToString(r.prefix, "prefix")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"distribution"+"}", url.PathEscape(parameterValueToString(r.distribution, "distribution")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.request == nil {
		return localVarReturnValue, nil, reportError("request is required and must be specified")
	}

	if r.async != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "_async", r.async, "", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.request
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiApiPublishPrefixPostRequest struct {
	ctx context.Context
	ApiService *PublishAPIService
	prefix string
	request *ApiPublishedRepoCreateParams
	async *bool
}

// Parameters
func (r ApiApiPublishPrefixPostRequest) Request(request ApiPublishedRepoCreateParams) ApiApiPublishPrefixPostRequest {
	r.request = &request
	return r
}

// Run in background and return task object
func (r ApiApiPublishPrefixPostRequest) Async(async bool) ApiApiPublishPrefixPostRequest {
	r.async = &async
	return r
}

func (r ApiApiPublishPrefixPostRequest) Execute() (*DebPublishedRepo, *http.Response, error) {
	return r.ApiService.ApiPublishPrefixPostExecute(r)
}

/*
ApiPublishPrefixPost Create Published Repository

**Publish a local repository or snapshot**

Create a published repository.

The prefix may contain a storage specifier, e.g. `s3:packages/`, or it may also be empty to publish to the root directory.

**Example:**
```
$ curl -X POST -H 'Content-Type: application/json' --data '{"Distribution": "wheezy", "Sources": [{"Name": "aptly-repo"}]}' http://localhost:8080/api/publish//repos
{"Architectures":["i386"],"Distribution":"wheezy","Label":"","Origin":"","Prefix":".","SourceKind":"local","Sources":[{"Component":"main","Name":"aptly-repo"}],"Storage":""}
```

See also: `aptly publish create`

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param prefix publishing prefix
 @return ApiApiPublishPrefixPostRequest
*/
func (a *PublishAPIService) ApiPublishPrefixPost(ctx context.Context, prefix string) ApiApiPublishPrefixPostRequest {
	return ApiApiPublishPrefixPostRequest{
		ApiService: a,
		ctx: ctx,
		prefix: prefix,
	}
}

// Execute executes the request
//  @return DebPublishedRepo
func (a *PublishAPIService) ApiPublishPrefixPostExecute(r ApiApiPublishPrefixPostRequest) (*DebPublishedRepo, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *DebPublishedRepo
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PublishAPIService.ApiPublishPrefixPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/publish/{prefix}"
	localVarPath = strings.Replace(localVarPath, "{"+"prefix"+"}", url.PathEscape(parameterValueToString(r.prefix, "prefix")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.request == nil {
		return localVarReturnValue, nil, reportError("request is required and must be specified")
	}

	if r.async != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "_async", r.async, "", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.request
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
