/*
Aptly API

Aptly operations are also available via REST API served with `aptly api serve`.  On Debian based systems, a package `aptly-api` is available, which will run aptly as systemd service as dedicated aptly-api user.  Some configuration changes (S3 publishing endpoints, ...) will require restarting the aptly service in order to take effect.  The REST API shouldn't be exposed to the Internet as there is no authentication/protection, consider using a HTTP proxy (e.g. nginx) to add https and authentication.  #### Aptly REST API Documentation 

API version: 1.6.2+20260308145521.8e943a3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aptly

import (
	"encoding/json"
)

// checks if the ApiSnapshotsUpdateParams type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiSnapshotsUpdateParams{}

// ApiSnapshotsUpdateParams struct for ApiSnapshotsUpdateParams
type ApiSnapshotsUpdateParams struct {
	// Change Description of snapshot
	Description *string `json:"Description,omitempty"`
	// Change Name of snapshot
	Name *string `json:"Name,omitempty"`
}

// NewApiSnapshotsUpdateParams instantiates a new ApiSnapshotsUpdateParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiSnapshotsUpdateParams() *ApiSnapshotsUpdateParams {
	this := ApiSnapshotsUpdateParams{}
	return &this
}

// NewApiSnapshotsUpdateParamsWithDefaults instantiates a new ApiSnapshotsUpdateParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiSnapshotsUpdateParamsWithDefaults() *ApiSnapshotsUpdateParams {
	this := ApiSnapshotsUpdateParams{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ApiSnapshotsUpdateParams) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiSnapshotsUpdateParams) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ApiSnapshotsUpdateParams) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ApiSnapshotsUpdateParams) SetDescription(v string) {
	o.Description = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ApiSnapshotsUpdateParams) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiSnapshotsUpdateParams) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ApiSnapshotsUpdateParams) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ApiSnapshotsUpdateParams) SetName(v string) {
	o.Name = &v
}

func (o ApiSnapshotsUpdateParams) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiSnapshotsUpdateParams) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Description) {
		toSerialize["Description"] = o.Description
	}
	if !IsNil(o.Name) {
		toSerialize["Name"] = o.Name
	}
	return toSerialize, nil
}

type NullableApiSnapshotsUpdateParams struct {
	value *ApiSnapshotsUpdateParams
	isSet bool
}

func (v NullableApiSnapshotsUpdateParams) Get() *ApiSnapshotsUpdateParams {
	return v.value
}

func (v *NullableApiSnapshotsUpdateParams) Set(val *ApiSnapshotsUpdateParams) {
	v.value = val
	v.isSet = true
}

func (v NullableApiSnapshotsUpdateParams) IsSet() bool {
	return v.isSet
}

func (v *NullableApiSnapshotsUpdateParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiSnapshotsUpdateParams(val *ApiSnapshotsUpdateParams) *NullableApiSnapshotsUpdateParams {
	return &NullableApiSnapshotsUpdateParams{value: val, isSet: true}
}

func (v NullableApiSnapshotsUpdateParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiSnapshotsUpdateParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


