/*
Aptly API

Aptly operations are also available via REST API served with `aptly api serve`.  On Debian based systems, a package `aptly-api` is available, which will run aptly as systemd service as dedicated aptly-api user.  Some configuration changes (S3 publishing endpoints, ...) will require restarting the aptly service in order to take effect.  The REST API shouldn't be exposed to the Internet as there is no authentication/protection, consider using a HTTP proxy (e.g. nginx) to add https and authentication.  #### Aptly REST API Documentation 

API version: 1.6.2+20260308145521.8e943a3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aptly

import (
	"encoding/json"
)

// checks if the DebPublishedRepo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DebPublishedRepo{}

// DebPublishedRepo struct for DebPublishedRepo
type DebPublishedRepo struct {
	// Provide index files per hash also
	AcquireByHash *bool `json:"AcquireByHash,omitempty"`
	// Architectures is a list of all architectures published
	Architectures []string `json:"Architectures,omitempty"`
	ButAutomaticUpgrades *string `json:"ButAutomaticUpgrades,omitempty"`
	Codename *string `json:"Codename,omitempty"`
	// Legacy fields for compatibility with old published repositories (< 0.6)
	Component *string `json:"Component,omitempty"`
	Distribution *string `json:"Distribution,omitempty"`
	Label *string `json:"Label,omitempty"`
	// Support multiple distributions
	MultiDist *bool `json:"MultiDist,omitempty"`
	NotAutomatic *string `json:"NotAutomatic,omitempty"`
	Origin *string `json:"Origin,omitempty"`
	Prefix *string `json:"Prefix,omitempty"`
	// Revision
	Revision *DebPublishedRepoRevision `json:"Revision,omitempty"`
	// An optional field containing a comma separated list of OpenPGP key fingerprints to be used for validating the next Release file
	SignedBy *string `json:"SignedBy,omitempty"`
	// Skip bz2 compression for index files
	SkipBz2 *bool `json:"SkipBz2,omitempty"`
	// Skip contents generation
	SkipContents *bool `json:"SkipContents,omitempty"`
	// SourceKind is \"local\"/\"repo\"
	SourceKind *string `json:"SourceKind,omitempty"`
	// SourceUUID is UUID of either snapshot or local repo
	SourceUUID *string `json:"SourceUUID,omitempty"`
	// Map of sources by each component: component name -> source UUID
	Sources *map[string]string `json:"Sources,omitempty"`
	// Storage & Prefix & distribution should be unique across all published repositories
	Storage *string `json:"Storage,omitempty"`
	Suite *string `json:"Suite,omitempty"`
	// Internal unique ID
	UUID *string `json:"UUID,omitempty"`
}

// NewDebPublishedRepo instantiates a new DebPublishedRepo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDebPublishedRepo() *DebPublishedRepo {
	this := DebPublishedRepo{}
	return &this
}

// NewDebPublishedRepoWithDefaults instantiates a new DebPublishedRepo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDebPublishedRepoWithDefaults() *DebPublishedRepo {
	this := DebPublishedRepo{}
	return &this
}

// GetAcquireByHash returns the AcquireByHash field value if set, zero value otherwise.
func (o *DebPublishedRepo) GetAcquireByHash() bool {
	if o == nil || IsNil(o.AcquireByHash) {
		var ret bool
		return ret
	}
	return *o.AcquireByHash
}

// GetAcquireByHashOk returns a tuple with the AcquireByHash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebPublishedRepo) GetAcquireByHashOk() (*bool, bool) {
	if o == nil || IsNil(o.AcquireByHash) {
		return nil, false
	}
	return o.AcquireByHash, true
}

// HasAcquireByHash returns a boolean if a field has been set.
func (o *DebPublishedRepo) HasAcquireByHash() bool {
	if o != nil && !IsNil(o.AcquireByHash) {
		return true
	}

	return false
}

// SetAcquireByHash gets a reference to the given bool and assigns it to the AcquireByHash field.
func (o *DebPublishedRepo) SetAcquireByHash(v bool) {
	o.AcquireByHash = &v
}

// GetArchitectures returns the Architectures field value if set, zero value otherwise.
func (o *DebPublishedRepo) GetArchitectures() []string {
	if o == nil || IsNil(o.Architectures) {
		var ret []string
		return ret
	}
	return o.Architectures
}

// GetArchitecturesOk returns a tuple with the Architectures field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebPublishedRepo) GetArchitecturesOk() ([]string, bool) {
	if o == nil || IsNil(o.Architectures) {
		return nil, false
	}
	return o.Architectures, true
}

// HasArchitectures returns a boolean if a field has been set.
func (o *DebPublishedRepo) HasArchitectures() bool {
	if o != nil && !IsNil(o.Architectures) {
		return true
	}

	return false
}

// SetArchitectures gets a reference to the given []string and assigns it to the Architectures field.
func (o *DebPublishedRepo) SetArchitectures(v []string) {
	o.Architectures = v
}

// GetButAutomaticUpgrades returns the ButAutomaticUpgrades field value if set, zero value otherwise.
func (o *DebPublishedRepo) GetButAutomaticUpgrades() string {
	if o == nil || IsNil(o.ButAutomaticUpgrades) {
		var ret string
		return ret
	}
	return *o.ButAutomaticUpgrades
}

// GetButAutomaticUpgradesOk returns a tuple with the ButAutomaticUpgrades field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebPublishedRepo) GetButAutomaticUpgradesOk() (*string, bool) {
	if o == nil || IsNil(o.ButAutomaticUpgrades) {
		return nil, false
	}
	return o.ButAutomaticUpgrades, true
}

// HasButAutomaticUpgrades returns a boolean if a field has been set.
func (o *DebPublishedRepo) HasButAutomaticUpgrades() bool {
	if o != nil && !IsNil(o.ButAutomaticUpgrades) {
		return true
	}

	return false
}

// SetButAutomaticUpgrades gets a reference to the given string and assigns it to the ButAutomaticUpgrades field.
func (o *DebPublishedRepo) SetButAutomaticUpgrades(v string) {
	o.ButAutomaticUpgrades = &v
}

// GetCodename returns the Codename field value if set, zero value otherwise.
func (o *DebPublishedRepo) GetCodename() string {
	if o == nil || IsNil(o.Codename) {
		var ret string
		return ret
	}
	return *o.Codename
}

// GetCodenameOk returns a tuple with the Codename field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebPublishedRepo) GetCodenameOk() (*string, bool) {
	if o == nil || IsNil(o.Codename) {
		return nil, false
	}
	return o.Codename, true
}

// HasCodename returns a boolean if a field has been set.
func (o *DebPublishedRepo) HasCodename() bool {
	if o != nil && !IsNil(o.Codename) {
		return true
	}

	return false
}

// SetCodename gets a reference to the given string and assigns it to the Codename field.
func (o *DebPublishedRepo) SetCodename(v string) {
	o.Codename = &v
}

// GetComponent returns the Component field value if set, zero value otherwise.
func (o *DebPublishedRepo) GetComponent() string {
	if o == nil || IsNil(o.Component) {
		var ret string
		return ret
	}
	return *o.Component
}

// GetComponentOk returns a tuple with the Component field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebPublishedRepo) GetComponentOk() (*string, bool) {
	if o == nil || IsNil(o.Component) {
		return nil, false
	}
	return o.Component, true
}

// HasComponent returns a boolean if a field has been set.
func (o *DebPublishedRepo) HasComponent() bool {
	if o != nil && !IsNil(o.Component) {
		return true
	}

	return false
}

// SetComponent gets a reference to the given string and assigns it to the Component field.
func (o *DebPublishedRepo) SetComponent(v string) {
	o.Component = &v
}

// GetDistribution returns the Distribution field value if set, zero value otherwise.
func (o *DebPublishedRepo) GetDistribution() string {
	if o == nil || IsNil(o.Distribution) {
		var ret string
		return ret
	}
	return *o.Distribution
}

// GetDistributionOk returns a tuple with the Distribution field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebPublishedRepo) GetDistributionOk() (*string, bool) {
	if o == nil || IsNil(o.Distribution) {
		return nil, false
	}
	return o.Distribution, true
}

// HasDistribution returns a boolean if a field has been set.
func (o *DebPublishedRepo) HasDistribution() bool {
	if o != nil && !IsNil(o.Distribution) {
		return true
	}

	return false
}

// SetDistribution gets a reference to the given string and assigns it to the Distribution field.
func (o *DebPublishedRepo) SetDistribution(v string) {
	o.Distribution = &v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *DebPublishedRepo) GetLabel() string {
	if o == nil || IsNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebPublishedRepo) GetLabelOk() (*string, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *DebPublishedRepo) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *DebPublishedRepo) SetLabel(v string) {
	o.Label = &v
}

// GetMultiDist returns the MultiDist field value if set, zero value otherwise.
func (o *DebPublishedRepo) GetMultiDist() bool {
	if o == nil || IsNil(o.MultiDist) {
		var ret bool
		return ret
	}
	return *o.MultiDist
}

// GetMultiDistOk returns a tuple with the MultiDist field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebPublishedRepo) GetMultiDistOk() (*bool, bool) {
	if o == nil || IsNil(o.MultiDist) {
		return nil, false
	}
	return o.MultiDist, true
}

// HasMultiDist returns a boolean if a field has been set.
func (o *DebPublishedRepo) HasMultiDist() bool {
	if o != nil && !IsNil(o.MultiDist) {
		return true
	}

	return false
}

// SetMultiDist gets a reference to the given bool and assigns it to the MultiDist field.
func (o *DebPublishedRepo) SetMultiDist(v bool) {
	o.MultiDist = &v
}

// GetNotAutomatic returns the NotAutomatic field value if set, zero value otherwise.
func (o *DebPublishedRepo) GetNotAutomatic() string {
	if o == nil || IsNil(o.NotAutomatic) {
		var ret string
		return ret
	}
	return *o.NotAutomatic
}

// GetNotAutomaticOk returns a tuple with the NotAutomatic field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebPublishedRepo) GetNotAutomaticOk() (*string, bool) {
	if o == nil || IsNil(o.NotAutomatic) {
		return nil, false
	}
	return o.NotAutomatic, true
}

// HasNotAutomatic returns a boolean if a field has been set.
func (o *DebPublishedRepo) HasNotAutomatic() bool {
	if o != nil && !IsNil(o.NotAutomatic) {
		return true
	}

	return false
}

// SetNotAutomatic gets a reference to the given string and assigns it to the NotAutomatic field.
func (o *DebPublishedRepo) SetNotAutomatic(v string) {
	o.NotAutomatic = &v
}

// GetOrigin returns the Origin field value if set, zero value otherwise.
func (o *DebPublishedRepo) GetOrigin() string {
	if o == nil || IsNil(o.Origin) {
		var ret string
		return ret
	}
	return *o.Origin
}

// GetOriginOk returns a tuple with the Origin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebPublishedRepo) GetOriginOk() (*string, bool) {
	if o == nil || IsNil(o.Origin) {
		return nil, false
	}
	return o.Origin, true
}

// HasOrigin returns a boolean if a field has been set.
func (o *DebPublishedRepo) HasOrigin() bool {
	if o != nil && !IsNil(o.Origin) {
		return true
	}

	return false
}

// SetOrigin gets a reference to the given string and assigns it to the Origin field.
func (o *DebPublishedRepo) SetOrigin(v string) {
	o.Origin = &v
}

// GetPrefix returns the Prefix field value if set, zero value otherwise.
func (o *DebPublishedRepo) GetPrefix() string {
	if o == nil || IsNil(o.Prefix) {
		var ret string
		return ret
	}
	return *o.Prefix
}

// GetPrefixOk returns a tuple with the Prefix field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebPublishedRepo) GetPrefixOk() (*string, bool) {
	if o == nil || IsNil(o.Prefix) {
		return nil, false
	}
	return o.Prefix, true
}

// HasPrefix returns a boolean if a field has been set.
func (o *DebPublishedRepo) HasPrefix() bool {
	if o != nil && !IsNil(o.Prefix) {
		return true
	}

	return false
}

// SetPrefix gets a reference to the given string and assigns it to the Prefix field.
func (o *DebPublishedRepo) SetPrefix(v string) {
	o.Prefix = &v
}

// GetRevision returns the Revision field value if set, zero value otherwise.
func (o *DebPublishedRepo) GetRevision() DebPublishedRepoRevision {
	if o == nil || IsNil(o.Revision) {
		var ret DebPublishedRepoRevision
		return ret
	}
	return *o.Revision
}

// GetRevisionOk returns a tuple with the Revision field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebPublishedRepo) GetRevisionOk() (*DebPublishedRepoRevision, bool) {
	if o == nil || IsNil(o.Revision) {
		return nil, false
	}
	return o.Revision, true
}

// HasRevision returns a boolean if a field has been set.
func (o *DebPublishedRepo) HasRevision() bool {
	if o != nil && !IsNil(o.Revision) {
		return true
	}

	return false
}

// SetRevision gets a reference to the given DebPublishedRepoRevision and assigns it to the Revision field.
func (o *DebPublishedRepo) SetRevision(v DebPublishedRepoRevision) {
	o.Revision = &v
}

// GetSignedBy returns the SignedBy field value if set, zero value otherwise.
func (o *DebPublishedRepo) GetSignedBy() string {
	if o == nil || IsNil(o.SignedBy) {
		var ret string
		return ret
	}
	return *o.SignedBy
}

// GetSignedByOk returns a tuple with the SignedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebPublishedRepo) GetSignedByOk() (*string, bool) {
	if o == nil || IsNil(o.SignedBy) {
		return nil, false
	}
	return o.SignedBy, true
}

// HasSignedBy returns a boolean if a field has been set.
func (o *DebPublishedRepo) HasSignedBy() bool {
	if o != nil && !IsNil(o.SignedBy) {
		return true
	}

	return false
}

// SetSignedBy gets a reference to the given string and assigns it to the SignedBy field.
func (o *DebPublishedRepo) SetSignedBy(v string) {
	o.SignedBy = &v
}

// GetSkipBz2 returns the SkipBz2 field value if set, zero value otherwise.
func (o *DebPublishedRepo) GetSkipBz2() bool {
	if o == nil || IsNil(o.SkipBz2) {
		var ret bool
		return ret
	}
	return *o.SkipBz2
}

// GetSkipBz2Ok returns a tuple with the SkipBz2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebPublishedRepo) GetSkipBz2Ok() (*bool, bool) {
	if o == nil || IsNil(o.SkipBz2) {
		return nil, false
	}
	return o.SkipBz2, true
}

// HasSkipBz2 returns a boolean if a field has been set.
func (o *DebPublishedRepo) HasSkipBz2() bool {
	if o != nil && !IsNil(o.SkipBz2) {
		return true
	}

	return false
}

// SetSkipBz2 gets a reference to the given bool and assigns it to the SkipBz2 field.
func (o *DebPublishedRepo) SetSkipBz2(v bool) {
	o.SkipBz2 = &v
}

// GetSkipContents returns the SkipContents field value if set, zero value otherwise.
func (o *DebPublishedRepo) GetSkipContents() bool {
	if o == nil || IsNil(o.SkipContents) {
		var ret bool
		return ret
	}
	return *o.SkipContents
}

// GetSkipContentsOk returns a tuple with the SkipContents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebPublishedRepo) GetSkipContentsOk() (*bool, bool) {
	if o == nil || IsNil(o.SkipContents) {
		return nil, false
	}
	return o.SkipContents, true
}

// HasSkipContents returns a boolean if a field has been set.
func (o *DebPublishedRepo) HasSkipContents() bool {
	if o != nil && !IsNil(o.SkipContents) {
		return true
	}

	return false
}

// SetSkipContents gets a reference to the given bool and assigns it to the SkipContents field.
func (o *DebPublishedRepo) SetSkipContents(v bool) {
	o.SkipContents = &v
}

// GetSourceKind returns the SourceKind field value if set, zero value otherwise.
func (o *DebPublishedRepo) GetSourceKind() string {
	if o == nil || IsNil(o.SourceKind) {
		var ret string
		return ret
	}
	return *o.SourceKind
}

// GetSourceKindOk returns a tuple with the SourceKind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebPublishedRepo) GetSourceKindOk() (*string, bool) {
	if o == nil || IsNil(o.SourceKind) {
		return nil, false
	}
	return o.SourceKind, true
}

// HasSourceKind returns a boolean if a field has been set.
func (o *DebPublishedRepo) HasSourceKind() bool {
	if o != nil && !IsNil(o.SourceKind) {
		return true
	}

	return false
}

// SetSourceKind gets a reference to the given string and assigns it to the SourceKind field.
func (o *DebPublishedRepo) SetSourceKind(v string) {
	o.SourceKind = &v
}

// GetSourceUUID returns the SourceUUID field value if set, zero value otherwise.
func (o *DebPublishedRepo) GetSourceUUID() string {
	if o == nil || IsNil(o.SourceUUID) {
		var ret string
		return ret
	}
	return *o.SourceUUID
}

// GetSourceUUIDOk returns a tuple with the SourceUUID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebPublishedRepo) GetSourceUUIDOk() (*string, bool) {
	if o == nil || IsNil(o.SourceUUID) {
		return nil, false
	}
	return o.SourceUUID, true
}

// HasSourceUUID returns a boolean if a field has been set.
func (o *DebPublishedRepo) HasSourceUUID() bool {
	if o != nil && !IsNil(o.SourceUUID) {
		return true
	}

	return false
}

// SetSourceUUID gets a reference to the given string and assigns it to the SourceUUID field.
func (o *DebPublishedRepo) SetSourceUUID(v string) {
	o.SourceUUID = &v
}

// GetSources returns the Sources field value if set, zero value otherwise.
func (o *DebPublishedRepo) GetSources() map[string]string {
	if o == nil || IsNil(o.Sources) {
		var ret map[string]string
		return ret
	}
	return *o.Sources
}

// GetSourcesOk returns a tuple with the Sources field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebPublishedRepo) GetSourcesOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Sources) {
		return nil, false
	}
	return o.Sources, true
}

// HasSources returns a boolean if a field has been set.
func (o *DebPublishedRepo) HasSources() bool {
	if o != nil && !IsNil(o.Sources) {
		return true
	}

	return false
}

// SetSources gets a reference to the given map[string]string and assigns it to the Sources field.
func (o *DebPublishedRepo) SetSources(v map[string]string) {
	o.Sources = &v
}

// GetStorage returns the Storage field value if set, zero value otherwise.
func (o *DebPublishedRepo) GetStorage() string {
	if o == nil || IsNil(o.Storage) {
		var ret string
		return ret
	}
	return *o.Storage
}

// GetStorageOk returns a tuple with the Storage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebPublishedRepo) GetStorageOk() (*string, bool) {
	if o == nil || IsNil(o.Storage) {
		return nil, false
	}
	return o.Storage, true
}

// HasStorage returns a boolean if a field has been set.
func (o *DebPublishedRepo) HasStorage() bool {
	if o != nil && !IsNil(o.Storage) {
		return true
	}

	return false
}

// SetStorage gets a reference to the given string and assigns it to the Storage field.
func (o *DebPublishedRepo) SetStorage(v string) {
	o.Storage = &v
}

// GetSuite returns the Suite field value if set, zero value otherwise.
func (o *DebPublishedRepo) GetSuite() string {
	if o == nil || IsNil(o.Suite) {
		var ret string
		return ret
	}
	return *o.Suite
}

// GetSuiteOk returns a tuple with the Suite field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebPublishedRepo) GetSuiteOk() (*string, bool) {
	if o == nil || IsNil(o.Suite) {
		return nil, false
	}
	return o.Suite, true
}

// HasSuite returns a boolean if a field has been set.
func (o *DebPublishedRepo) HasSuite() bool {
	if o != nil && !IsNil(o.Suite) {
		return true
	}

	return false
}

// SetSuite gets a reference to the given string and assigns it to the Suite field.
func (o *DebPublishedRepo) SetSuite(v string) {
	o.Suite = &v
}

// GetUUID returns the UUID field value if set, zero value otherwise.
func (o *DebPublishedRepo) GetUUID() string {
	if o == nil || IsNil(o.UUID) {
		var ret string
		return ret
	}
	return *o.UUID
}

// GetUUIDOk returns a tuple with the UUID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebPublishedRepo) GetUUIDOk() (*string, bool) {
	if o == nil || IsNil(o.UUID) {
		return nil, false
	}
	return o.UUID, true
}

// HasUUID returns a boolean if a field has been set.
func (o *DebPublishedRepo) HasUUID() bool {
	if o != nil && !IsNil(o.UUID) {
		return true
	}

	return false
}

// SetUUID gets a reference to the given string and assigns it to the UUID field.
func (o *DebPublishedRepo) SetUUID(v string) {
	o.UUID = &v
}

func (o DebPublishedRepo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DebPublishedRepo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AcquireByHash) {
		toSerialize["AcquireByHash"] = o.AcquireByHash
	}
	if !IsNil(o.Architectures) {
		toSerialize["Architectures"] = o.Architectures
	}
	if !IsNil(o.ButAutomaticUpgrades) {
		toSerialize["ButAutomaticUpgrades"] = o.ButAutomaticUpgrades
	}
	if !IsNil(o.Codename) {
		toSerialize["Codename"] = o.Codename
	}
	if !IsNil(o.Component) {
		toSerialize["Component"] = o.Component
	}
	if !IsNil(o.Distribution) {
		toSerialize["Distribution"] = o.Distribution
	}
	if !IsNil(o.Label) {
		toSerialize["Label"] = o.Label
	}
	if !IsNil(o.MultiDist) {
		toSerialize["MultiDist"] = o.MultiDist
	}
	if !IsNil(o.NotAutomatic) {
		toSerialize["NotAutomatic"] = o.NotAutomatic
	}
	if !IsNil(o.Origin) {
		toSerialize["Origin"] = o.Origin
	}
	if !IsNil(o.Prefix) {
		toSerialize["Prefix"] = o.Prefix
	}
	if !IsNil(o.Revision) {
		toSerialize["Revision"] = o.Revision
	}
	if !IsNil(o.SignedBy) {
		toSerialize["SignedBy"] = o.SignedBy
	}
	if !IsNil(o.SkipBz2) {
		toSerialize["SkipBz2"] = o.SkipBz2
	}
	if !IsNil(o.SkipContents) {
		toSerialize["SkipContents"] = o.SkipContents
	}
	if !IsNil(o.SourceKind) {
		toSerialize["SourceKind"] = o.SourceKind
	}
	if !IsNil(o.SourceUUID) {
		toSerialize["SourceUUID"] = o.SourceUUID
	}
	if !IsNil(o.Sources) {
		toSerialize["Sources"] = o.Sources
	}
	if !IsNil(o.Storage) {
		toSerialize["Storage"] = o.Storage
	}
	if !IsNil(o.Suite) {
		toSerialize["Suite"] = o.Suite
	}
	if !IsNil(o.UUID) {
		toSerialize["UUID"] = o.UUID
	}
	return toSerialize, nil
}

type NullableDebPublishedRepo struct {
	value *DebPublishedRepo
	isSet bool
}

func (v NullableDebPublishedRepo) Get() *DebPublishedRepo {
	return v.value
}

func (v *NullableDebPublishedRepo) Set(val *DebPublishedRepo) {
	v.value = val
	v.isSet = true
}

func (v NullableDebPublishedRepo) IsSet() bool {
	return v.isSet
}

func (v *NullableDebPublishedRepo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDebPublishedRepo(val *DebPublishedRepo) *NullableDebPublishedRepo {
	return &NullableDebPublishedRepo{value: val, isSet: true}
}

func (v NullableDebPublishedRepo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDebPublishedRepo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


