/*
Aptly API

Aptly operations are also available via REST API served with `aptly api serve`.  On Debian based systems, a package `aptly-api` is available, which will run aptly as systemd service as dedicated aptly-api user.  Some configuration changes (S3 publishing endpoints, ...) will require restarting the aptly service in order to take effect.  The REST API shouldn't be exposed to the Internet as there is no authentication/protection, consider using a HTTP proxy (e.g. nginx) to add https and authentication.  #### Aptly REST API Documentation 

API version: 1.6.2+20260315225119.eb0ae3a
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aptly

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiRepoCreateParams type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiRepoCreateParams{}

// ApiRepoCreateParams struct for ApiRepoCreateParams
type ApiRepoCreateParams struct {
	// Text describing the repository (optional)
	Comment *string `json:"Comment,omitempty"`
	// Default component when publishing from this local repo
	DefaultComponent *string `json:"DefaultComponent,omitempty"`
	// Default distribution when publishing from this local repo
	DefaultDistribution *string `json:"DefaultDistribution,omitempty"`
	// Snapshot name to create repoitory from (optional)
	FromSnapshot *string `json:"FromSnapshot,omitempty"`
	// Name of repository to create
	Name string `json:"Name"`
}

type _ApiRepoCreateParams ApiRepoCreateParams

// NewApiRepoCreateParams instantiates a new ApiRepoCreateParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiRepoCreateParams(name string) *ApiRepoCreateParams {
	this := ApiRepoCreateParams{}
	this.Name = name
	return &this
}

// NewApiRepoCreateParamsWithDefaults instantiates a new ApiRepoCreateParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiRepoCreateParamsWithDefaults() *ApiRepoCreateParams {
	this := ApiRepoCreateParams{}
	return &this
}

// GetComment returns the Comment field value if set, zero value otherwise.
func (o *ApiRepoCreateParams) GetComment() string {
	if o == nil || IsNil(o.Comment) {
		var ret string
		return ret
	}
	return *o.Comment
}

// GetCommentOk returns a tuple with the Comment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiRepoCreateParams) GetCommentOk() (*string, bool) {
	if o == nil || IsNil(o.Comment) {
		return nil, false
	}
	return o.Comment, true
}

// HasComment returns a boolean if a field has been set.
func (o *ApiRepoCreateParams) HasComment() bool {
	if o != nil && !IsNil(o.Comment) {
		return true
	}

	return false
}

// SetComment gets a reference to the given string and assigns it to the Comment field.
func (o *ApiRepoCreateParams) SetComment(v string) {
	o.Comment = &v
}

// GetDefaultComponent returns the DefaultComponent field value if set, zero value otherwise.
func (o *ApiRepoCreateParams) GetDefaultComponent() string {
	if o == nil || IsNil(o.DefaultComponent) {
		var ret string
		return ret
	}
	return *o.DefaultComponent
}

// GetDefaultComponentOk returns a tuple with the DefaultComponent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiRepoCreateParams) GetDefaultComponentOk() (*string, bool) {
	if o == nil || IsNil(o.DefaultComponent) {
		return nil, false
	}
	return o.DefaultComponent, true
}

// HasDefaultComponent returns a boolean if a field has been set.
func (o *ApiRepoCreateParams) HasDefaultComponent() bool {
	if o != nil && !IsNil(o.DefaultComponent) {
		return true
	}

	return false
}

// SetDefaultComponent gets a reference to the given string and assigns it to the DefaultComponent field.
func (o *ApiRepoCreateParams) SetDefaultComponent(v string) {
	o.DefaultComponent = &v
}

// GetDefaultDistribution returns the DefaultDistribution field value if set, zero value otherwise.
func (o *ApiRepoCreateParams) GetDefaultDistribution() string {
	if o == nil || IsNil(o.DefaultDistribution) {
		var ret string
		return ret
	}
	return *o.DefaultDistribution
}

// GetDefaultDistributionOk returns a tuple with the DefaultDistribution field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiRepoCreateParams) GetDefaultDistributionOk() (*string, bool) {
	if o == nil || IsNil(o.DefaultDistribution) {
		return nil, false
	}
	return o.DefaultDistribution, true
}

// HasDefaultDistribution returns a boolean if a field has been set.
func (o *ApiRepoCreateParams) HasDefaultDistribution() bool {
	if o != nil && !IsNil(o.DefaultDistribution) {
		return true
	}

	return false
}

// SetDefaultDistribution gets a reference to the given string and assigns it to the DefaultDistribution field.
func (o *ApiRepoCreateParams) SetDefaultDistribution(v string) {
	o.DefaultDistribution = &v
}

// GetFromSnapshot returns the FromSnapshot field value if set, zero value otherwise.
func (o *ApiRepoCreateParams) GetFromSnapshot() string {
	if o == nil || IsNil(o.FromSnapshot) {
		var ret string
		return ret
	}
	return *o.FromSnapshot
}

// GetFromSnapshotOk returns a tuple with the FromSnapshot field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiRepoCreateParams) GetFromSnapshotOk() (*string, bool) {
	if o == nil || IsNil(o.FromSnapshot) {
		return nil, false
	}
	return o.FromSnapshot, true
}

// HasFromSnapshot returns a boolean if a field has been set.
func (o *ApiRepoCreateParams) HasFromSnapshot() bool {
	if o != nil && !IsNil(o.FromSnapshot) {
		return true
	}

	return false
}

// SetFromSnapshot gets a reference to the given string and assigns it to the FromSnapshot field.
func (o *ApiRepoCreateParams) SetFromSnapshot(v string) {
	o.FromSnapshot = &v
}

// GetName returns the Name field value
func (o *ApiRepoCreateParams) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ApiRepoCreateParams) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ApiRepoCreateParams) SetName(v string) {
	o.Name = v
}

func (o ApiRepoCreateParams) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiRepoCreateParams) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Comment) {
		toSerialize["Comment"] = o.Comment
	}
	if !IsNil(o.DefaultComponent) {
		toSerialize["DefaultComponent"] = o.DefaultComponent
	}
	if !IsNil(o.DefaultDistribution) {
		toSerialize["DefaultDistribution"] = o.DefaultDistribution
	}
	if !IsNil(o.FromSnapshot) {
		toSerialize["FromSnapshot"] = o.FromSnapshot
	}
	toSerialize["Name"] = o.Name
	return toSerialize, nil
}

func (o *ApiRepoCreateParams) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"Name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiRepoCreateParams := _ApiRepoCreateParams{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiRepoCreateParams)

	if err != nil {
		return err
	}

	*o = ApiRepoCreateParams(varApiRepoCreateParams)

	return err
}

type NullableApiRepoCreateParams struct {
	value *ApiRepoCreateParams
	isSet bool
}

func (v NullableApiRepoCreateParams) Get() *ApiRepoCreateParams {
	return v.value
}

func (v *NullableApiRepoCreateParams) Set(val *ApiRepoCreateParams) {
	v.value = val
	v.isSet = true
}

func (v NullableApiRepoCreateParams) IsSet() bool {
	return v.isSet
}

func (v *NullableApiRepoCreateParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiRepoCreateParams(val *ApiRepoCreateParams) *NullableApiRepoCreateParams {
	return &NullableApiRepoCreateParams{value: val, isSet: true}
}

func (v NullableApiRepoCreateParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiRepoCreateParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


