/*
Aptly API

Aptly operations are also available via REST API served with `aptly api serve`.  On Debian based systems, a package `aptly-api` is available, which will run aptly as systemd service as dedicated aptly-api user.  Some configuration changes (S3 publishing endpoints, ...) will require restarting the aptly service in order to take effect.  The REST API shouldn't be exposed to the Internet as there is no authentication/protection, consider using a HTTP proxy (e.g. nginx) to add https and authentication.  #### Aptly REST API Documentation 

API version: 1.6.2+20260228114657.9defe70
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aptly

import (
	"encoding/json"
)

// checks if the ApiPublishedRepoUpdateSwitchParams type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiPublishedRepoUpdateSwitchParams{}

// ApiPublishedRepoUpdateSwitchParams struct for ApiPublishedRepoUpdateSwitchParams
type ApiPublishedRepoUpdateSwitchParams struct {
	// Provide index files by hash
	AcquireByHash *bool `json:"AcquireByHash,omitempty"`
	// when publishing, overwrite files in pool/ directory without notice
	ForceOverwrite *bool `json:"ForceOverwrite,omitempty"`
	// Value of Label: field in published repository stanza
	Label *string `json:"Label,omitempty"`
	// Enable multiple packages with the same filename in different distributions
	MultiDist *bool `json:"MultiDist,omitempty"`
	// Value of Origin: field in published repository stanza
	Origin *string `json:"Origin,omitempty"`
	// An optional field containing a comma separated list of OpenPGP key fingerprints to be used for validating the next Release file
	SignedBy *string `json:"SignedBy,omitempty"`
	// GPG options
	Signing *ApiSigningParams `json:"Signing,omitempty"`
	// Skip bz2 compression for index files
	SkipBz2 *bool `json:"SkipBz2,omitempty"`
	// Don't remove unreferenced files in prefix/component
	SkipCleanup *bool `json:"SkipCleanup,omitempty"`
	// Don't generate contents indexes
	SkipContents *bool `json:"SkipContents,omitempty"`
	// only when updating published snapshots, list of objects 'Component/Name'
	Snapshots []ApiSourceParams `json:"Snapshots,omitempty"`
}

// NewApiPublishedRepoUpdateSwitchParams instantiates a new ApiPublishedRepoUpdateSwitchParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiPublishedRepoUpdateSwitchParams() *ApiPublishedRepoUpdateSwitchParams {
	this := ApiPublishedRepoUpdateSwitchParams{}
	return &this
}

// NewApiPublishedRepoUpdateSwitchParamsWithDefaults instantiates a new ApiPublishedRepoUpdateSwitchParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiPublishedRepoUpdateSwitchParamsWithDefaults() *ApiPublishedRepoUpdateSwitchParams {
	this := ApiPublishedRepoUpdateSwitchParams{}
	return &this
}

// GetAcquireByHash returns the AcquireByHash field value if set, zero value otherwise.
func (o *ApiPublishedRepoUpdateSwitchParams) GetAcquireByHash() bool {
	if o == nil || IsNil(o.AcquireByHash) {
		var ret bool
		return ret
	}
	return *o.AcquireByHash
}

// GetAcquireByHashOk returns a tuple with the AcquireByHash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiPublishedRepoUpdateSwitchParams) GetAcquireByHashOk() (*bool, bool) {
	if o == nil || IsNil(o.AcquireByHash) {
		return nil, false
	}
	return o.AcquireByHash, true
}

// HasAcquireByHash returns a boolean if a field has been set.
func (o *ApiPublishedRepoUpdateSwitchParams) HasAcquireByHash() bool {
	if o != nil && !IsNil(o.AcquireByHash) {
		return true
	}

	return false
}

// SetAcquireByHash gets a reference to the given bool and assigns it to the AcquireByHash field.
func (o *ApiPublishedRepoUpdateSwitchParams) SetAcquireByHash(v bool) {
	o.AcquireByHash = &v
}

// GetForceOverwrite returns the ForceOverwrite field value if set, zero value otherwise.
func (o *ApiPublishedRepoUpdateSwitchParams) GetForceOverwrite() bool {
	if o == nil || IsNil(o.ForceOverwrite) {
		var ret bool
		return ret
	}
	return *o.ForceOverwrite
}

// GetForceOverwriteOk returns a tuple with the ForceOverwrite field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiPublishedRepoUpdateSwitchParams) GetForceOverwriteOk() (*bool, bool) {
	if o == nil || IsNil(o.ForceOverwrite) {
		return nil, false
	}
	return o.ForceOverwrite, true
}

// HasForceOverwrite returns a boolean if a field has been set.
func (o *ApiPublishedRepoUpdateSwitchParams) HasForceOverwrite() bool {
	if o != nil && !IsNil(o.ForceOverwrite) {
		return true
	}

	return false
}

// SetForceOverwrite gets a reference to the given bool and assigns it to the ForceOverwrite field.
func (o *ApiPublishedRepoUpdateSwitchParams) SetForceOverwrite(v bool) {
	o.ForceOverwrite = &v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *ApiPublishedRepoUpdateSwitchParams) GetLabel() string {
	if o == nil || IsNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiPublishedRepoUpdateSwitchParams) GetLabelOk() (*string, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *ApiPublishedRepoUpdateSwitchParams) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *ApiPublishedRepoUpdateSwitchParams) SetLabel(v string) {
	o.Label = &v
}

// GetMultiDist returns the MultiDist field value if set, zero value otherwise.
func (o *ApiPublishedRepoUpdateSwitchParams) GetMultiDist() bool {
	if o == nil || IsNil(o.MultiDist) {
		var ret bool
		return ret
	}
	return *o.MultiDist
}

// GetMultiDistOk returns a tuple with the MultiDist field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiPublishedRepoUpdateSwitchParams) GetMultiDistOk() (*bool, bool) {
	if o == nil || IsNil(o.MultiDist) {
		return nil, false
	}
	return o.MultiDist, true
}

// HasMultiDist returns a boolean if a field has been set.
func (o *ApiPublishedRepoUpdateSwitchParams) HasMultiDist() bool {
	if o != nil && !IsNil(o.MultiDist) {
		return true
	}

	return false
}

// SetMultiDist gets a reference to the given bool and assigns it to the MultiDist field.
func (o *ApiPublishedRepoUpdateSwitchParams) SetMultiDist(v bool) {
	o.MultiDist = &v
}

// GetOrigin returns the Origin field value if set, zero value otherwise.
func (o *ApiPublishedRepoUpdateSwitchParams) GetOrigin() string {
	if o == nil || IsNil(o.Origin) {
		var ret string
		return ret
	}
	return *o.Origin
}

// GetOriginOk returns a tuple with the Origin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiPublishedRepoUpdateSwitchParams) GetOriginOk() (*string, bool) {
	if o == nil || IsNil(o.Origin) {
		return nil, false
	}
	return o.Origin, true
}

// HasOrigin returns a boolean if a field has been set.
func (o *ApiPublishedRepoUpdateSwitchParams) HasOrigin() bool {
	if o != nil && !IsNil(o.Origin) {
		return true
	}

	return false
}

// SetOrigin gets a reference to the given string and assigns it to the Origin field.
func (o *ApiPublishedRepoUpdateSwitchParams) SetOrigin(v string) {
	o.Origin = &v
}

// GetSignedBy returns the SignedBy field value if set, zero value otherwise.
func (o *ApiPublishedRepoUpdateSwitchParams) GetSignedBy() string {
	if o == nil || IsNil(o.SignedBy) {
		var ret string
		return ret
	}
	return *o.SignedBy
}

// GetSignedByOk returns a tuple with the SignedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiPublishedRepoUpdateSwitchParams) GetSignedByOk() (*string, bool) {
	if o == nil || IsNil(o.SignedBy) {
		return nil, false
	}
	return o.SignedBy, true
}

// HasSignedBy returns a boolean if a field has been set.
func (o *ApiPublishedRepoUpdateSwitchParams) HasSignedBy() bool {
	if o != nil && !IsNil(o.SignedBy) {
		return true
	}

	return false
}

// SetSignedBy gets a reference to the given string and assigns it to the SignedBy field.
func (o *ApiPublishedRepoUpdateSwitchParams) SetSignedBy(v string) {
	o.SignedBy = &v
}

// GetSigning returns the Signing field value if set, zero value otherwise.
func (o *ApiPublishedRepoUpdateSwitchParams) GetSigning() ApiSigningParams {
	if o == nil || IsNil(o.Signing) {
		var ret ApiSigningParams
		return ret
	}
	return *o.Signing
}

// GetSigningOk returns a tuple with the Signing field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiPublishedRepoUpdateSwitchParams) GetSigningOk() (*ApiSigningParams, bool) {
	if o == nil || IsNil(o.Signing) {
		return nil, false
	}
	return o.Signing, true
}

// HasSigning returns a boolean if a field has been set.
func (o *ApiPublishedRepoUpdateSwitchParams) HasSigning() bool {
	if o != nil && !IsNil(o.Signing) {
		return true
	}

	return false
}

// SetSigning gets a reference to the given ApiSigningParams and assigns it to the Signing field.
func (o *ApiPublishedRepoUpdateSwitchParams) SetSigning(v ApiSigningParams) {
	o.Signing = &v
}

// GetSkipBz2 returns the SkipBz2 field value if set, zero value otherwise.
func (o *ApiPublishedRepoUpdateSwitchParams) GetSkipBz2() bool {
	if o == nil || IsNil(o.SkipBz2) {
		var ret bool
		return ret
	}
	return *o.SkipBz2
}

// GetSkipBz2Ok returns a tuple with the SkipBz2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiPublishedRepoUpdateSwitchParams) GetSkipBz2Ok() (*bool, bool) {
	if o == nil || IsNil(o.SkipBz2) {
		return nil, false
	}
	return o.SkipBz2, true
}

// HasSkipBz2 returns a boolean if a field has been set.
func (o *ApiPublishedRepoUpdateSwitchParams) HasSkipBz2() bool {
	if o != nil && !IsNil(o.SkipBz2) {
		return true
	}

	return false
}

// SetSkipBz2 gets a reference to the given bool and assigns it to the SkipBz2 field.
func (o *ApiPublishedRepoUpdateSwitchParams) SetSkipBz2(v bool) {
	o.SkipBz2 = &v
}

// GetSkipCleanup returns the SkipCleanup field value if set, zero value otherwise.
func (o *ApiPublishedRepoUpdateSwitchParams) GetSkipCleanup() bool {
	if o == nil || IsNil(o.SkipCleanup) {
		var ret bool
		return ret
	}
	return *o.SkipCleanup
}

// GetSkipCleanupOk returns a tuple with the SkipCleanup field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiPublishedRepoUpdateSwitchParams) GetSkipCleanupOk() (*bool, bool) {
	if o == nil || IsNil(o.SkipCleanup) {
		return nil, false
	}
	return o.SkipCleanup, true
}

// HasSkipCleanup returns a boolean if a field has been set.
func (o *ApiPublishedRepoUpdateSwitchParams) HasSkipCleanup() bool {
	if o != nil && !IsNil(o.SkipCleanup) {
		return true
	}

	return false
}

// SetSkipCleanup gets a reference to the given bool and assigns it to the SkipCleanup field.
func (o *ApiPublishedRepoUpdateSwitchParams) SetSkipCleanup(v bool) {
	o.SkipCleanup = &v
}

// GetSkipContents returns the SkipContents field value if set, zero value otherwise.
func (o *ApiPublishedRepoUpdateSwitchParams) GetSkipContents() bool {
	if o == nil || IsNil(o.SkipContents) {
		var ret bool
		return ret
	}
	return *o.SkipContents
}

// GetSkipContentsOk returns a tuple with the SkipContents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiPublishedRepoUpdateSwitchParams) GetSkipContentsOk() (*bool, bool) {
	if o == nil || IsNil(o.SkipContents) {
		return nil, false
	}
	return o.SkipContents, true
}

// HasSkipContents returns a boolean if a field has been set.
func (o *ApiPublishedRepoUpdateSwitchParams) HasSkipContents() bool {
	if o != nil && !IsNil(o.SkipContents) {
		return true
	}

	return false
}

// SetSkipContents gets a reference to the given bool and assigns it to the SkipContents field.
func (o *ApiPublishedRepoUpdateSwitchParams) SetSkipContents(v bool) {
	o.SkipContents = &v
}

// GetSnapshots returns the Snapshots field value if set, zero value otherwise.
func (o *ApiPublishedRepoUpdateSwitchParams) GetSnapshots() []ApiSourceParams {
	if o == nil || IsNil(o.Snapshots) {
		var ret []ApiSourceParams
		return ret
	}
	return o.Snapshots
}

// GetSnapshotsOk returns a tuple with the Snapshots field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiPublishedRepoUpdateSwitchParams) GetSnapshotsOk() ([]ApiSourceParams, bool) {
	if o == nil || IsNil(o.Snapshots) {
		return nil, false
	}
	return o.Snapshots, true
}

// HasSnapshots returns a boolean if a field has been set.
func (o *ApiPublishedRepoUpdateSwitchParams) HasSnapshots() bool {
	if o != nil && !IsNil(o.Snapshots) {
		return true
	}

	return false
}

// SetSnapshots gets a reference to the given []ApiSourceParams and assigns it to the Snapshots field.
func (o *ApiPublishedRepoUpdateSwitchParams) SetSnapshots(v []ApiSourceParams) {
	o.Snapshots = v
}

func (o ApiPublishedRepoUpdateSwitchParams) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiPublishedRepoUpdateSwitchParams) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AcquireByHash) {
		toSerialize["AcquireByHash"] = o.AcquireByHash
	}
	if !IsNil(o.ForceOverwrite) {
		toSerialize["ForceOverwrite"] = o.ForceOverwrite
	}
	if !IsNil(o.Label) {
		toSerialize["Label"] = o.Label
	}
	if !IsNil(o.MultiDist) {
		toSerialize["MultiDist"] = o.MultiDist
	}
	if !IsNil(o.Origin) {
		toSerialize["Origin"] = o.Origin
	}
	if !IsNil(o.SignedBy) {
		toSerialize["SignedBy"] = o.SignedBy
	}
	if !IsNil(o.Signing) {
		toSerialize["Signing"] = o.Signing
	}
	if !IsNil(o.SkipBz2) {
		toSerialize["SkipBz2"] = o.SkipBz2
	}
	if !IsNil(o.SkipCleanup) {
		toSerialize["SkipCleanup"] = o.SkipCleanup
	}
	if !IsNil(o.SkipContents) {
		toSerialize["SkipContents"] = o.SkipContents
	}
	if !IsNil(o.Snapshots) {
		toSerialize["Snapshots"] = o.Snapshots
	}
	return toSerialize, nil
}

type NullableApiPublishedRepoUpdateSwitchParams struct {
	value *ApiPublishedRepoUpdateSwitchParams
	isSet bool
}

func (v NullableApiPublishedRepoUpdateSwitchParams) Get() *ApiPublishedRepoUpdateSwitchParams {
	return v.value
}

func (v *NullableApiPublishedRepoUpdateSwitchParams) Set(val *ApiPublishedRepoUpdateSwitchParams) {
	v.value = val
	v.isSet = true
}

func (v NullableApiPublishedRepoUpdateSwitchParams) IsSet() bool {
	return v.isSet
}

func (v *NullableApiPublishedRepoUpdateSwitchParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiPublishedRepoUpdateSwitchParams(val *ApiPublishedRepoUpdateSwitchParams) *NullableApiPublishedRepoUpdateSwitchParams {
	return &NullableApiPublishedRepoUpdateSwitchParams{value: val, isSet: true}
}

func (v NullableApiPublishedRepoUpdateSwitchParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiPublishedRepoUpdateSwitchParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


