/*
Aptly API

Aptly operations are also available via REST API served with `aptly api serve`.  On Debian based systems, a package `aptly-api` is available, which will run aptly as systemd service as dedicated aptly-api user.  Some configuration changes (S3 publishing endpoints, ...) will require restarting the aptly service in order to take effect.  The REST API shouldn't be exposed to the Internet as there is no authentication/protection, consider using a HTTP proxy (e.g. nginx) to add https and authentication.  #### Aptly REST API Documentation 

API version: 1.6.2+20260308145521.8e943a3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aptly

import (
	"encoding/json"
)

// checks if the DebRemoteRepo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DebRemoteRepo{}

// DebRemoteRepo struct for DebRemoteRepo
type DebRemoteRepo struct {
	// List of architectures to fetch, if empty, then fetch all architectures
	Architectures []string `json:"Architectures,omitempty"`
	// Root of Debian archive, URL
	ArchiveRoot *string `json:"ArchiveRoot,omitempty"`
	// List of components to fetch, if empty, then fetch all components
	Components []string `json:"Components,omitempty"`
	// Distribution name, e.g. squeeze
	Distribution *string `json:"Distribution,omitempty"`
	// Should we download installer files?
	DownloadInstaller *bool `json:"DownloadInstaller,omitempty"`
	// Should we download sources?
	DownloadSources *bool `json:"DownloadSources,omitempty"`
	// Should we download .udebs?
	DownloadUdebs *bool `json:"DownloadUdebs,omitempty"`
	// Filter for packages
	Filter *string `json:"Filter,omitempty"`
	// FilterWithDeps to include dependencies from filter query
	FilterWithDeps *bool `json:"FilterWithDeps,omitempty"`
	// Last update date
	LastDownloadDate *string `json:"LastDownloadDate,omitempty"`
	// Meta-information about repository
	Meta *map[string]string `json:"Meta,omitempty"`
	// User-assigned name
	Name *string `json:"Name,omitempty"`
	// Packages for json output
	Packages []string `json:"Packages,omitempty"`
	// SkipArchitectureCheck skips architecture list verification
	SkipArchitectureCheck *bool `json:"SkipArchitectureCheck,omitempty"`
	// SkipComponentCheck skips component list verification
	SkipComponentCheck *bool `json:"SkipComponentCheck,omitempty"`
	// Status marks state of repository (being updated, no action)
	Status *int32 `json:"Status,omitempty"`
	// Permanent internal ID
	UUID *string `json:"UUID,omitempty"`
	// WorkerPID is PID of the process modifying the mirror (if any)
	WorkerPID *int32 `json:"WorkerPID,omitempty"`
}

// NewDebRemoteRepo instantiates a new DebRemoteRepo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDebRemoteRepo() *DebRemoteRepo {
	this := DebRemoteRepo{}
	return &this
}

// NewDebRemoteRepoWithDefaults instantiates a new DebRemoteRepo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDebRemoteRepoWithDefaults() *DebRemoteRepo {
	this := DebRemoteRepo{}
	return &this
}

// GetArchitectures returns the Architectures field value if set, zero value otherwise.
func (o *DebRemoteRepo) GetArchitectures() []string {
	if o == nil || IsNil(o.Architectures) {
		var ret []string
		return ret
	}
	return o.Architectures
}

// GetArchitecturesOk returns a tuple with the Architectures field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebRemoteRepo) GetArchitecturesOk() ([]string, bool) {
	if o == nil || IsNil(o.Architectures) {
		return nil, false
	}
	return o.Architectures, true
}

// HasArchitectures returns a boolean if a field has been set.
func (o *DebRemoteRepo) HasArchitectures() bool {
	if o != nil && !IsNil(o.Architectures) {
		return true
	}

	return false
}

// SetArchitectures gets a reference to the given []string and assigns it to the Architectures field.
func (o *DebRemoteRepo) SetArchitectures(v []string) {
	o.Architectures = v
}

// GetArchiveRoot returns the ArchiveRoot field value if set, zero value otherwise.
func (o *DebRemoteRepo) GetArchiveRoot() string {
	if o == nil || IsNil(o.ArchiveRoot) {
		var ret string
		return ret
	}
	return *o.ArchiveRoot
}

// GetArchiveRootOk returns a tuple with the ArchiveRoot field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebRemoteRepo) GetArchiveRootOk() (*string, bool) {
	if o == nil || IsNil(o.ArchiveRoot) {
		return nil, false
	}
	return o.ArchiveRoot, true
}

// HasArchiveRoot returns a boolean if a field has been set.
func (o *DebRemoteRepo) HasArchiveRoot() bool {
	if o != nil && !IsNil(o.ArchiveRoot) {
		return true
	}

	return false
}

// SetArchiveRoot gets a reference to the given string and assigns it to the ArchiveRoot field.
func (o *DebRemoteRepo) SetArchiveRoot(v string) {
	o.ArchiveRoot = &v
}

// GetComponents returns the Components field value if set, zero value otherwise.
func (o *DebRemoteRepo) GetComponents() []string {
	if o == nil || IsNil(o.Components) {
		var ret []string
		return ret
	}
	return o.Components
}

// GetComponentsOk returns a tuple with the Components field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebRemoteRepo) GetComponentsOk() ([]string, bool) {
	if o == nil || IsNil(o.Components) {
		return nil, false
	}
	return o.Components, true
}

// HasComponents returns a boolean if a field has been set.
func (o *DebRemoteRepo) HasComponents() bool {
	if o != nil && !IsNil(o.Components) {
		return true
	}

	return false
}

// SetComponents gets a reference to the given []string and assigns it to the Components field.
func (o *DebRemoteRepo) SetComponents(v []string) {
	o.Components = v
}

// GetDistribution returns the Distribution field value if set, zero value otherwise.
func (o *DebRemoteRepo) GetDistribution() string {
	if o == nil || IsNil(o.Distribution) {
		var ret string
		return ret
	}
	return *o.Distribution
}

// GetDistributionOk returns a tuple with the Distribution field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebRemoteRepo) GetDistributionOk() (*string, bool) {
	if o == nil || IsNil(o.Distribution) {
		return nil, false
	}
	return o.Distribution, true
}

// HasDistribution returns a boolean if a field has been set.
func (o *DebRemoteRepo) HasDistribution() bool {
	if o != nil && !IsNil(o.Distribution) {
		return true
	}

	return false
}

// SetDistribution gets a reference to the given string and assigns it to the Distribution field.
func (o *DebRemoteRepo) SetDistribution(v string) {
	o.Distribution = &v
}

// GetDownloadInstaller returns the DownloadInstaller field value if set, zero value otherwise.
func (o *DebRemoteRepo) GetDownloadInstaller() bool {
	if o == nil || IsNil(o.DownloadInstaller) {
		var ret bool
		return ret
	}
	return *o.DownloadInstaller
}

// GetDownloadInstallerOk returns a tuple with the DownloadInstaller field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebRemoteRepo) GetDownloadInstallerOk() (*bool, bool) {
	if o == nil || IsNil(o.DownloadInstaller) {
		return nil, false
	}
	return o.DownloadInstaller, true
}

// HasDownloadInstaller returns a boolean if a field has been set.
func (o *DebRemoteRepo) HasDownloadInstaller() bool {
	if o != nil && !IsNil(o.DownloadInstaller) {
		return true
	}

	return false
}

// SetDownloadInstaller gets a reference to the given bool and assigns it to the DownloadInstaller field.
func (o *DebRemoteRepo) SetDownloadInstaller(v bool) {
	o.DownloadInstaller = &v
}

// GetDownloadSources returns the DownloadSources field value if set, zero value otherwise.
func (o *DebRemoteRepo) GetDownloadSources() bool {
	if o == nil || IsNil(o.DownloadSources) {
		var ret bool
		return ret
	}
	return *o.DownloadSources
}

// GetDownloadSourcesOk returns a tuple with the DownloadSources field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebRemoteRepo) GetDownloadSourcesOk() (*bool, bool) {
	if o == nil || IsNil(o.DownloadSources) {
		return nil, false
	}
	return o.DownloadSources, true
}

// HasDownloadSources returns a boolean if a field has been set.
func (o *DebRemoteRepo) HasDownloadSources() bool {
	if o != nil && !IsNil(o.DownloadSources) {
		return true
	}

	return false
}

// SetDownloadSources gets a reference to the given bool and assigns it to the DownloadSources field.
func (o *DebRemoteRepo) SetDownloadSources(v bool) {
	o.DownloadSources = &v
}

// GetDownloadUdebs returns the DownloadUdebs field value if set, zero value otherwise.
func (o *DebRemoteRepo) GetDownloadUdebs() bool {
	if o == nil || IsNil(o.DownloadUdebs) {
		var ret bool
		return ret
	}
	return *o.DownloadUdebs
}

// GetDownloadUdebsOk returns a tuple with the DownloadUdebs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebRemoteRepo) GetDownloadUdebsOk() (*bool, bool) {
	if o == nil || IsNil(o.DownloadUdebs) {
		return nil, false
	}
	return o.DownloadUdebs, true
}

// HasDownloadUdebs returns a boolean if a field has been set.
func (o *DebRemoteRepo) HasDownloadUdebs() bool {
	if o != nil && !IsNil(o.DownloadUdebs) {
		return true
	}

	return false
}

// SetDownloadUdebs gets a reference to the given bool and assigns it to the DownloadUdebs field.
func (o *DebRemoteRepo) SetDownloadUdebs(v bool) {
	o.DownloadUdebs = &v
}

// GetFilter returns the Filter field value if set, zero value otherwise.
func (o *DebRemoteRepo) GetFilter() string {
	if o == nil || IsNil(o.Filter) {
		var ret string
		return ret
	}
	return *o.Filter
}

// GetFilterOk returns a tuple with the Filter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebRemoteRepo) GetFilterOk() (*string, bool) {
	if o == nil || IsNil(o.Filter) {
		return nil, false
	}
	return o.Filter, true
}

// HasFilter returns a boolean if a field has been set.
func (o *DebRemoteRepo) HasFilter() bool {
	if o != nil && !IsNil(o.Filter) {
		return true
	}

	return false
}

// SetFilter gets a reference to the given string and assigns it to the Filter field.
func (o *DebRemoteRepo) SetFilter(v string) {
	o.Filter = &v
}

// GetFilterWithDeps returns the FilterWithDeps field value if set, zero value otherwise.
func (o *DebRemoteRepo) GetFilterWithDeps() bool {
	if o == nil || IsNil(o.FilterWithDeps) {
		var ret bool
		return ret
	}
	return *o.FilterWithDeps
}

// GetFilterWithDepsOk returns a tuple with the FilterWithDeps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebRemoteRepo) GetFilterWithDepsOk() (*bool, bool) {
	if o == nil || IsNil(o.FilterWithDeps) {
		return nil, false
	}
	return o.FilterWithDeps, true
}

// HasFilterWithDeps returns a boolean if a field has been set.
func (o *DebRemoteRepo) HasFilterWithDeps() bool {
	if o != nil && !IsNil(o.FilterWithDeps) {
		return true
	}

	return false
}

// SetFilterWithDeps gets a reference to the given bool and assigns it to the FilterWithDeps field.
func (o *DebRemoteRepo) SetFilterWithDeps(v bool) {
	o.FilterWithDeps = &v
}

// GetLastDownloadDate returns the LastDownloadDate field value if set, zero value otherwise.
func (o *DebRemoteRepo) GetLastDownloadDate() string {
	if o == nil || IsNil(o.LastDownloadDate) {
		var ret string
		return ret
	}
	return *o.LastDownloadDate
}

// GetLastDownloadDateOk returns a tuple with the LastDownloadDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebRemoteRepo) GetLastDownloadDateOk() (*string, bool) {
	if o == nil || IsNil(o.LastDownloadDate) {
		return nil, false
	}
	return o.LastDownloadDate, true
}

// HasLastDownloadDate returns a boolean if a field has been set.
func (o *DebRemoteRepo) HasLastDownloadDate() bool {
	if o != nil && !IsNil(o.LastDownloadDate) {
		return true
	}

	return false
}

// SetLastDownloadDate gets a reference to the given string and assigns it to the LastDownloadDate field.
func (o *DebRemoteRepo) SetLastDownloadDate(v string) {
	o.LastDownloadDate = &v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *DebRemoteRepo) GetMeta() map[string]string {
	if o == nil || IsNil(o.Meta) {
		var ret map[string]string
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebRemoteRepo) GetMetaOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *DebRemoteRepo) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given map[string]string and assigns it to the Meta field.
func (o *DebRemoteRepo) SetMeta(v map[string]string) {
	o.Meta = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *DebRemoteRepo) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebRemoteRepo) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *DebRemoteRepo) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *DebRemoteRepo) SetName(v string) {
	o.Name = &v
}

// GetPackages returns the Packages field value if set, zero value otherwise.
func (o *DebRemoteRepo) GetPackages() []string {
	if o == nil || IsNil(o.Packages) {
		var ret []string
		return ret
	}
	return o.Packages
}

// GetPackagesOk returns a tuple with the Packages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebRemoteRepo) GetPackagesOk() ([]string, bool) {
	if o == nil || IsNil(o.Packages) {
		return nil, false
	}
	return o.Packages, true
}

// HasPackages returns a boolean if a field has been set.
func (o *DebRemoteRepo) HasPackages() bool {
	if o != nil && !IsNil(o.Packages) {
		return true
	}

	return false
}

// SetPackages gets a reference to the given []string and assigns it to the Packages field.
func (o *DebRemoteRepo) SetPackages(v []string) {
	o.Packages = v
}

// GetSkipArchitectureCheck returns the SkipArchitectureCheck field value if set, zero value otherwise.
func (o *DebRemoteRepo) GetSkipArchitectureCheck() bool {
	if o == nil || IsNil(o.SkipArchitectureCheck) {
		var ret bool
		return ret
	}
	return *o.SkipArchitectureCheck
}

// GetSkipArchitectureCheckOk returns a tuple with the SkipArchitectureCheck field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebRemoteRepo) GetSkipArchitectureCheckOk() (*bool, bool) {
	if o == nil || IsNil(o.SkipArchitectureCheck) {
		return nil, false
	}
	return o.SkipArchitectureCheck, true
}

// HasSkipArchitectureCheck returns a boolean if a field has been set.
func (o *DebRemoteRepo) HasSkipArchitectureCheck() bool {
	if o != nil && !IsNil(o.SkipArchitectureCheck) {
		return true
	}

	return false
}

// SetSkipArchitectureCheck gets a reference to the given bool and assigns it to the SkipArchitectureCheck field.
func (o *DebRemoteRepo) SetSkipArchitectureCheck(v bool) {
	o.SkipArchitectureCheck = &v
}

// GetSkipComponentCheck returns the SkipComponentCheck field value if set, zero value otherwise.
func (o *DebRemoteRepo) GetSkipComponentCheck() bool {
	if o == nil || IsNil(o.SkipComponentCheck) {
		var ret bool
		return ret
	}
	return *o.SkipComponentCheck
}

// GetSkipComponentCheckOk returns a tuple with the SkipComponentCheck field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebRemoteRepo) GetSkipComponentCheckOk() (*bool, bool) {
	if o == nil || IsNil(o.SkipComponentCheck) {
		return nil, false
	}
	return o.SkipComponentCheck, true
}

// HasSkipComponentCheck returns a boolean if a field has been set.
func (o *DebRemoteRepo) HasSkipComponentCheck() bool {
	if o != nil && !IsNil(o.SkipComponentCheck) {
		return true
	}

	return false
}

// SetSkipComponentCheck gets a reference to the given bool and assigns it to the SkipComponentCheck field.
func (o *DebRemoteRepo) SetSkipComponentCheck(v bool) {
	o.SkipComponentCheck = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *DebRemoteRepo) GetStatus() int32 {
	if o == nil || IsNil(o.Status) {
		var ret int32
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebRemoteRepo) GetStatusOk() (*int32, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *DebRemoteRepo) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given int32 and assigns it to the Status field.
func (o *DebRemoteRepo) SetStatus(v int32) {
	o.Status = &v
}

// GetUUID returns the UUID field value if set, zero value otherwise.
func (o *DebRemoteRepo) GetUUID() string {
	if o == nil || IsNil(o.UUID) {
		var ret string
		return ret
	}
	return *o.UUID
}

// GetUUIDOk returns a tuple with the UUID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebRemoteRepo) GetUUIDOk() (*string, bool) {
	if o == nil || IsNil(o.UUID) {
		return nil, false
	}
	return o.UUID, true
}

// HasUUID returns a boolean if a field has been set.
func (o *DebRemoteRepo) HasUUID() bool {
	if o != nil && !IsNil(o.UUID) {
		return true
	}

	return false
}

// SetUUID gets a reference to the given string and assigns it to the UUID field.
func (o *DebRemoteRepo) SetUUID(v string) {
	o.UUID = &v
}

// GetWorkerPID returns the WorkerPID field value if set, zero value otherwise.
func (o *DebRemoteRepo) GetWorkerPID() int32 {
	if o == nil || IsNil(o.WorkerPID) {
		var ret int32
		return ret
	}
	return *o.WorkerPID
}

// GetWorkerPIDOk returns a tuple with the WorkerPID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebRemoteRepo) GetWorkerPIDOk() (*int32, bool) {
	if o == nil || IsNil(o.WorkerPID) {
		return nil, false
	}
	return o.WorkerPID, true
}

// HasWorkerPID returns a boolean if a field has been set.
func (o *DebRemoteRepo) HasWorkerPID() bool {
	if o != nil && !IsNil(o.WorkerPID) {
		return true
	}

	return false
}

// SetWorkerPID gets a reference to the given int32 and assigns it to the WorkerPID field.
func (o *DebRemoteRepo) SetWorkerPID(v int32) {
	o.WorkerPID = &v
}

func (o DebRemoteRepo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DebRemoteRepo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Architectures) {
		toSerialize["Architectures"] = o.Architectures
	}
	if !IsNil(o.ArchiveRoot) {
		toSerialize["ArchiveRoot"] = o.ArchiveRoot
	}
	if !IsNil(o.Components) {
		toSerialize["Components"] = o.Components
	}
	if !IsNil(o.Distribution) {
		toSerialize["Distribution"] = o.Distribution
	}
	if !IsNil(o.DownloadInstaller) {
		toSerialize["DownloadInstaller"] = o.DownloadInstaller
	}
	if !IsNil(o.DownloadSources) {
		toSerialize["DownloadSources"] = o.DownloadSources
	}
	if !IsNil(o.DownloadUdebs) {
		toSerialize["DownloadUdebs"] = o.DownloadUdebs
	}
	if !IsNil(o.Filter) {
		toSerialize["Filter"] = o.Filter
	}
	if !IsNil(o.FilterWithDeps) {
		toSerialize["FilterWithDeps"] = o.FilterWithDeps
	}
	if !IsNil(o.LastDownloadDate) {
		toSerialize["LastDownloadDate"] = o.LastDownloadDate
	}
	if !IsNil(o.Meta) {
		toSerialize["Meta"] = o.Meta
	}
	if !IsNil(o.Name) {
		toSerialize["Name"] = o.Name
	}
	if !IsNil(o.Packages) {
		toSerialize["Packages"] = o.Packages
	}
	if !IsNil(o.SkipArchitectureCheck) {
		toSerialize["SkipArchitectureCheck"] = o.SkipArchitectureCheck
	}
	if !IsNil(o.SkipComponentCheck) {
		toSerialize["SkipComponentCheck"] = o.SkipComponentCheck
	}
	if !IsNil(o.Status) {
		toSerialize["Status"] = o.Status
	}
	if !IsNil(o.UUID) {
		toSerialize["UUID"] = o.UUID
	}
	if !IsNil(o.WorkerPID) {
		toSerialize["WorkerPID"] = o.WorkerPID
	}
	return toSerialize, nil
}

type NullableDebRemoteRepo struct {
	value *DebRemoteRepo
	isSet bool
}

func (v NullableDebRemoteRepo) Get() *DebRemoteRepo {
	return v.value
}

func (v *NullableDebRemoteRepo) Set(val *DebRemoteRepo) {
	v.value = val
	v.isSet = true
}

func (v NullableDebRemoteRepo) IsSet() bool {
	return v.isSet
}

func (v *NullableDebRemoteRepo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDebRemoteRepo(val *DebRemoteRepo) *NullableDebRemoteRepo {
	return &NullableDebRemoteRepo{value: val, isSet: true}
}

func (v NullableDebRemoteRepo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDebRemoteRepo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


