/*
Aptly API

Aptly operations are also available via REST API served with `aptly api serve`.  On Debian based systems, a package `aptly-api` is available, which will run aptly as systemd service as dedicated aptly-api user.  Some configuration changes (S3 publishing endpoints, ...) will require restarting the aptly service in order to take effect.  The REST API shouldn't be exposed to the Internet as there is no authentication/protection, consider using a HTTP proxy (e.g. nginx) to add https and authentication.  #### Aptly REST API Documentation 

API version: 1.6.2+20260315225119.eb0ae3a
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aptly

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiReposPackagesAddDeleteParams type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiReposPackagesAddDeleteParams{}

// ApiReposPackagesAddDeleteParams struct for ApiReposPackagesAddDeleteParams
type ApiReposPackagesAddDeleteParams struct {
	// Package Refs
	PackageRefs []string `json:"PackageRefs"`
}

type _ApiReposPackagesAddDeleteParams ApiReposPackagesAddDeleteParams

// NewApiReposPackagesAddDeleteParams instantiates a new ApiReposPackagesAddDeleteParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiReposPackagesAddDeleteParams(packageRefs []string) *ApiReposPackagesAddDeleteParams {
	this := ApiReposPackagesAddDeleteParams{}
	this.PackageRefs = packageRefs
	return &this
}

// NewApiReposPackagesAddDeleteParamsWithDefaults instantiates a new ApiReposPackagesAddDeleteParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiReposPackagesAddDeleteParamsWithDefaults() *ApiReposPackagesAddDeleteParams {
	this := ApiReposPackagesAddDeleteParams{}
	return &this
}

// GetPackageRefs returns the PackageRefs field value
func (o *ApiReposPackagesAddDeleteParams) GetPackageRefs() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.PackageRefs
}

// GetPackageRefsOk returns a tuple with the PackageRefs field value
// and a boolean to check if the value has been set.
func (o *ApiReposPackagesAddDeleteParams) GetPackageRefsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PackageRefs, true
}

// SetPackageRefs sets field value
func (o *ApiReposPackagesAddDeleteParams) SetPackageRefs(v []string) {
	o.PackageRefs = v
}

func (o ApiReposPackagesAddDeleteParams) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiReposPackagesAddDeleteParams) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["PackageRefs"] = o.PackageRefs
	return toSerialize, nil
}

func (o *ApiReposPackagesAddDeleteParams) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"PackageRefs",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiReposPackagesAddDeleteParams := _ApiReposPackagesAddDeleteParams{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiReposPackagesAddDeleteParams)

	if err != nil {
		return err
	}

	*o = ApiReposPackagesAddDeleteParams(varApiReposPackagesAddDeleteParams)

	return err
}

type NullableApiReposPackagesAddDeleteParams struct {
	value *ApiReposPackagesAddDeleteParams
	isSet bool
}

func (v NullableApiReposPackagesAddDeleteParams) Get() *ApiReposPackagesAddDeleteParams {
	return v.value
}

func (v *NullableApiReposPackagesAddDeleteParams) Set(val *ApiReposPackagesAddDeleteParams) {
	v.value = val
	v.isSet = true
}

func (v NullableApiReposPackagesAddDeleteParams) IsSet() bool {
	return v.isSet
}

func (v *NullableApiReposPackagesAddDeleteParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiReposPackagesAddDeleteParams(val *ApiReposPackagesAddDeleteParams) *NullableApiReposPackagesAddDeleteParams {
	return &NullableApiReposPackagesAddDeleteParams{value: val, isSet: true}
}

func (v NullableApiReposPackagesAddDeleteParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiReposPackagesAddDeleteParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


