/*
Aptly API

Aptly operations are also available via REST API served with `aptly api serve`.  On Debian based systems, a package `aptly-api` is available, which will run aptly as systemd service as dedicated aptly-api user.  Some configuration changes (S3 publishing endpoints, ...) will require restarting the aptly service in order to take effect.  The REST API shouldn't be exposed to the Internet as there is no authentication/protection, consider using a HTTP proxy (e.g. nginx) to add https and authentication.  #### Aptly REST API Documentation 

API version: 1.6.2+20260315225119.eb0ae3a
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aptly

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiSnapshotsCreateFromRepositoryParams type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiSnapshotsCreateFromRepositoryParams{}

// ApiSnapshotsCreateFromRepositoryParams struct for ApiSnapshotsCreateFromRepositoryParams
type ApiSnapshotsCreateFromRepositoryParams struct {
	// Description of snapshot
	Description *string `json:"Description,omitempty"`
	// Name of snapshot to create
	Name string `json:"Name"`
}

type _ApiSnapshotsCreateFromRepositoryParams ApiSnapshotsCreateFromRepositoryParams

// NewApiSnapshotsCreateFromRepositoryParams instantiates a new ApiSnapshotsCreateFromRepositoryParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiSnapshotsCreateFromRepositoryParams(name string) *ApiSnapshotsCreateFromRepositoryParams {
	this := ApiSnapshotsCreateFromRepositoryParams{}
	this.Name = name
	return &this
}

// NewApiSnapshotsCreateFromRepositoryParamsWithDefaults instantiates a new ApiSnapshotsCreateFromRepositoryParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiSnapshotsCreateFromRepositoryParamsWithDefaults() *ApiSnapshotsCreateFromRepositoryParams {
	this := ApiSnapshotsCreateFromRepositoryParams{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ApiSnapshotsCreateFromRepositoryParams) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiSnapshotsCreateFromRepositoryParams) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ApiSnapshotsCreateFromRepositoryParams) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ApiSnapshotsCreateFromRepositoryParams) SetDescription(v string) {
	o.Description = &v
}

// GetName returns the Name field value
func (o *ApiSnapshotsCreateFromRepositoryParams) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ApiSnapshotsCreateFromRepositoryParams) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ApiSnapshotsCreateFromRepositoryParams) SetName(v string) {
	o.Name = v
}

func (o ApiSnapshotsCreateFromRepositoryParams) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiSnapshotsCreateFromRepositoryParams) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Description) {
		toSerialize["Description"] = o.Description
	}
	toSerialize["Name"] = o.Name
	return toSerialize, nil
}

func (o *ApiSnapshotsCreateFromRepositoryParams) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"Name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiSnapshotsCreateFromRepositoryParams := _ApiSnapshotsCreateFromRepositoryParams{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiSnapshotsCreateFromRepositoryParams)

	if err != nil {
		return err
	}

	*o = ApiSnapshotsCreateFromRepositoryParams(varApiSnapshotsCreateFromRepositoryParams)

	return err
}

type NullableApiSnapshotsCreateFromRepositoryParams struct {
	value *ApiSnapshotsCreateFromRepositoryParams
	isSet bool
}

func (v NullableApiSnapshotsCreateFromRepositoryParams) Get() *ApiSnapshotsCreateFromRepositoryParams {
	return v.value
}

func (v *NullableApiSnapshotsCreateFromRepositoryParams) Set(val *ApiSnapshotsCreateFromRepositoryParams) {
	v.value = val
	v.isSet = true
}

func (v NullableApiSnapshotsCreateFromRepositoryParams) IsSet() bool {
	return v.isSet
}

func (v *NullableApiSnapshotsCreateFromRepositoryParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiSnapshotsCreateFromRepositoryParams(val *ApiSnapshotsCreateFromRepositoryParams) *NullableApiSnapshotsCreateFromRepositoryParams {
	return &NullableApiSnapshotsCreateFromRepositoryParams{value: val, isSet: true}
}

func (v NullableApiSnapshotsCreateFromRepositoryParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiSnapshotsCreateFromRepositoryParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


