/*
Aptly API

Aptly operations are also available via REST API served with `aptly api serve`.  On Debian based systems, a package `aptly-api` is available, which will run aptly as systemd service as dedicated aptly-api user.  Some configuration changes (S3 publishing endpoints, ...) will require restarting the aptly service in order to take effect.  The REST API shouldn't be exposed to the Internet as there is no authentication/protection, consider using a HTTP proxy (e.g. nginx) to add https and authentication.  #### Aptly REST API Documentation 

API version: 1.6.2+20260308145521.8e943a3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aptly

import (
	"encoding/json"
)

// checks if the ApiReposIncludePackageFromDirResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiReposIncludePackageFromDirResponse{}

// ApiReposIncludePackageFromDirResponse struct for ApiReposIncludePackageFromDirResponse
type ApiReposIncludePackageFromDirResponse struct {
	FailedFiles []string `json:"FailedFiles,omitempty"`
	Report *AptlyRecordingResultReporter `json:"Report,omitempty"`
}

// NewApiReposIncludePackageFromDirResponse instantiates a new ApiReposIncludePackageFromDirResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiReposIncludePackageFromDirResponse() *ApiReposIncludePackageFromDirResponse {
	this := ApiReposIncludePackageFromDirResponse{}
	return &this
}

// NewApiReposIncludePackageFromDirResponseWithDefaults instantiates a new ApiReposIncludePackageFromDirResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiReposIncludePackageFromDirResponseWithDefaults() *ApiReposIncludePackageFromDirResponse {
	this := ApiReposIncludePackageFromDirResponse{}
	return &this
}

// GetFailedFiles returns the FailedFiles field value if set, zero value otherwise.
func (o *ApiReposIncludePackageFromDirResponse) GetFailedFiles() []string {
	if o == nil || IsNil(o.FailedFiles) {
		var ret []string
		return ret
	}
	return o.FailedFiles
}

// GetFailedFilesOk returns a tuple with the FailedFiles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiReposIncludePackageFromDirResponse) GetFailedFilesOk() ([]string, bool) {
	if o == nil || IsNil(o.FailedFiles) {
		return nil, false
	}
	return o.FailedFiles, true
}

// HasFailedFiles returns a boolean if a field has been set.
func (o *ApiReposIncludePackageFromDirResponse) HasFailedFiles() bool {
	if o != nil && !IsNil(o.FailedFiles) {
		return true
	}

	return false
}

// SetFailedFiles gets a reference to the given []string and assigns it to the FailedFiles field.
func (o *ApiReposIncludePackageFromDirResponse) SetFailedFiles(v []string) {
	o.FailedFiles = v
}

// GetReport returns the Report field value if set, zero value otherwise.
func (o *ApiReposIncludePackageFromDirResponse) GetReport() AptlyRecordingResultReporter {
	if o == nil || IsNil(o.Report) {
		var ret AptlyRecordingResultReporter
		return ret
	}
	return *o.Report
}

// GetReportOk returns a tuple with the Report field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiReposIncludePackageFromDirResponse) GetReportOk() (*AptlyRecordingResultReporter, bool) {
	if o == nil || IsNil(o.Report) {
		return nil, false
	}
	return o.Report, true
}

// HasReport returns a boolean if a field has been set.
func (o *ApiReposIncludePackageFromDirResponse) HasReport() bool {
	if o != nil && !IsNil(o.Report) {
		return true
	}

	return false
}

// SetReport gets a reference to the given AptlyRecordingResultReporter and assigns it to the Report field.
func (o *ApiReposIncludePackageFromDirResponse) SetReport(v AptlyRecordingResultReporter) {
	o.Report = &v
}

func (o ApiReposIncludePackageFromDirResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiReposIncludePackageFromDirResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FailedFiles) {
		toSerialize["FailedFiles"] = o.FailedFiles
	}
	if !IsNil(o.Report) {
		toSerialize["Report"] = o.Report
	}
	return toSerialize, nil
}

type NullableApiReposIncludePackageFromDirResponse struct {
	value *ApiReposIncludePackageFromDirResponse
	isSet bool
}

func (v NullableApiReposIncludePackageFromDirResponse) Get() *ApiReposIncludePackageFromDirResponse {
	return v.value
}

func (v *NullableApiReposIncludePackageFromDirResponse) Set(val *ApiReposIncludePackageFromDirResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableApiReposIncludePackageFromDirResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableApiReposIncludePackageFromDirResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiReposIncludePackageFromDirResponse(val *ApiReposIncludePackageFromDirResponse) *NullableApiReposIncludePackageFromDirResponse {
	return &NullableApiReposIncludePackageFromDirResponse{value: val, isSet: true}
}

func (v NullableApiReposIncludePackageFromDirResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiReposIncludePackageFromDirResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


