/*
Aptly API

Aptly operations are also available via REST API served with `aptly api serve`.  On Debian based systems, a package `aptly-api` is available, which will run aptly as systemd service as dedicated aptly-api user.  Some configuration changes (S3 publishing endpoints, ...) will require restarting the aptly service in order to take effect.  The REST API shouldn't be exposed to the Internet as there is no authentication/protection, consider using a HTTP proxy (e.g. nginx) to add https and authentication.  #### Aptly REST API Documentation 

API version: 1.6.2+20260316002414.a40994d
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aptly

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiPublishedRepoCreateParams type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiPublishedRepoCreateParams{}

// ApiPublishedRepoCreateParams struct for ApiPublishedRepoCreateParams
type ApiPublishedRepoCreateParams struct {
	// Provide index files by hash
	AcquireByHash *bool `json:"AcquireByHash,omitempty"`
	// Override list of published architectures
	Architectures []string `json:"Architectures,omitempty"`
	// setting to yes excludes upgrades from the NotAutomic setting
	ButAutomaticUpgrades *string `json:"ButAutomaticUpgrades,omitempty"`
	// Value of Description: field in published repository stanza
	Description *string `json:"Description,omitempty"`
	// Distribution name, if missing Aptly would try to guess from sources
	Distribution *string `json:"Distribution,omitempty"`
	// when publishing, overwrite files in pool/ directory without notice
	ForceOverwrite *bool `json:"ForceOverwrite,omitempty"`
	// Value of Label: field in published repository stanza
	Label *string `json:"Label,omitempty"`
	// Enable multiple packages with the same filename in different distributions
	MultiDist *bool `json:"MultiDist,omitempty"`
	// Setting to yes indicates to the package manager to not install or upgrade packages from the repository without user consent
	NotAutomatic *string `json:"NotAutomatic,omitempty"`
	// Value of Origin: field in published repository stanza
	Origin *string `json:"Origin,omitempty"`
	// An optional field containing a comma separated list of OpenPGP key fingerprints to be used for validating the next Release file.
	SignedBy *string `json:"SignedBy,omitempty"`
	// GPG options
	Signing *ApiSigningParams `json:"Signing,omitempty"`
	// Skip bz2 compression for index files
	SkipBz2 *bool `json:"SkipBz2,omitempty"`
	// Don't remove unreferenced files in prefix/component
	SkipCleanup *bool `json:"SkipCleanup,omitempty"`
	// Don't generate contents indexes
	SkipContents *bool `json:"SkipContents,omitempty"`
	// 'local' for local repositories and 'snapshot' for snapshots
	SourceKind string `json:"SourceKind"`
	// List of 'Component/Name' objects, 'Name' is either local repository or snapshot name
	Sources []ApiSourceParams `json:"Sources"`
}

type _ApiPublishedRepoCreateParams ApiPublishedRepoCreateParams

// NewApiPublishedRepoCreateParams instantiates a new ApiPublishedRepoCreateParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiPublishedRepoCreateParams(sourceKind string, sources []ApiSourceParams) *ApiPublishedRepoCreateParams {
	this := ApiPublishedRepoCreateParams{}
	this.SourceKind = sourceKind
	this.Sources = sources
	return &this
}

// NewApiPublishedRepoCreateParamsWithDefaults instantiates a new ApiPublishedRepoCreateParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiPublishedRepoCreateParamsWithDefaults() *ApiPublishedRepoCreateParams {
	this := ApiPublishedRepoCreateParams{}
	return &this
}

// GetAcquireByHash returns the AcquireByHash field value if set, zero value otherwise.
func (o *ApiPublishedRepoCreateParams) GetAcquireByHash() bool {
	if o == nil || IsNil(o.AcquireByHash) {
		var ret bool
		return ret
	}
	return *o.AcquireByHash
}

// GetAcquireByHashOk returns a tuple with the AcquireByHash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiPublishedRepoCreateParams) GetAcquireByHashOk() (*bool, bool) {
	if o == nil || IsNil(o.AcquireByHash) {
		return nil, false
	}
	return o.AcquireByHash, true
}

// HasAcquireByHash returns a boolean if a field has been set.
func (o *ApiPublishedRepoCreateParams) HasAcquireByHash() bool {
	if o != nil && !IsNil(o.AcquireByHash) {
		return true
	}

	return false
}

// SetAcquireByHash gets a reference to the given bool and assigns it to the AcquireByHash field.
func (o *ApiPublishedRepoCreateParams) SetAcquireByHash(v bool) {
	o.AcquireByHash = &v
}

// GetArchitectures returns the Architectures field value if set, zero value otherwise.
func (o *ApiPublishedRepoCreateParams) GetArchitectures() []string {
	if o == nil || IsNil(o.Architectures) {
		var ret []string
		return ret
	}
	return o.Architectures
}

// GetArchitecturesOk returns a tuple with the Architectures field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiPublishedRepoCreateParams) GetArchitecturesOk() ([]string, bool) {
	if o == nil || IsNil(o.Architectures) {
		return nil, false
	}
	return o.Architectures, true
}

// HasArchitectures returns a boolean if a field has been set.
func (o *ApiPublishedRepoCreateParams) HasArchitectures() bool {
	if o != nil && !IsNil(o.Architectures) {
		return true
	}

	return false
}

// SetArchitectures gets a reference to the given []string and assigns it to the Architectures field.
func (o *ApiPublishedRepoCreateParams) SetArchitectures(v []string) {
	o.Architectures = v
}

// GetButAutomaticUpgrades returns the ButAutomaticUpgrades field value if set, zero value otherwise.
func (o *ApiPublishedRepoCreateParams) GetButAutomaticUpgrades() string {
	if o == nil || IsNil(o.ButAutomaticUpgrades) {
		var ret string
		return ret
	}
	return *o.ButAutomaticUpgrades
}

// GetButAutomaticUpgradesOk returns a tuple with the ButAutomaticUpgrades field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiPublishedRepoCreateParams) GetButAutomaticUpgradesOk() (*string, bool) {
	if o == nil || IsNil(o.ButAutomaticUpgrades) {
		return nil, false
	}
	return o.ButAutomaticUpgrades, true
}

// HasButAutomaticUpgrades returns a boolean if a field has been set.
func (o *ApiPublishedRepoCreateParams) HasButAutomaticUpgrades() bool {
	if o != nil && !IsNil(o.ButAutomaticUpgrades) {
		return true
	}

	return false
}

// SetButAutomaticUpgrades gets a reference to the given string and assigns it to the ButAutomaticUpgrades field.
func (o *ApiPublishedRepoCreateParams) SetButAutomaticUpgrades(v string) {
	o.ButAutomaticUpgrades = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ApiPublishedRepoCreateParams) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiPublishedRepoCreateParams) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ApiPublishedRepoCreateParams) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ApiPublishedRepoCreateParams) SetDescription(v string) {
	o.Description = &v
}

// GetDistribution returns the Distribution field value if set, zero value otherwise.
func (o *ApiPublishedRepoCreateParams) GetDistribution() string {
	if o == nil || IsNil(o.Distribution) {
		var ret string
		return ret
	}
	return *o.Distribution
}

// GetDistributionOk returns a tuple with the Distribution field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiPublishedRepoCreateParams) GetDistributionOk() (*string, bool) {
	if o == nil || IsNil(o.Distribution) {
		return nil, false
	}
	return o.Distribution, true
}

// HasDistribution returns a boolean if a field has been set.
func (o *ApiPublishedRepoCreateParams) HasDistribution() bool {
	if o != nil && !IsNil(o.Distribution) {
		return true
	}

	return false
}

// SetDistribution gets a reference to the given string and assigns it to the Distribution field.
func (o *ApiPublishedRepoCreateParams) SetDistribution(v string) {
	o.Distribution = &v
}

// GetForceOverwrite returns the ForceOverwrite field value if set, zero value otherwise.
func (o *ApiPublishedRepoCreateParams) GetForceOverwrite() bool {
	if o == nil || IsNil(o.ForceOverwrite) {
		var ret bool
		return ret
	}
	return *o.ForceOverwrite
}

// GetForceOverwriteOk returns a tuple with the ForceOverwrite field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiPublishedRepoCreateParams) GetForceOverwriteOk() (*bool, bool) {
	if o == nil || IsNil(o.ForceOverwrite) {
		return nil, false
	}
	return o.ForceOverwrite, true
}

// HasForceOverwrite returns a boolean if a field has been set.
func (o *ApiPublishedRepoCreateParams) HasForceOverwrite() bool {
	if o != nil && !IsNil(o.ForceOverwrite) {
		return true
	}

	return false
}

// SetForceOverwrite gets a reference to the given bool and assigns it to the ForceOverwrite field.
func (o *ApiPublishedRepoCreateParams) SetForceOverwrite(v bool) {
	o.ForceOverwrite = &v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *ApiPublishedRepoCreateParams) GetLabel() string {
	if o == nil || IsNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiPublishedRepoCreateParams) GetLabelOk() (*string, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *ApiPublishedRepoCreateParams) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *ApiPublishedRepoCreateParams) SetLabel(v string) {
	o.Label = &v
}

// GetMultiDist returns the MultiDist field value if set, zero value otherwise.
func (o *ApiPublishedRepoCreateParams) GetMultiDist() bool {
	if o == nil || IsNil(o.MultiDist) {
		var ret bool
		return ret
	}
	return *o.MultiDist
}

// GetMultiDistOk returns a tuple with the MultiDist field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiPublishedRepoCreateParams) GetMultiDistOk() (*bool, bool) {
	if o == nil || IsNil(o.MultiDist) {
		return nil, false
	}
	return o.MultiDist, true
}

// HasMultiDist returns a boolean if a field has been set.
func (o *ApiPublishedRepoCreateParams) HasMultiDist() bool {
	if o != nil && !IsNil(o.MultiDist) {
		return true
	}

	return false
}

// SetMultiDist gets a reference to the given bool and assigns it to the MultiDist field.
func (o *ApiPublishedRepoCreateParams) SetMultiDist(v bool) {
	o.MultiDist = &v
}

// GetNotAutomatic returns the NotAutomatic field value if set, zero value otherwise.
func (o *ApiPublishedRepoCreateParams) GetNotAutomatic() string {
	if o == nil || IsNil(o.NotAutomatic) {
		var ret string
		return ret
	}
	return *o.NotAutomatic
}

// GetNotAutomaticOk returns a tuple with the NotAutomatic field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiPublishedRepoCreateParams) GetNotAutomaticOk() (*string, bool) {
	if o == nil || IsNil(o.NotAutomatic) {
		return nil, false
	}
	return o.NotAutomatic, true
}

// HasNotAutomatic returns a boolean if a field has been set.
func (o *ApiPublishedRepoCreateParams) HasNotAutomatic() bool {
	if o != nil && !IsNil(o.NotAutomatic) {
		return true
	}

	return false
}

// SetNotAutomatic gets a reference to the given string and assigns it to the NotAutomatic field.
func (o *ApiPublishedRepoCreateParams) SetNotAutomatic(v string) {
	o.NotAutomatic = &v
}

// GetOrigin returns the Origin field value if set, zero value otherwise.
func (o *ApiPublishedRepoCreateParams) GetOrigin() string {
	if o == nil || IsNil(o.Origin) {
		var ret string
		return ret
	}
	return *o.Origin
}

// GetOriginOk returns a tuple with the Origin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiPublishedRepoCreateParams) GetOriginOk() (*string, bool) {
	if o == nil || IsNil(o.Origin) {
		return nil, false
	}
	return o.Origin, true
}

// HasOrigin returns a boolean if a field has been set.
func (o *ApiPublishedRepoCreateParams) HasOrigin() bool {
	if o != nil && !IsNil(o.Origin) {
		return true
	}

	return false
}

// SetOrigin gets a reference to the given string and assigns it to the Origin field.
func (o *ApiPublishedRepoCreateParams) SetOrigin(v string) {
	o.Origin = &v
}

// GetSignedBy returns the SignedBy field value if set, zero value otherwise.
func (o *ApiPublishedRepoCreateParams) GetSignedBy() string {
	if o == nil || IsNil(o.SignedBy) {
		var ret string
		return ret
	}
	return *o.SignedBy
}

// GetSignedByOk returns a tuple with the SignedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiPublishedRepoCreateParams) GetSignedByOk() (*string, bool) {
	if o == nil || IsNil(o.SignedBy) {
		return nil, false
	}
	return o.SignedBy, true
}

// HasSignedBy returns a boolean if a field has been set.
func (o *ApiPublishedRepoCreateParams) HasSignedBy() bool {
	if o != nil && !IsNil(o.SignedBy) {
		return true
	}

	return false
}

// SetSignedBy gets a reference to the given string and assigns it to the SignedBy field.
func (o *ApiPublishedRepoCreateParams) SetSignedBy(v string) {
	o.SignedBy = &v
}

// GetSigning returns the Signing field value if set, zero value otherwise.
func (o *ApiPublishedRepoCreateParams) GetSigning() ApiSigningParams {
	if o == nil || IsNil(o.Signing) {
		var ret ApiSigningParams
		return ret
	}
	return *o.Signing
}

// GetSigningOk returns a tuple with the Signing field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiPublishedRepoCreateParams) GetSigningOk() (*ApiSigningParams, bool) {
	if o == nil || IsNil(o.Signing) {
		return nil, false
	}
	return o.Signing, true
}

// HasSigning returns a boolean if a field has been set.
func (o *ApiPublishedRepoCreateParams) HasSigning() bool {
	if o != nil && !IsNil(o.Signing) {
		return true
	}

	return false
}

// SetSigning gets a reference to the given ApiSigningParams and assigns it to the Signing field.
func (o *ApiPublishedRepoCreateParams) SetSigning(v ApiSigningParams) {
	o.Signing = &v
}

// GetSkipBz2 returns the SkipBz2 field value if set, zero value otherwise.
func (o *ApiPublishedRepoCreateParams) GetSkipBz2() bool {
	if o == nil || IsNil(o.SkipBz2) {
		var ret bool
		return ret
	}
	return *o.SkipBz2
}

// GetSkipBz2Ok returns a tuple with the SkipBz2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiPublishedRepoCreateParams) GetSkipBz2Ok() (*bool, bool) {
	if o == nil || IsNil(o.SkipBz2) {
		return nil, false
	}
	return o.SkipBz2, true
}

// HasSkipBz2 returns a boolean if a field has been set.
func (o *ApiPublishedRepoCreateParams) HasSkipBz2() bool {
	if o != nil && !IsNil(o.SkipBz2) {
		return true
	}

	return false
}

// SetSkipBz2 gets a reference to the given bool and assigns it to the SkipBz2 field.
func (o *ApiPublishedRepoCreateParams) SetSkipBz2(v bool) {
	o.SkipBz2 = &v
}

// GetSkipCleanup returns the SkipCleanup field value if set, zero value otherwise.
func (o *ApiPublishedRepoCreateParams) GetSkipCleanup() bool {
	if o == nil || IsNil(o.SkipCleanup) {
		var ret bool
		return ret
	}
	return *o.SkipCleanup
}

// GetSkipCleanupOk returns a tuple with the SkipCleanup field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiPublishedRepoCreateParams) GetSkipCleanupOk() (*bool, bool) {
	if o == nil || IsNil(o.SkipCleanup) {
		return nil, false
	}
	return o.SkipCleanup, true
}

// HasSkipCleanup returns a boolean if a field has been set.
func (o *ApiPublishedRepoCreateParams) HasSkipCleanup() bool {
	if o != nil && !IsNil(o.SkipCleanup) {
		return true
	}

	return false
}

// SetSkipCleanup gets a reference to the given bool and assigns it to the SkipCleanup field.
func (o *ApiPublishedRepoCreateParams) SetSkipCleanup(v bool) {
	o.SkipCleanup = &v
}

// GetSkipContents returns the SkipContents field value if set, zero value otherwise.
func (o *ApiPublishedRepoCreateParams) GetSkipContents() bool {
	if o == nil || IsNil(o.SkipContents) {
		var ret bool
		return ret
	}
	return *o.SkipContents
}

// GetSkipContentsOk returns a tuple with the SkipContents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiPublishedRepoCreateParams) GetSkipContentsOk() (*bool, bool) {
	if o == nil || IsNil(o.SkipContents) {
		return nil, false
	}
	return o.SkipContents, true
}

// HasSkipContents returns a boolean if a field has been set.
func (o *ApiPublishedRepoCreateParams) HasSkipContents() bool {
	if o != nil && !IsNil(o.SkipContents) {
		return true
	}

	return false
}

// SetSkipContents gets a reference to the given bool and assigns it to the SkipContents field.
func (o *ApiPublishedRepoCreateParams) SetSkipContents(v bool) {
	o.SkipContents = &v
}

// GetSourceKind returns the SourceKind field value
func (o *ApiPublishedRepoCreateParams) GetSourceKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceKind
}

// GetSourceKindOk returns a tuple with the SourceKind field value
// and a boolean to check if the value has been set.
func (o *ApiPublishedRepoCreateParams) GetSourceKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceKind, true
}

// SetSourceKind sets field value
func (o *ApiPublishedRepoCreateParams) SetSourceKind(v string) {
	o.SourceKind = v
}

// GetSources returns the Sources field value
func (o *ApiPublishedRepoCreateParams) GetSources() []ApiSourceParams {
	if o == nil {
		var ret []ApiSourceParams
		return ret
	}

	return o.Sources
}

// GetSourcesOk returns a tuple with the Sources field value
// and a boolean to check if the value has been set.
func (o *ApiPublishedRepoCreateParams) GetSourcesOk() ([]ApiSourceParams, bool) {
	if o == nil {
		return nil, false
	}
	return o.Sources, true
}

// SetSources sets field value
func (o *ApiPublishedRepoCreateParams) SetSources(v []ApiSourceParams) {
	o.Sources = v
}

func (o ApiPublishedRepoCreateParams) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiPublishedRepoCreateParams) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AcquireByHash) {
		toSerialize["AcquireByHash"] = o.AcquireByHash
	}
	if !IsNil(o.Architectures) {
		toSerialize["Architectures"] = o.Architectures
	}
	if !IsNil(o.ButAutomaticUpgrades) {
		toSerialize["ButAutomaticUpgrades"] = o.ButAutomaticUpgrades
	}
	if !IsNil(o.Description) {
		toSerialize["Description"] = o.Description
	}
	if !IsNil(o.Distribution) {
		toSerialize["Distribution"] = o.Distribution
	}
	if !IsNil(o.ForceOverwrite) {
		toSerialize["ForceOverwrite"] = o.ForceOverwrite
	}
	if !IsNil(o.Label) {
		toSerialize["Label"] = o.Label
	}
	if !IsNil(o.MultiDist) {
		toSerialize["MultiDist"] = o.MultiDist
	}
	if !IsNil(o.NotAutomatic) {
		toSerialize["NotAutomatic"] = o.NotAutomatic
	}
	if !IsNil(o.Origin) {
		toSerialize["Origin"] = o.Origin
	}
	if !IsNil(o.SignedBy) {
		toSerialize["SignedBy"] = o.SignedBy
	}
	if !IsNil(o.Signing) {
		toSerialize["Signing"] = o.Signing
	}
	if !IsNil(o.SkipBz2) {
		toSerialize["SkipBz2"] = o.SkipBz2
	}
	if !IsNil(o.SkipCleanup) {
		toSerialize["SkipCleanup"] = o.SkipCleanup
	}
	if !IsNil(o.SkipContents) {
		toSerialize["SkipContents"] = o.SkipContents
	}
	toSerialize["SourceKind"] = o.SourceKind
	toSerialize["Sources"] = o.Sources
	return toSerialize, nil
}

func (o *ApiPublishedRepoCreateParams) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"SourceKind",
		"Sources",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiPublishedRepoCreateParams := _ApiPublishedRepoCreateParams{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiPublishedRepoCreateParams)

	if err != nil {
		return err
	}

	*o = ApiPublishedRepoCreateParams(varApiPublishedRepoCreateParams)

	return err
}

type NullableApiPublishedRepoCreateParams struct {
	value *ApiPublishedRepoCreateParams
	isSet bool
}

func (v NullableApiPublishedRepoCreateParams) Get() *ApiPublishedRepoCreateParams {
	return v.value
}

func (v *NullableApiPublishedRepoCreateParams) Set(val *ApiPublishedRepoCreateParams) {
	v.value = val
	v.isSet = true
}

func (v NullableApiPublishedRepoCreateParams) IsSet() bool {
	return v.isSet
}

func (v *NullableApiPublishedRepoCreateParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiPublishedRepoCreateParams(val *ApiPublishedRepoCreateParams) *NullableApiPublishedRepoCreateParams {
	return &NullableApiPublishedRepoCreateParams{value: val, isSet: true}
}

func (v NullableApiPublishedRepoCreateParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiPublishedRepoCreateParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


