/*
 * Aptly API
 *
 * Aptly operations are also available via REST API served with `aptly api serve`.  On Debian based systems, a package `aptly-api` is available, which will run aptly as systemd service as dedicated aptly-api user.  Some configuration changes (S3 publishing endpoints, ...) will require restarting the aptly service in order to take effect.  The REST API shouldn't be exposed to the Internet as there is no authentication/protection, consider using a HTTP proxy (e.g. nginx) to add https and authentication.  #### Aptly REST API Documentation 
 *
 * The version of the OpenAPI document: 1.6.2+20260315225119.eb0ae3a
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`api_publish_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ApiPublishGetError {
    Status500(models::ApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`api_publish_prefix_distribution_delete`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ApiPublishPrefixDistributionDeleteError {
    Status400(models::ApiError),
    Status404(models::ApiError),
    Status500(models::ApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`api_publish_prefix_distribution_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ApiPublishPrefixDistributionGetError {
    Status404(models::ApiError),
    Status500(models::ApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`api_publish_prefix_distribution_put`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ApiPublishPrefixDistributionPutError {
    Status400(models::ApiError),
    Status404(models::ApiError),
    Status500(models::ApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`api_publish_prefix_distribution_sources_component_delete`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ApiPublishPrefixDistributionSourcesComponentDeleteError {
    Status400(models::ApiError),
    Status404(models::ApiError),
    Status500(models::ApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`api_publish_prefix_distribution_sources_component_put`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ApiPublishPrefixDistributionSourcesComponentPutError {
    Status400(models::ApiError),
    Status404(models::ApiError),
    Status500(models::ApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`api_publish_prefix_distribution_sources_delete`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ApiPublishPrefixDistributionSourcesDeleteError {
    Status400(models::ApiError),
    Status404(models::ApiError),
    Status500(models::ApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`api_publish_prefix_distribution_sources_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ApiPublishPrefixDistributionSourcesGetError {
    Status400(models::ApiError),
    Status404(models::ApiError),
    Status500(models::ApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`api_publish_prefix_distribution_sources_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ApiPublishPrefixDistributionSourcesPostError {
    Status400(models::ApiError),
    Status404(models::ApiError),
    Status500(models::ApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`api_publish_prefix_distribution_sources_put`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ApiPublishPrefixDistributionSourcesPutError {
    Status400(models::ApiError),
    Status404(models::ApiError),
    Status500(models::ApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`api_publish_prefix_distribution_update_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ApiPublishPrefixDistributionUpdatePostError {
    Status400(models::ApiError),
    Status404(models::ApiError),
    Status500(models::ApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`api_publish_prefix_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ApiPublishPrefixPostError {
    Status400(models::ApiError),
    Status404(models::ApiError),
    Status500(models::ApiError),
    UnknownValue(serde_json::Value),
}


/// **Get list of published repositories**  Return list of published repositories including detailed information.  See also: `aptly publish list`
pub async fn api_publish_get(configuration: &configuration::Configuration, ) -> Result<Vec<models::DebPublishedRepo>, Error<ApiPublishGetError>> {

    let uri_str = format!("{}/api/publish", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::DebPublishedRepo&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::DebPublishedRepo&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ApiPublishGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// **Delete a published repository**  Delete a distribution of a published repository and remove associated files.  If no other published repositories share the same prefix, all files inside the prefix will be removed.  See also: `aptly publish drop`
pub async fn api_publish_prefix_distribution_delete(configuration: &configuration::Configuration, prefix: &str, distribution: &str, force: i32, skip_cleanup: i32, _async: Option<bool>) -> Result<(), Error<ApiPublishPrefixDistributionDeleteError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_prefix = prefix;
    let p_path_distribution = distribution;
    let p_query_force = force;
    let p_query_skip_cleanup = skip_cleanup;
    let p_query__async = _async;

    let uri_str = format!("{}/api/publish/{prefix}/{distribution}", configuration.base_path, prefix=crate::apis::urlencode(p_path_prefix), distribution=crate::apis::urlencode(p_path_distribution));
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    req_builder = req_builder.query(&[("force", &p_query_force.to_string())]);
    req_builder = req_builder.query(&[("skipCleanup", &p_query_skip_cleanup.to_string())]);
    if let Some(ref param_value) = p_query__async {
        req_builder = req_builder.query(&[("_async", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<ApiPublishPrefixDistributionDeleteError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// **Get published repository information**  Show detailed information of a published repository.  See also: `aptly publish show`
pub async fn api_publish_prefix_distribution_get(configuration: &configuration::Configuration, prefix: &str, distribution: &str) -> Result<models::DebPublishedRepo, Error<ApiPublishPrefixDistributionGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_prefix = prefix;
    let p_path_distribution = distribution;

    let uri_str = format!("{}/api/publish/{prefix}/{distribution}", configuration.base_path, prefix=crate::apis::urlencode(p_path_prefix), distribution=crate::apis::urlencode(p_path_distribution));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::DebPublishedRepo`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::DebPublishedRepo`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ApiPublishPrefixDistributionGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// **Update a published repository**  Update a published local repository or switch snapshot.  For published local repositories: * update to match local repository contents  For published snapshots: * switch components to new snapshot  See also: `aptly publish update` / `aptly publish switch`
pub async fn api_publish_prefix_distribution_put(configuration: &configuration::Configuration, prefix: &str, distribution: &str, request: models::ApiPublishedRepoUpdateSwitchParams, _async: Option<bool>) -> Result<models::DebPublishedRepo, Error<ApiPublishPrefixDistributionPutError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_prefix = prefix;
    let p_path_distribution = distribution;
    let p_body_request = request;
    let p_query__async = _async;

    let uri_str = format!("{}/api/publish/{prefix}/{distribution}", configuration.base_path, prefix=crate::apis::urlencode(p_path_prefix), distribution=crate::apis::urlencode(p_path_distribution));
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref param_value) = p_query__async {
        req_builder = req_builder.query(&[("_async", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::DebPublishedRepo`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::DebPublishedRepo`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ApiPublishPrefixDistributionPutError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// **Remove a source component from a published repo**  Remove a source component (snapshot / local repo) from a published repository.  This call does not publish the changes, but rather schedules them for a subsequent publish update call (i.e `PUT /api/publish/{prefix}/{distribution}` / `POST /api/publish/{prefix}/{distribution}/update`).  See also: `aptly publish source remove`
pub async fn api_publish_prefix_distribution_sources_component_delete(configuration: &configuration::Configuration, prefix: &str, distribution: &str, component: &str, _async: Option<bool>) -> Result<(), Error<ApiPublishPrefixDistributionSourcesComponentDeleteError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_prefix = prefix;
    let p_path_distribution = distribution;
    let p_path_component = component;
    let p_query__async = _async;

    let uri_str = format!("{}/api/publish/{prefix}/{distribution}/sources/{component}", configuration.base_path, prefix=crate::apis::urlencode(p_path_prefix), distribution=crate::apis::urlencode(p_path_distribution), component=crate::apis::urlencode(p_path_component));
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref param_value) = p_query__async {
        req_builder = req_builder.query(&[("_async", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<ApiPublishPrefixDistributionSourcesComponentDeleteError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// **Update the source component of a published repository**  Update a component of a snapshot or local repository to be published.  This call does not publish the changes, but rather schedules them for a subsequent publish update call (i.e `PUT /api/publish/{prefix}/{distribution}` / `POST /api/publish/{prefix}/{distribution}/update`).  See also: `aptly publish source update`
pub async fn api_publish_prefix_distribution_sources_component_put(configuration: &configuration::Configuration, prefix: &str, distribution: &str, component: &str, request: models::ApiSourceParams, _async: Option<bool>) -> Result<(), Error<ApiPublishPrefixDistributionSourcesComponentPutError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_prefix = prefix;
    let p_path_distribution = distribution;
    let p_path_component = component;
    let p_body_request = request;
    let p_query__async = _async;

    let uri_str = format!("{}/api/publish/{prefix}/{distribution}/sources/{component}", configuration.base_path, prefix=crate::apis::urlencode(p_path_prefix), distribution=crate::apis::urlencode(p_path_distribution), component=crate::apis::urlencode(p_path_component));
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref param_value) = p_query__async {
        req_builder = req_builder.query(&[("_async", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<ApiPublishPrefixDistributionSourcesComponentPutError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// **Discard pending source component changes of a published repository**  Remove all pending changes what would be applied with a subsequent publish update call (i.e. `PUT /api/publish/{prefix}/{distribution}` / `POST /api/publish/{prefix}/{distribution}/update`).  See also: `aptly publish source drop`
pub async fn api_publish_prefix_distribution_sources_delete(configuration: &configuration::Configuration, prefix: &str, distribution: &str, _async: Option<bool>) -> Result<(), Error<ApiPublishPrefixDistributionSourcesDeleteError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_prefix = prefix;
    let p_path_distribution = distribution;
    let p_query__async = _async;

    let uri_str = format!("{}/api/publish/{prefix}/{distribution}/sources", configuration.base_path, prefix=crate::apis::urlencode(p_path_prefix), distribution=crate::apis::urlencode(p_path_distribution));
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref param_value) = p_query__async {
        req_builder = req_builder.query(&[("_async", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<ApiPublishPrefixDistributionSourcesDeleteError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// **List source component changes to be applied**  Return added, removed or changed components of snapshots or local repository to be published.  The changes will be applied by a subsequent publish update call (i.e. `PUT /api/publish/{prefix}/{distribution}` / `POST /api/publish/{prefix}/{distribution}/update`).  See also: `aptly publish source list`
pub async fn api_publish_prefix_distribution_sources_get(configuration: &configuration::Configuration, prefix: &str, distribution: &str) -> Result<Vec<Vec<models::DebSourceEntry>>, Error<ApiPublishPrefixDistributionSourcesGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_prefix = prefix;
    let p_path_distribution = distribution;

    let uri_str = format!("{}/api/publish/{prefix}/{distribution}/sources", configuration.base_path, prefix=crate::apis::urlencode(p_path_prefix), distribution=crate::apis::urlencode(p_path_distribution));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;Vec&lt;models::DebSourceEntry&gt;&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;Vec&lt;models::DebSourceEntry&gt;&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ApiPublishPrefixDistributionSourcesGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// **Add a source component to a published repo**  Add a component of a snapshot or local repository to be published.  This call does not publish the changes, but rather schedules them for a subsequent publish update call (i.e `PUT /api/publish/{prefix}/{distribution}` / `POST /api/publish/{prefix}/{distribution}/update`).  See also: `aptly publish source add`
pub async fn api_publish_prefix_distribution_sources_post(configuration: &configuration::Configuration, prefix: &str, distribution: &str, request: models::ApiSourceParams, _async: Option<bool>) -> Result<(), Error<ApiPublishPrefixDistributionSourcesPostError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_prefix = prefix;
    let p_path_distribution = distribution;
    let p_body_request = request;
    let p_query__async = _async;

    let uri_str = format!("{}/api/publish/{prefix}/{distribution}/sources", configuration.base_path, prefix=crate::apis::urlencode(p_path_prefix), distribution=crate::apis::urlencode(p_path_distribution));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref param_value) = p_query__async {
        req_builder = req_builder.query(&[("_async", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<ApiPublishPrefixDistributionSourcesPostError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// **Replace the source components of a published repository**  Sets the components of snapshots or local repositories to be published. Existing Sourced will be replaced.  This call does not publish the changes, but rather schedules them for a subsequent publish update call (i.e `PUT /api/publish/{prefix}/{distribution}` / `POST /api/publish/{prefix}/{distribution}/update`).  See also: `aptly publish source replace`
pub async fn api_publish_prefix_distribution_sources_put(configuration: &configuration::Configuration, prefix: &str, distribution: &str, request: Vec<models::ApiSourceParams>, _async: Option<bool>) -> Result<(), Error<ApiPublishPrefixDistributionSourcesPutError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_prefix = prefix;
    let p_path_distribution = distribution;
    let p_body_request = request;
    let p_query__async = _async;

    let uri_str = format!("{}/api/publish/{prefix}/{distribution}/sources", configuration.base_path, prefix=crate::apis::urlencode(p_path_prefix), distribution=crate::apis::urlencode(p_path_distribution));
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref param_value) = p_query__async {
        req_builder = req_builder.query(&[("_async", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<ApiPublishPrefixDistributionSourcesPutError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// **Update a published repository**  Publish pending source component changes which were added with `Add/Remove/Replace Source Components`  See also: `aptly publish update`
pub async fn api_publish_prefix_distribution_update_post(configuration: &configuration::Configuration, prefix: &str, distribution: &str, request: models::ApiPublishedRepoUpdateParams, _async: Option<bool>) -> Result<models::DebPublishedRepo, Error<ApiPublishPrefixDistributionUpdatePostError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_prefix = prefix;
    let p_path_distribution = distribution;
    let p_body_request = request;
    let p_query__async = _async;

    let uri_str = format!("{}/api/publish/{prefix}/{distribution}/update", configuration.base_path, prefix=crate::apis::urlencode(p_path_prefix), distribution=crate::apis::urlencode(p_path_distribution));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref param_value) = p_query__async {
        req_builder = req_builder.query(&[("_async", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::DebPublishedRepo`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::DebPublishedRepo`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ApiPublishPrefixDistributionUpdatePostError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// **Publish a local repository or snapshot**  Create a published repository.  The prefix may contain a storage specifier, e.g. `s3:packages/`, or it may also be empty to publish to the root directory.  **Example:** ``` $ curl -X POST -H 'Content-Type: application/json' --data '{\"Distribution\": \"wheezy\", \"Sources\": [{\"Name\": \"aptly-repo\"}]}' http://localhost:8080/api/publish//repos {\"Architectures\":[\"i386\"],\"Distribution\":\"wheezy\",\"Label\":\"\",\"Origin\":\"\",\"Prefix\":\".\",\"SourceKind\":\"local\",\"Sources\":[{\"Component\":\"main\",\"Name\":\"aptly-repo\"}],\"Storage\":\"\"} ```  See also: `aptly publish create`
pub async fn api_publish_prefix_post(configuration: &configuration::Configuration, prefix: &str, request: models::ApiPublishedRepoCreateParams, _async: Option<bool>) -> Result<models::DebPublishedRepo, Error<ApiPublishPrefixPostError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_prefix = prefix;
    let p_body_request = request;
    let p_query__async = _async;

    let uri_str = format!("{}/api/publish/{prefix}", configuration.base_path, prefix=crate::apis::urlencode(p_path_prefix));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref param_value) = p_query__async {
        req_builder = req_builder.query(&[("_async", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::DebPublishedRepo`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::DebPublishedRepo`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ApiPublishPrefixPostError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

